const $=s=>document.querySelector(s);let db=null;const ui={series:'all',type:'all',q:'',spoiler:localStorage.getItem('adk-wiki-spoiler')!=='off',theme:localStorage.getItem('adk-theme')||'dark'};const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));function apply(){document.body.classList.toggle('light',ui.theme==='light');document.body.classList.toggle('spoiler-off',!ui.spoiler);$('#spoilerToggle').textContent=`Spoiler: ${ui.spoiler?'Bật':'Tắt'}`;$('#spoilerToggle').classList.toggle('active',ui.spoiler)}
$('#themeToggle').onclick=()=>{ui.theme=ui.theme==='dark'?'light':'dark';localStorage.setItem('adk-theme',ui.theme);apply()};$('#spoilerToggle').onclick=()=>{ui.spoiler=!ui.spoiler;localStorage.setItem('adk-wiki-spoiler',ui.spoiler?'on':'off');apply()};apply();
function monogram(x){return (x.name||x.title).split(/\s+/).slice(-2).map(v=>v[0]||'').join('').toUpperCase()}
function portrait(x,large=false){const concept=x.type!=='character';return `<div class="portrait ${concept?'concept':''}" style="--c1:${x.palette?.[0]||'#30232a'};--c2:${x.palette?.[1]||'#101014'};--hair:${x.hair||'#0d0d0f'}">${concept?`<div class="sigil">${esc(x.sigil||'◈')}</div>`:`<span class="monogram">${esc(monogram(x))}</span><span class="country">${esc(x.nationality||'VIỆT NAM')}</span>`}</div>`}
function hash(){return decodeURIComponent(location.hash.replace(/^#/,''))}
async function init(){db=await fetch('wiki-data.json').then(r=>r.json());renderTabs();renderStats();route();$('#searchInput').addEventListener('input',e=>{ui.q=e.target.value.trim().toLowerCase();renderGrid()});window.addEventListener('hashchange',route)}
function renderTabs(){const series=[['all','Tất cả'],...db.series.map(x=>[x.id,x.short])];$('#seriesTabs').innerHTML=series.map(([id,label])=>`<button class="tab ${ui.series===id?'active':''}" data-series="${id}">${esc(label)}</button>`).join('');document.querySelectorAll('[data-series]').forEach(b=>b.onclick=()=>{ui.series=b.dataset.series;renderTabs();renderGrid()});const types=[['all','Mọi loại'],['character','Nhân vật'],['organization','Tổ chức'],['concept','Khái niệm'],['artifact','Vật phẩm'],['place','Địa điểm'],['phenomenon','Hiện tượng']];$('#typeTabs').innerHTML=types.map(([id,label])=>`<button class="tab ${ui.type===id?'active':''}" data-type="${id}">${label}</button>`).join('');document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{ui.type=b.dataset.type;renderTabs();renderGrid()})}
function renderStats(){const chars=db.entries.filter(x=>x.type==='character').length,lore=db.entries.length-chars,series=db.series.length,foreign=db.entries.filter(x=>x.type==='character'&&x.nationality&&x.nationality!=='Việt Nam').length;$('#stats').innerHTML=[[chars,'nhân vật'],[lore,'hồ sơ thế giới'],[series,'bộ truyện'],[foreign,'nhân vật nước ngoài']].map(x=>`<div class="stat"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}
function route(){const h=hash();if(h.startsWith('entry/')){showDetail(h.slice(6));return}showGrid()}
function showGrid(){$('#detail').classList.add('hidden');$('#grid').classList.remove('hidden');$('.hero').classList.remove('hidden');$('#stats').classList.remove('hidden');renderGrid();document.title='Âm Dương Kí Wiki'}
function match(x){if(ui.series!=='all'&&!x.series.includes(ui.series))return false;if(ui.type!=='all'&&x.type!==ui.type)return false;if(!ui.q)return true;const bag=[x.name,x.title,x.role,x.summary,x.aliases?.join(' '),x.tags?.join(' '),x.appearance,x.bio].join(' ').toLowerCase();return bag.includes(ui.q)}
function renderGrid(){const list=db.entries.filter(match);$('#grid').innerHTML=list.length?list.map(x=>`<section class="wiki-card" onclick="location.hash='entry/${encodeURIComponent(x.id)}'">${portrait(x)}<div class="card-copy"><span class="card-kicker">${esc(x.typeLabel)} · ${esc(seriesLabel(x.series))}</span><h2>${esc(x.name||x.title)}</h2><p>${esc(x.summary)}</p><div class="tags">${(x.tags||[]).slice(0,4).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div></section>`).join(''):'<p class="empty">Không tìm thấy hồ sơ phù hợp.</p>'}
function seriesLabel(ids){return ids.map(id=>db.series.find(s=>s.id===id)?.short||id).join(' · ')}
function showDetail(id){const x=db.entries.find(e=>e.id===id);if(!x){location.hash='';return}$('.hero').classList.add('hidden');$('#stats').classList.add('hidden');$('#grid').classList.add('hidden');const d=$('#detail');d.classList.remove('hidden');const facts=[['Loại',x.typeLabel],['Xuất hiện',seriesLabel(x.series)],x.age?['Tuổi',x.age]:null,x.nationality?['Quốc tịch',x.nationality]:null,x.occupation?['Vai trò/nghề',x.occupation]:null,x.status?['Trạng thái',x.status]:null].filter(Boolean);d.innerHTML=`<button class="detail-back" onclick="location.hash=''">← Wiki</button><section class="profile-hero">${portrait(x,true)}<div class="profile-title"><p class="eyebrow">${esc(x.typeLabel)} · ${esc(seriesLabel(x.series))}</p><h1>${esc(x.name||x.title)}</h1><p class="lead">${esc(x.role||x.summary)}</p><div class="facts">${facts.map(f=>`<div class="fact"><span>${esc(f[0])}</span><b>${esc(f[1])}</b></div>`).join('')}</div><div class="tags">${(x.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div></section>${section('Ngoại hình',x.appearance)}${outfits(x.outfits)}${section('Tính cách & dấu nhận diện',x.personality)}${section('Tiểu sử',x.bio,x.bioSpoiler)}${section('Quan hệ',x.relationships)}${section('Vai trò trong vũ trụ',x.universe,x.universeSpoiler)}${mini(x.miniStory)}${x.notes?section('Ghi chú canon',x.notes):''}`;window.scrollTo(0,0);document.title=`${x.name||x.title} — Âm Dương Kí Wiki`}
function section(title,text,spoiler=false){if(!text)return'';return `<section class="detail-section"><h2>${esc(title)}</h2><div class="${spoiler?'spoiler-block':''}"><p>${esc(text).replace(/\n/g,'<br>')}</p></div></section>`}
function outfits(list){if(!list?.length)return'';return `<section class="detail-section"><h2>Trang phục theo giai đoạn</h2><div class="outfits">${list.map(o=>`<div class="outfit"><b>${esc(o.label)}</b><span>${esc(o.text)}</span></div>`).join('')}</div></section>`}
function mini(m){if(!m)return'';return `<section class="detail-section"><h2>${esc(m.title||'Mini story')}</h2><div class="mini-story ${m.spoiler?'spoiler-block':''}"><p>${esc(m.text).replace(/\n/g,'<br>')}</p></div></section>`}
init().catch(e=>{console.error(e);$('#grid').innerHTML='<p class="empty">Không tải được dữ liệu wiki.</p>'});