window.PT_SOURCE = {
  schemaVersion: 3,
  sourceUpdatedAt: "2026-08-12T23:29:00+07:00",
  sourceOfTruth: "Tu4nla/MyGym",

  profile: {
    sex: "Nam",
    age: 25,
    heightCm: 163,
    weightKg: 59,
    job: "Lập trình viên",
    trainingAge: "Khoảng 2 tháng",
    baselineWeightKg: 53,
    goal: "Body recomposition: giảm vòng bụng, tăng cơ, giữ cân tương đối ổn định",
    preferredGymWindow: "20:00–21:20",
    preferredSleepTime: "23:30"
  },

  // Inventory CANONICAL theo 79 checkbox đã chọn trước đó,
  // đã gộp 7 cặp alias/trùng thành 72 thiết bị vật lý thực tế.
  equipment: {
    mode: "source-controlled",
    selectedCheckboxCountBeforeAliasMerge: 79,
    physicalEquipmentCount: 72,
    confirmedFromCurrentProfile: [
      "incline-chest-press",
      "converging-chest-press",
      "seated-chest-press",
      "pec-fly-rear-delt-combo",
      "vertical-chest-press",
      "iso-lateral-chest-press",
      "decline-chest-press",
      "lat-pulldown",
      "front-lat-pulldown",
      "low-row-machine",
      "seated-row",
      "t-bar-row-machine",
      "rear-delt-machine",
      "shoulder-press",
      "lateral-raise",
      "lying-leg-curl",
      "leg-extension-curl-combo",
      "seated-leg-press",
      "horizontal-leg-press",
      "45-degree-leg-press",
      "hack-squat",
      "v-squat",
      "seated-calf-raise",
      "seated-dip",
      "biceps-curl",
      "preacher-curl-machine",
      "rotary-torso",
      "vertical-knee-raise",
      "dual-adjustable-pulley",
      "cable-crossover",
      "lat-pulldown-low-row-combo",
      "multi-press-machine",
      "half-rack",
      "squat-stand",
      "adjustable-bench",
      "flat-bench",
      "olympic-flat-bench",
      "olympic-incline-bench",
      "olympic-decline-bench",
      "decline-situp-bench",
      "preacher-curl-bench",
      "utility-stool",
      "fixed-dumbbells",
      "dumbbell-rack",
      "kettlebells",
      "fixed-barbells",
      "olympic-barbell",
      "ez-curl-bar",
      "straight-curl-bar",
      "trap-hex-bar",
      "swiss-multigrip-bar",
      "cambered-bar",
      "calibrated-plates",
      "fractional-plates",
      "bumper-plates",
      "lat-pulldown-bar",
      "straight-cable-bar",
      "ez-curl-cable-bar",
      "rope-attachment",
      "v-row-handle",
      "d-handle",
      "double-d-handle",
      "triceps-v-bar",
      "treadmill",
      "elliptical",
      "spin-bike",
      "air-bike",
      "ab-roller-wheel",
      "pushup-bars",
      "sandbag",
      "foam-roller",
      "yoga-mat"
    ],
    aliasMerges: [
      ["Chest Press Machine", "Seated Chest Press Machine"],
      ["Pec Fly / Rear Delt", "Pec Fly / Rear Delt Combo"],
      ["T-Bar Row", "T-Bar Row Machine"],
      ["Captain's Chair", "Vertical Knee Raise Station"],
      ["Swiss Bar", "Swiss Multi-Grip Bar"],
      ["Straight Bar Attachment", "Straight Cable Bar"],
      ["Cable Rope", "Rope Attachment"]
    ],
    unresolvedEquipment: []
  },

  trainingPolicy: {
    mode: "rolling-sequence",
    preferredStrengthWeekdays: [1, 2, 4, 6],
    sequence: ["upperA", "lowerA", "upperB", "lowerB"],
    rules: {
      missedWorkout: "Không ghép hai buổi tạ vào cùng một ngày để trả nợ. Buổi bị lỡ vẫn là buổi kế tiếp trong chuỗi.",
      partialWorkoutThresholdPct: 60,
      partialWorkoutRule: "Nếu hoàn thành >=60% planned sets và các compound chính đã làm, có thể tính buổi là hoàn thành; không cần đuổi toàn bộ accessory vào hôm sau.",
      lowRecovery: "Ngủ <6 giờ và energy <=2/5: giảm khoảng 20% planned sets, giữ RIR >=2, không cố failure.",
      pain: "Đau bất thường không được tự động xử lý như DOMS: dừng bài gây đau; app không chẩn đoán chấn thương.",
      missedMeal: "Không ăn bù gấp đôi ở bữa sau. Quay lại kế hoạch; ưu tiên đưa protein còn thiếu vào các bữa còn lại nếu vẫn phù hợp tiêu hoá và tổng năng lượng.",
      offPlanMeal: "Không phạt bằng bỏ bữa hoặc cardio quá mức. Ghi nhận, rồi quay lại cấu trúc bữa kế tiếp."
    }
  },

  syncedEvents: [],
  syncedMeasurements: [],
  syncedWorkoutSessions: []
};