(()=>{
const D=window.PT_DATA||{},S=window.PT_SOURCE||{},C=window.PT_CLOUD_CONFIG;if(!C||!window.supabase)return;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
const day=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},add=(k,n)=>{const[y,m,d]=k.split('-').map(Number),x=new Date(y,m-1,d,12);x.setDate(x.getDate()+n);return`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const sb=window.supabase.createClient(C.url,C.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const st={user:null,todos:[],entries:[],sessions:[],sets:[],measurements:[],analyses:[],insights:[],messages:[],eq:new Map(),busy:false,install:null};
function toast(t){const e=$('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)}
function dom(){document.documentElement.classList.add('pt-v4');document.title='MyGym Personal PT v4';const eb=document.querySelector('.pt-header .eyebrow');if(eb)eb.textContent='PERSONAL FITNESS OS • V4';
 if($('panel-today')&&!$('v4-home')){const e=document.createElement('section');e.id='v4-home';$('panel-today').prepend(e)}
 if($('panel-progress')&&!$('v4-week')){const e=document.createElement('section');e.id='v4-week';e.innerHTML='<div class="section-head"><div><p class="eyebrow">WEEKLY REVIEW</p><h2>Tuần của bạn</h2></div><button id="v4-week-ai" class="mini-btn">AI review</button></div><div id="v4-week-body"></div>';$('panel-progress').append(e)}
 if($('panel-workout')&&!$('v4-swap')){const e=document.createElement('section');e.id='v4-swap';e.innerHTML='<div class="section-head"><div><p class="eyebrow">SMART SWAP</p><h2>Máy bận? Đổi nhanh</h2></div></div><div id="v4-swap-body"></div>';$('panel-workout').append(e)}
 if($('panel-nutrition')&&!$('v4-meal')){const e=document.createElement('section');e.id='v4-meal';e.innerHTML='<div class="section-head"><div><p class="eyebrow">MEAL ASSISTANT</p><h2>Ước tính bữa ăn</h2></div></div><div class="card v4-meal"><p class="muted">Mô tả món + khẩu phần gần đúng. AI chỉ ước tính khi dữ liệu chưa đủ.</p><textarea id="v4-meal-input" rows="3" placeholder="VD: 1 chén cơm, 150g gà, 2 trứng..."></textarea><button id="v4-meal-btn" class="primary">Ước tính & gợi ý</button><div id="v4-meal-out" class="v4-ai-out hidden"></div></div>';$('panel-nutrition').append(e)}
 if($('panel-coach')&&!$('v4-coach')){const e=document.createElement('section');e.id='v4-coach';e.innerHTML='<div class="section-head"><div><p class="eyebrow">AI COACH</p><h2>Hỏi PT bất cứ lúc nào</h2></div><span id="v4-ai-status" class="pill">Kiểm tra AI</span></div><div class="v4-coach-grid"><div class="card"><div class="v4-head"><div><p class="eyebrow">DAILY BRIEF</p><h3 id="v4-ai-title">Rule engine đang hoạt động</h3></div><button id="v4-daily-ai" class="mini-btn">Phân tích</button></div><div id="v4-ai-latest" class="v4-ai-out"><p class="muted">AI Coach dùng context 14 ngày; deterministic engine vẫn giữ quyền ưu tiên về an toàn.</p></div></div><div class="card v4-chat"><div id="v4-chat-log"></div><form id="v4-chat-form"><textarea id="v4-chat-input" rows="2" placeholder="Tối nay chỉ có 45 phút, nên tập gì?"></textarea><button class="primary">Gửi</button></form></div></div>'; $('coach-analysis')?.insertAdjacentElement('afterend',e)}
 if(!$('v4-install')){const b=document.createElement('button');b.id='v4-install';b.className='v4-install hidden';b.textContent='＋ Cài My PT';document.body.append(b)}}
async function equipment(){try{const c=await fetch('equipment-catalog.json?v=5').then(r=>r.json()),xs=await Promise.all((c.dataFiles||[]).map(p=>fetch(`${p}?v=5`).then(r=>r.json())));xs.flat().forEach(x=>{if(!st.eq.has(x.id))st.eq.set(x.id,x)})}catch(e){console.warn(e)}}
async function profile(){if(!st.user)return;const p={...(S.profile||{}),calorieTarget:D.profile?.calorieTarget,proteinTarget:D.profile?.proteinTarget,waterTargetMl:D.profile?.waterTargetMl,stepsTarget:D.profile?.stepsTarget,equipmentCount:S.equipment?.physicalEquipmentCount||S.equipment?.confirmedFromCurrentProfile?.length||0,productVersion:4};const{error}=await sb.from('pt_profiles').upsert({user_id:st.user.id,display_name:st.user.email?.split('@')[0]||'MyGym User',timezone:C.timezone||'Asia/Ho_Chi_Minh',profile:p},{onConflict:'user_id'});if(error)console.warn(error)}
async function load(){if(!st.user){render();return}const s=add(day(),-30),u=st.user.id,r=await Promise.all([sb.from('pt_todos').select('*').eq('user_id',u).gte('todo_date',s).order('todo_date'),sb.from('pt_daily_entries').select('*').eq('user_id',u).gte('entry_date',s).order('created_at'),sb.from('pt_workout_sessions').select('*').eq('user_id',u).gte('workout_date',s).order('workout_date'),sb.from('pt_exercise_sets').select('*').eq('user_id',u).gte('created_at',`${s}T00:00:00`).order('created_at'),sb.from('pt_measurements').select('*').eq('user_id',u).gte('measured_at',s).order('measured_at'),sb.from('pt_analysis_snapshots').select('*').eq('user_id',u).gte('analysis_date',s).order('created_at'),sb.from('pt_ai_insights').select('*').eq('user_id',u).gte('insight_date',s).order('created_at'),sb.from('pt_coach_messages').select('*').eq('user_id',u).order('created_at',{ascending:false}).limit(30)]),ks=['todos','entries','sessions','sets','measurements','analyses','insights','messages'];r.forEach((x,i)=>{if(x.error)console.warn(ks[i],x.error);else st[ks[i]]=x.data||[]});st.messages=[...st.messages].reverse();render()}
const checkin=()=>st.entries.filter(x=>x.entry_date===day()&&x.entry_type==='checkin').at(-1)?.payload||null;
function ready(){const c=checkin();if(!c)return{score:58,label:'Chưa đủ dữ liệu',tone:'',why:'Check-in để cá nhân hóa hôm nay.'};let n=64,h=+c.sleepHours||0,e=+c.energy||3,s=+c.soreness||1;n+=h>=7.5?16:h>=6.5?8:h>=6?0:-18;n+=(e-3)*7;n-=Math.max(0,s-1)*8;n=clamp(Math.round(n),15,98);if(s>=4)return{score:Math.min(n,35),label:'Ưu tiên an toàn',tone:'danger',why:'Bạn đã báo đau bất thường.'};return n>=78?{score:n,label:'Sẵn sàng tốt',tone:'good',why:'Recovery đủ tốt để theo giáo án.'}:n>=58?{score:n,label:'Sẵn sàng vừa',tone:'warn',why:'Tập được nhưng giữ kỹ thuật và RIR.'}:{score:n,label:'Recovery thấp',tone:'danger',why:'Giảm volume và ưu tiên hồi phục.'}}
const doneSessions=()=>st.sessions.filter(x=>['complete','partial_counted'].includes(String(x.status||'').replaceAll('-','_'))),nextId=()=>{const q=S.trainingPolicy?.sequence||['upperA','lowerA','upperB','lowerB'];return q[doneSessions().length%q.length]};
function plan(){const o=st.entries.filter(x=>x.entry_date===day()&&x.entry_type==='schedule_change').at(-1)?.payload;if(o?.type==='sick_or_pain')return{type:'rest',title:'Recovery / không cố tập'};if(o?.type==='skip_workout')return{type:'rest',title:'Hôm nay nghỉ'};const dow=new Date().getDay();if(S.trainingPolicy?.preferredStrengthWeekdays?.includes(dow)){const id=nextId();return{type:'strength',workoutId:id,title:D.workouts?.[id]?.title||id}}return D.week?.[dow]||{type:'rest',title:'Recovery'}}
function todoStats(k=day()){const a=st.todos.filter(x=>x.todo_date===k),d=a.filter(x=>x.completed).length;return{a,d,n:a.length,p:a.length?Math.round(d*100/a.length):0}}const water=()=>+st.entries.filter(x=>x.entry_date===day()&&x.entry_key==='water-total').at(-1)?.payload?.ml||0;
function nextAction(){const t=todoStats(),p=plan(),h=new Date().getHours()+new Date().getMinutes()/60,f=k=>t.a.find(x=>x.todo_key===k);if(!checkin())return['◉','Check-in 30 giây','Ngủ, năng lượng và đau/mỏi quyết định volume hôm nay.','checkin'];if(p.type==='strength'&&!f('workout')?.completed&&h>=18)return['▶',`Bắt đầu ${p.title}`,'Giữ rolling sequence; không cần bù buổi cũ.','workout'];if(water()<(D.profile?.waterTargetMl||2500)*.55&&h>=14)return['◌','Bổ sung nước',`Bạn mới log ${water()} ml. Uống thêm theo khát và vận động.`,'water'];if(!f('protein')?.completed&&h>=20.5)return['◎','Khóa protein hôm nay','Ưu tiên bữa tối có nguồn protein rõ ràng.','nutrition'];if(h>=22.8)return['☾','Chuẩn bị ngủ','Giảm màn hình và chốt ngày để bảo vệ recovery.','sleep'];const u=t.a.find(x=>!x.completed);return u?['✓',u.title,u.payload?.defaultNote||'Một việc nhỏ tiếp theo.','todo']:['✓','Ngày đang đi đúng hướng','Duy trì nhịp hiện tại; không cần tối ưu cực đoan.','done']}
function metric(a,b,c,p){return`<div class="v4-kpi"><span>${esc(a)}</span><strong>${esc(b)}</strong><small>${esc(c)}</small><i><b style="width:${clamp(p,0,100)}%"></b></i></div>`}
function home(){const e=$('v4-home');if(!e)return;const r=ready(),t=todoStats(),p=plan(),n=nextAction(),ec=S.equipment?.physicalEquipmentCount||S.equipment?.confirmedFromCurrentProfile?.length||0;e.innerHTML=`<div class="v4-hero"><article class="v4-ready ${r.tone}"><div class="v4-ring" style="--p:${r.score}"><div><strong>${r.score}</strong><span>readiness</span></div></div><div><p class="eyebrow">COMMAND CENTER</p><h2>${esc(r.label)}</h2><p>${esc(r.why)}</p><div class="v4-tags"><span>${esc(p.title)}</span><span>${t.p}% todo</span><span>${ec} thiết bị</span></div></div></article><article class="v4-next"><b>${n[0]}</b><div><p class="eyebrow">NEXT BEST ACTION</p><h3>${esc(n[1])}</h3><p>${esc(n[2])}</p></div><button id="v4-go" class="primary">Làm ngay</button></article></div><div class="v4-kpis">${metric('Adherence',`${t.p}%`,`${t.d}/${t.n||0} việc`,t.p)}${metric('Nước',`${(water()/1000).toFixed(1)}L`,`mục tiêu ${(D.profile?.waterTargetMl||2500)/1000}L`,Math.min(100,water()*100/(D.profile?.waterTargetMl||2500)))}${metric('Workout',p.type==='strength'?p.title:'Recovery',p.type==='strength'?'rolling sequence':'không ép tập',p.type==='strength'?68:100)}${metric('Cloud',st.user?'LIVE':'LOCAL',st.user?'đa thiết bị':'cần đăng nhập',st.user?100:35)}</div><div class="section-head"><div><p class="eyebrow">14-DAY SIGNAL</p><h2>Nhịp gần đây</h2></div><button id="v4-refresh" class="mini-btn">Refresh</button></div><div id="v4-days" class="v4-days"></div>`;$('v4-go').onclick=()=>go(n[3]);$('v4-refresh').onclick=load;timeline()}
function go(a){if(a==='checkin')return $('checkin-form')?.scrollIntoView({behavior:'smooth',block:'center'});if(a==='workout')return document.querySelector('.tab[data-tab="workout"]')?.click();if(a==='nutrition')return document.querySelector('.tab[data-tab="nutrition"]')?.click();if(a==='water')return $('quick-water')?.focus();if(a==='sleep')return toast('Chuẩn bị ngủ: giảm màn hình và ánh sáng mạnh.');document.querySelector('[data-todo-check]:not(:checked)')?.scrollIntoView({behavior:'smooth',block:'center'})}
function timeline(){const e=$('v4-days');if(!e)return;e.innerHTML=Array.from({length:14},(_,i)=>add(day(),i-13)).map(k=>{const t=todoStats(k),s=st.sessions.filter(x=>x.workout_date===k).at(-1),c=st.entries.some(x=>x.entry_date===k&&x.entry_type==='checkin'),z=['complete','partial_counted'].includes(String(s?.status||'').replaceAll('-','_'))?'trained':s?.status==='skipped'?'skipped':c?'logged':'';return`<div class="v4-day ${z} ${k===day()?'today':''}"><span>${new Intl.DateTimeFormat('vi-VN',{weekday:'short'}).format(new Date(`${k}T12:00`))}</span><strong>${k.slice(-2)}</strong><i style="--p:${t.p}%"></i></div>`}).join('')}
function weekly(){const s=add(day(),-6),ts=st.todos.filter(x=>x.todo_date>=s),ad=ts.length?Math.round(ts.filter(x=>x.completed).length*100/ts.length):0,ss=st.sessions.filter(x=>x.workout_date>=s),wo=ss.filter(x=>['complete','partial_counted'].includes(String(x.status||'').replaceAll('-','_'))).length,sk=ss.filter(x=>x.status==='skipped').length,cs=st.entries.filter(x=>x.entry_date>=s&&x.entry_type==='checkin'&&x.entry_key==='daily-checkin'),sl=cs.map(x=>+x.payload?.sleepHours).filter(Number.isFinite),en=cs.map(x=>+x.payload?.energy).filter(Number.isFinite),ms=st.measurements.filter(x=>x.measured_at>=s),f=ms[0],l=ms.at(-1),dw=f?.weight_kg!=null&&l?.weight_kg!=null?+l.weight_kg-+f.weight_kg:null,de=f?.waist_cm!=null&&l?.waist_cm!=null?+l.waist_cm-+f.waist_cm:null,sets=st.sets.filter(x=>x.created_at?.slice(0,10)>=s&&x.completed),ton=Math.round(sets.reduce((a,x)=>a+(+x.weight_kg||0)*(+x.reps||0),0)),score=clamp(Math.round(ad*.55+Math.min(100,wo/4*100)*.3+((avg(sl)||6.5)/8*15)),0,100);return{s,ad,wo,sk,sl:avg(sl),en:avg(en),dw,de,sets:sets.length,ton,score}}
function week(){const e=$('v4-week-body');if(!e)return;const w=weekly(),sig=[];if(w.sl!=null&&w.sl<6.5)sig.push('Giấc ngủ đang là bottleneck lớn nhất.');if(w.ad<65)sig.push('Adherence thấp: giảm việc bắt buộc, ưu tiên hành vi đòn bẩy.');if(w.dw!=null&&w.de!=null&&Math.abs(w.dw)<=.5&&w.de<0)sig.push('Recomp signal tốt: cân khá ổn định trong khi eo giảm.');if(w.dw!=null&&w.de!=null&&w.dw>.5&&w.de>.5)sig.push('Cân và eo cùng tăng: theo dõi thêm trước khi đổi calories.');if(!sig.length)sig.push('Chưa có xu hướng đủ mạnh để đổi kế hoạch.');e.innerHTML=`<div class="v4-week"><div class="v4-week-score"><div class="v4-ring small" style="--p:${w.score}"><div><strong>${w.score}</strong><span>consistency</span></div></div><h3>${w.score>=75?'Tuần ổn định':w.score>=55?'Tuần cần tinh chỉnh':'Xây lại nhịp'}</h3><p class="muted">${w.s} → ${day()}</p></div><div class="v4-week-kpis">${metric('Adherence',`${w.ad}%`,'todo hoàn thành',w.ad)}${metric('Strength',`${w.wo} buổi`,`${w.sk} buổi bỏ`,Math.min(100,w.wo/4*100))}${metric('Sleep',w.sl==null?'—':`${w.sl.toFixed(1)}h`,w.en==null?'chưa đủ log':`energy ${w.en.toFixed(1)}/5`,Math.min(100,(w.sl||0)/8*100))}${metric('Training',`${w.sets} sets`,`${w.ton.toLocaleString('vi-VN')} kg·reps`,Math.min(100,w.sets/45*100))}</div><div class="card v4-signals"><p class="eyebrow">SIGNALS</p>${sig.map(x=>`<p>• ${esc(x)}</p>`).join('')}<div>${w.dw==null?'':`<span>Δ cân ${w.dw>0?'+':''}${w.dw.toFixed(1)} kg</span>`}${w.de==null?'':`<span>Δ eo ${w.de>0?'+':''}${w.de.toFixed(1)} cm</span>`}</div></div></div>`}
function swap(){const e=$('v4-swap-body');if(!e)return;const id=plan().workoutId||nextId(),w=D.workouts?.[id],ok=new Set(S.equipment?.confirmedFromCurrentProfile||[]);if(!w)return e.innerHTML='<div class="card muted">Chưa có workout để gợi ý.</div>';e.innerHTML='<div class="v4-swaps">'+w.exercises.map(r=>{const key=r[0],x=D.exerciseLibrary?.[key];if(!x)return'';const direct=(x.equipment||[]).filter(i=>ok.has(i)),token=String(x.primary||'').split('•')[0].trim().toLowerCase(),alts=Object.entries(D.exerciseLibrary||{}).filter(([k,a])=>k!==key&&String(a.primary||'').toLowerCase().includes(token)&&(a.equipment||[]).some(i=>ok.has(i))).slice(0,3);return`<article class="card"><p class="eyebrow">${esc(x.nameVi||'')}</p><h3>${esc(x.name)}</h3><p class="muted">${direct.length?direct.map(i=>esc(st.eq.get(i)?.name||i)).join(' · '):'Không có map máy trực tiếp'}</p>${alts.length?`<details><summary>Phương án thay bài</summary>${alts.map(([,a])=>`<div class="v4-alt"><b>${esc(a.name)}</b><span>${esc((a.equipment||[]).filter(i=>ok.has(i)).map(i=>st.eq.get(i)?.name||i).join(' · '))}</span></div>`).join('')}</details>`:''}</article>`}).join('')+'</div>'}
function aiContext(input=''){const s=add(day(),-14);return{date:day(),userInput:input||null,profile:{...(S.profile||{}),...(D.profile||{})},rules:S.trainingPolicy?.rules||{},equipmentCount:S.equipment?.physicalEquipmentCount||0,todayPlan:plan(),readiness:ready(),weekly:weekly(),todos:st.todos.filter(x=>x.todo_date>=s),entries:st.entries.filter(x=>x.entry_date>=s).slice(-80),sessions:st.sessions.filter(x=>x.workout_date>=s).slice(-20),sets:st.sets.filter(x=>x.created_at?.slice(0,10)>=s).slice(-120),measurements:st.measurements.filter(x=>x.measured_at>=s),deterministic:st.analyses.filter(x=>x.analysis_date>=s).slice(-10)}}
function aiStatus(t,c=''){const e=$('v4-ai-status');if(e){e.textContent=t;e.className=`pill ${c}`}}
async function ai(mode,input='',opt={}){if(!st.user){aiStatus('Cần đăng nhập','warn');if(!opt.silent)toast('Đăng nhập để dùng AI Coach.');return null}if(st.busy)return null;st.busy=true;aiStatus('AI đang nghĩ…','warn');try{const{data,error}=await sb.functions.invoke('pt-ai-coach',{body:{mode,message:input,trigger:opt.trigger||'manual',context:aiContext(input)}});if(error)throw error;const text=String(data?.text||data?.message||'').trim();if(!text)throw Error('AI không trả nội dung');aiStatus('AI LIVE','good');if(mode==='chat')await saveChat(input,text,data?.model);else await saveInsight(mode,text,data?.model,opt.trigger||'manual');return text}catch(e){console.warn('AI',e);aiStatus('AI chưa sẵn sàng','warn');if(!opt.silent)toast('AI Coach chưa sẵn sàng; rule engine vẫn hoạt động.');return null}finally{st.busy=false}}
async function saveInsight(kind,text,model,trigger){const k=`ai:${kind}:${day()}`,row={user_id:st.user.id,insight_date:day(),trigger_type:trigger,kind,title:kind==='weekly'?'Weekly AI Review':kind==='meal_estimate'?'Meal Estimate':kind==='workout_review'?'Workout Review':'Daily AI Brief',summary:text.slice(0,700),content:{text},model:model||null,client_key:k,updated_at:new Date().toISOString()},{data,error}=await sb.from('pt_ai_insights').upsert(row,{onConflict:'user_id,client_key'}).select().single();if(!error&&data){const i=st.insights.findIndex(x=>x.client_key===k);i>=0?st.insights[i]=data:st.insights.push(data);renderAI()}}
async function saveChat(q,a,model){const t=Date.now(),rows=[{user_id:st.user.id,role:'user',content:q,client_key:`chat:user:${t}:${Math.random()}`,metadata:{}},{user_id:st.user.id,role:'assistant',content:a,client_key:`chat:assistant:${t}:${Math.random()}`,metadata:{model:model||null}}],{data,error}=await sb.from('pt_coach_messages').insert(rows).select();if(!error&&data){st.messages.push(...data);renderAI()}}
function renderAI(){const e=$('v4-ai-latest'),t=$('v4-ai-title'),x=[...st.insights].filter(x=>['daily','weekly','workout_review'].includes(x.kind)).sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))).at(-1);if(x&&e){t.textContent=x.title||'AI Coach';e.innerHTML=`<p>${esc(x.content?.text||x.summary||'')}</p><small>${esc(x.kind)} • ${esc(x.model||'AI')}</small>`;aiStatus('AI history ready','good')}else aiStatus(st.user?'Sẵn sàng':'Cần đăng nhập',st.user?'':'warn');const l=$('v4-chat-log');if(l){const m=st.messages.slice(-14);l.innerHTML=m.length?m.map(x=>`<div class="v4-msg ${x.role}"><span>${x.role==='user'?'Bạn':'AI PT'}</span><p>${esc(x.content)}</p></div>`).join(''):'<div class="v4-empty"><b>AI Coach có context fitness của bạn</b><p>Hỏi về workout, bữa ăn, lịch bị lệch, progression hoặc recovery.</p></div>';l.scrollTop=l.scrollHeight}}
function bind(){ $('v4-daily-ai').onclick=()=>ai('daily','',{trigger:'manual-daily'});$('v4-week-ai').onclick=()=>ai('weekly','',{trigger:'manual-weekly'});$('v4-chat-form').onsubmit=async e=>{e.preventDefault();const i=$('v4-chat-input'),q=i.value.trim();if(!q)return;i.value='';const tmp={role:'user',content:q,client_key:'tmp'};st.messages.push(tmp);renderAI();await ai('chat',q,{trigger:'chat'});st.messages=st.messages.filter(x=>x!==tmp);renderAI()};$('v4-meal-btn').onclick=async()=>{const q=$('v4-meal-input').value.trim(),o=$('v4-meal-out');if(!q)return toast('Mô tả bữa ăn trước.');o.classList.remove('hidden');o.innerHTML='<p>Đang phân tích…</p>';const a=await ai('meal_estimate',q,{trigger:'meal-estimate'});o.innerHTML=a?`<p>${esc(a)}</p>`:'<p class="muted">AI chưa sẵn sàng; hãy ghi meal log để theo dõi.</p>'};document.addEventListener('submit',e=>{if(['checkin-form','progress-form','change-form'].includes(e.target?.id))setTimeout(()=>autoAI('daily',e.target.id),1800)},true);document.addEventListener('click',e=>{if(e.target?.id==='player-complete-set')setTimeout(workoutAI,2200)},true)}
async function autoAI(mode,tr){if(!st.user)return;const k=`mygym.v4.auto.${day()}.${mode}.${tr}`;if(localStorage.getItem(k))return;localStorage.setItem(k,'1');await load();if(!await ai(mode,'',{trigger:`auto-${tr}`,silent:true}))localStorage.removeItem(k)}
async function workoutAI(){if(!st.user)return;const{data}=await sb.from('pt_workout_sessions').select('*').eq('user_id',st.user.id).eq('workout_date',day()).order('updated_at',{ascending:false}).limit(1),s=data?.[0];if(s&&['complete','partial_counted'].includes(String(s.status||'').replaceAll('-','_')))autoAI('workout_review',s.client_key||s.id)}
function render(){home();week();swap();renderAI()}
function realtime(){if(!st.user)return;const f=`user_id=eq.${st.user.id}`;sb.channel(`pt-v4-${st.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'pt_ai_insights',filter:f},load).on('postgres_changes',{event:'*',schema:'public',table:'pt_coach_messages',filter:f},load).subscribe()}
function pwa(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./pt-sw.js').catch(console.warn);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();st.install=e;$('v4-install')?.classList.remove('hidden')});$('v4-install').onclick=async()=>{if(!st.install)return;st.install.prompt();await st.install.userChoice;st.install=null;$('v4-install').classList.add('hidden')}}
async function init(){dom();bind();pwa();await equipment();const{data:{session}}=await sb.auth.getSession();st.user=session?.user||null;if(st.user)await profile();await load();realtime();sb.auth.onAuthStateChange((_e,s)=>setTimeout(async()=>{st.user=s?.user||null;if(st.user)await profile();await load();realtime()},0));if(new Date().getDay()===0)setTimeout(()=>autoAI('weekly','sunday-open'),2500)}init();
})();