(()=>{
  const F=window.PT_FOOD_VN||{meals:[]};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  const L={get:(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
  const typeDefs=[['all','Tất cả'],['breakfast','Sáng'],['lunch','Trưa'],['snack','Xế'],['preworkout','Pre-workout'],['dinner','Tối']];
  const order=['breakfast','lunch','snack','preworkout','dinner'];
  const labels={breakfast:'Bữa sáng',lunch:'Bữa trưa',snack:'Bữa xế',preworkout:'Pre-workout',dinner:'Bữa tối'};
  let activeType='all',search='';
  const day=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  function seed(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h)}
  function byId(id){return(F.meals||[]).find(x=>x.id===id)}
  function pool(type){let xs=(F.meals||[]).filter(x=>x.type===type);if(type==='breakfast'){const office=xs.filter(x=>x.office===true||(x.tags||[]).includes('office-friendly'));if(office.length)xs=office}return xs}
  function key(){return`mygym.v6.menu.${day()}`}
  function state(){let s=L.get(key(),null)||{date:day(),ids:[]};const selected=new Map((s.ids||[]).map(id=>{const x=byId(id);return x?[x.type,id]:null}).filter(Boolean));for(const type of order){if(selected.has(type))continue;const xs=pool(type);if(xs.length)selected.set(type,xs[seed(`${day()}:${type}:v9-menu`)%xs.length].id)}s={...s,date:day(),ids:order.map(t=>selected.get(t)).filter(Boolean)};L.set(key(),s);return s}
  function currentMeals(){return state().ids.map(byId).filter(Boolean)}
  function total(xs){return{kcal:Math.round(xs.reduce((a,x)=>a+(+x.kcal||0),0)),protein:Math.round(xs.reduce((a,x)=>a+(+x.protein||0),0)),carbs:Math.round(xs.reduce((a,x)=>a+(+x.carbs||0),0)),fat:Math.round(xs.reduce((a,x)=>a+(+x.fat||0),0))}}
  function choose(type,id){const s=state(),map=new Map(s.ids.map(x=>{const m=byId(x);return m?[m.type,x]:null}).filter(Boolean));map.set(type,id);s.ids=order.map(t=>map.get(t)).filter(Boolean);L.set(key(),s);render();window.dispatchEvent(new CustomEvent('mygym:v9-menu-changed',{detail:{type,id}}))}
  function swap(type){const xs=pool(type),s=state(),cur=s.ids.map(byId).find(x=>x?.type===type);if(!xs.length)return;const i=Math.max(0,xs.findIndex(x=>x.id===cur?.id));choose(type,xs[(i+1)%xs.length].id)}
  function mealCard(x){return`<article class="v9-menu-meal"><p class="eyebrow">${esc(labels[x.type]||x.type)}</p><h3>${esc(x.name)}</h3><p>${esc((x.tags||[]).slice(0,3).join(' • '))}</p><div class="meta"><span>≈ ${esc(x.kcal)} kcal</span><span>${esc(x.protein)}g protein</span><span>${esc(x.time||'—')} phút</span></div><button class="secondary" data-v9-swap-type="${esc(x.type)}">Đổi món khác</button></article>`}
  function foodCard(x){return`<article class="v9-food-card"><strong>${esc(x.name)}</strong><small>${esc(labels[x.type]||x.type)}${x.budget?` • ${esc(x.budget)}`:''}${x.time?` • ${esc(x.time)} phút`:''}</small><div class="meta"><span>${esc(x.kcal)} kcal</span><span>${esc(x.protein)}g P</span><span>${esc(x.carbs)}g C</span><span>${esc(x.fat)}g F</span></div><button class="mini-btn" data-v9-pick="${esc(x.id)}" data-v9-pick-type="${esc(x.type)}">Chọn cho ${esc((labels[x.type]||x.type).toLowerCase())}</button></article>`}
  function filtered(){const s=search.trim().toLowerCase();return(F.meals||[]).filter(x=>(activeType==='all'||x.type===activeType)&&(!s||`${x.name} ${(x.tags||[]).join(' ')} ${(x.ingredients||[]).join(' ')}`.toLowerCase().includes(s)))}
  function render(){const root=$('v9-food-menu');if(!root)return;const meals=currentMeals(),t=total(meals),xs=filtered();root.innerHTML=`<div class="v9-menu-hero"><p class="eyebrow">THỰC ĐƠN HÔM NAY</p><h2>Món Việt theo từng bữa</h2><p>Đây là menu mà tab Hôm nay dùng để đề xuất món đúng giờ. Bấm đổi món hoặc chọn trực tiếp từ Kho món Việt bên dưới.</p><div class="v9-menu-total"><span>${t.kcal} kcal</span><span>${t.protein}g protein</span><span>${t.carbs}g carb</span><span>${t.fat}g fat</span></div></div><div class="v9-menu-day">${meals.map(mealCard).join('')}</div><div class="v9-plan-divider"></div><div><div class="section-head"><div><p class="eyebrow">KHO MÓN VIỆT</p><h2>${xs.length} món để chọn</h2></div></div><div class="v9-food-tools"><input id="v9-food-search" class="v9-food-search" value="${esc(search)}" placeholder="Tìm: gà, cá, bánh mì, cơm, bún…"><div class="v9-food-types">${typeDefs.map(([id,label])=>`<button data-v9-food-type="${id}" class="${activeType===id?'active':''}">${label}</button>`).join('')}</div></div><div class="v9-food-library" style="margin-top:10px">${xs.map(foodCard).join('')}</div></div>`;bind()}
  function bind(){document.querySelectorAll('[data-v9-swap-type]').forEach(b=>b.onclick=()=>swap(b.dataset.v9SwapType));document.querySelectorAll('[data-v9-pick]').forEach(b=>b.onclick=()=>choose(b.dataset.v9PickType,b.dataset.v9Pick));document.querySelectorAll('[data-v9-food-type]').forEach(b=>b.onclick=()=>{activeType=b.dataset.v9FoodType;render()});const s=$('v9-food-search');if(s){let tm;s.oninput=()=>{search=s.value;clearTimeout(tm);tm=setTimeout(render,160)}}}
  function ensure(){const plan=$('panel-plan');if(!plan)return false;let root=$('v9-food-menu');if(!root){root=document.createElement('section');root.id='v9-food-menu';root.className='v9-food-menu';const intro=plan.querySelector('.v9-section-intro');intro?.insertAdjacentElement('afterend',root);if(!intro)plan.prepend(root)}render();return true}
  function boot(){if(ensure())return;const o=new MutationObserver(()=>{if(ensure())o.disconnect()});o.observe(document.body,{childList:true,subtree:true});setTimeout(()=>{ensure();o.disconnect()},3000)}
  window.addEventListener('mygym:v9-menu-changed',()=>{});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();