(()=>{
  const D=window.PT_DATA||{};
  const S=window.PT_SOURCE||{};
  const F=window.PT_FOOD_VN||{meals:[],drinks:[]};
  const C=window.PT_CLOUD_CONFIG||null;
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
  const sum=a=>a.reduce((x,y)=>x+y,0);
  const nowIso=()=>new Date().toISOString();
  const day=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const add=(k,n)=>{const[y,m,d]=k.split('-').map(Number),x=new Date(y,m-1,d,12);x.setDate(x.getDate()+n);return day(x)};
  const fmt=k=>new Intl.DateTimeFormat('vi-VN',{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(`${k}T12:00:00`));
  const L={get:(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
  const keys=['todos','entries','sessions','sets','measurements','analyses'];
  const st={todos:[],entries:[],sessions:[],sets:[],measurements:[],analyses:[],hash:'',sb:null,user:null,sorenessPart:'chest'};
  const targets={sleep:7.5,caffeineCutoffHour:15,proteinMealMin:25,proteinMealMax:35};
  const muscleParts=[['chest','Ngực'],['back','Lưng'],['shoulders','Vai'],['arms','Tay'],['quads','Đùi trước'],['hamstrings','Đùi sau'],['glutes','Mông'],['calves','Bắp chân'],['core','Core']];

  function rawHash(){return keys.map(k=>localStorage.getItem(`mygym.v3.${k}`)||'[]').join('|')}
  function read(){keys.forEach(k=>st[k]=L.get(`mygym.v3.${k}`,[]));st.hash=rawHash()}
  function toast(t){const e=$('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>e.classList.remove('show'),1700)}
  function todayEntries(type){return st.entries.filter(x=>x.entry_date===day()&&(!type||x.entry_type===type))}
  function entry(key){return todayEntries().filter(x=>x.entry_key===key).at(-1)}
  function checkin(){return todayEntries('checkin').filter(x=>x.entry_key==='daily-checkin').at(-1)?.payload||{}}
  function normStatus(s){return String(s||'').replaceAll('-','_')}
  function completedSessions(){return st.sessions.filter(x=>['complete','partial_counted'].includes(normStatus(x.status)))}
  function nextWorkoutId(){const q=S.trainingPolicy?.sequence||['upperA','lowerA','upperB','lowerB'];return q[completedSessions().length%q.length]}
  function plan(){const o=todayEntries('schedule_change').at(-1)?.payload;if(o?.type==='sick_or_pain')return{type:'rest',title:'Recovery'};if(o?.type==='skip_workout')return{type:'rest',title:'Nghỉ'};const dow=new Date().getDay();if(S.trainingPolicy?.preferredStrengthWeekdays?.includes(dow)){const id=nextWorkoutId();return{type:'strength',workoutId:id,title:D.workouts?.[id]?.title||id}}return D.week?.[dow]||{type:'rest',title:'Recovery'}}
  function water(){return +entry('water-total')?.payload?.ml||0}
  function steps(){return +entry('steps-total')?.payload?.steps||0}
  function caffeine(){return +entry('caffeine-total')?.payload?.mg||0}
  function stress(){return +entry('stress-level')?.payload?.level||0}
  function sorenessMap(){return entry('soreness-map')?.payload?.parts||{}}
  function mealsToday(){return todayEntries('meal')}
  function nutrition(){const rows=mealsToday(),kcal=Math.round(sum(rows.map(x=>+x.payload?.kcal||0))),protein=Math.round(sum(rows.map(x=>+x.payload?.protein||0))),carbs=Math.round(sum(rows.map(x=>+x.payload?.carbs||0))),fat=Math.round(sum(rows.map(x=>+x.payload?.fat||0)));return{rows,kcal,protein,carbs,fat}}
  function profileTarget(k,f){return +(D.profile?.[k]??f)}

  async function cloudSession(){if(!C||!window.supabase)return null;if(!st.sb)st.sb=window.supabase.createClient(C.url,C.publishableKey,{auth:{persistSession:true,autoRefreshToken:false,detectSessionInUrl:false}});const{data}=await st.sb.auth.getSession();st.user=data?.session?.user||null;return st.user}
  async function saveEntry(type,key,payload){
    const arr=L.get('mygym.v3.entries',[]),i=arr.findIndex(x=>x.entry_date===day()&&x.entry_type===type&&x.entry_key===key),base=i>=0?arr[i]:{},row={...base,user_id:base.user_id||st.user?.id||null,entry_date:day(),entry_type:type,entry_key:key,payload,created_at:base.created_at||nowIso(),updated_at:nowIso()};
    if(i>=0)arr[i]=row;else arr.push(row);L.set('mygym.v3.entries',arr);read();renderAll();
    const u=await cloudSession();if(u){const{error}=await st.sb.from('pt_daily_entries').upsert({user_id:u.id,entry_date:day(),entry_type:type,entry_key:key,payload},{onConflict:'user_id,entry_date,entry_type,entry_key'});if(error)console.warn('[V7 save]',error)}
  }
  async function addWater(ml){await saveEntry('activity','water-total',{ml:water()+ml,source:'v7-quick-log'});toast(`+${ml} ml nước`)}
  async function addSteps(n){await saveEntry('activity','steps-total',{steps:steps()+n,source:'v7-quick-log'});toast(`+${n.toLocaleString('vi-VN')} bước`)}
  async function addCaffeine(mg,label){const h=new Date().getHours()+new Date().getMinutes()/60;await saveEntry('activity','caffeine-total',{mg:caffeine()+mg,lastDoseMg:mg,lastDoseAt:nowIso(),lastLabel:label,afterCutoff:h>=targets.caffeineCutoffHour,source:'v7-quick-log'});toast(`+${mg} mg caffeine`)}
  async function saveStress(v){await saveEntry('checkin','stress-level',{level:+v,source:'v7'});toast('Đã lưu stress')}
  async function saveSoreness(){const host=$('v7-soreness-grid'),parts={...sorenessMap()};host?.querySelectorAll('[data-sore-part]').forEach(x=>parts[x.dataset.sorePart]=+x.value||0);await saveEntry('checkin','soreness-map',{parts,source:'v7'});toast('Đã lưu soreness theo vùng')}

  function sleepStats(){const start=add(day(),-6),rows=st.entries.filter(x=>x.entry_type==='checkin'&&x.entry_key==='daily-checkin'&&x.entry_date>=start),vals=rows.map(x=>+x.payload?.sleepHours).filter(x=>Number.isFinite(x)&&x>0),mean=avg(vals),debt=sum(vals.map(v=>Math.max(0,targets.sleep-v)));return{mean,debt,days:vals.length}}
  function hydrationPace(){const target=profileTarget('waterTargetMl',2500),h=new Date().getHours()+new Date().getMinutes()/60,awakeStart=7.7,bed=23.5,p=clamp((h-awakeStart)/(bed-awakeStart),0,1),expected=Math.round(target*p),delta=water()-expected;return{target,expected,delta,pct:target?water()/target*100:0}}
  function caffeineStatus(){const e=entry('caffeine-total'),mg=caffeine(),last=e?.payload?.lastDoseAt?new Date(e.payload.lastDoseAt):null,after=Boolean(e?.payload?.afterCutoff)||(last&&last.getHours()>=targets.caffeineCutoffHour);return{mg,last,after,label:after?'Có caffeine khá muộn':mg>250?'Khá cao hôm nay':'Ổn'}}
  function activityScore(){const wt=profileTarget('waterTargetMl',2500),stp=profileTarget('stepsTarget',8000);return Math.round(clamp((water()/wt*.45+steps()/stp*.55)*100,0,100))}
  function recoveryScore(){const c=checkin(),sl=+c.sleepHours||0,en=+c.energy||3,so=+c.soreness||1,sm=sorenessMap(),bodyMax=Math.max(0,...Object.values(sm).map(Number));let n=55;n+=sl>=7.5?20:sl>=6.5?10:sl>=6?0:-15;n+=(en-3)*6;n-=Math.max(0,so-1)*6;n-=Math.max(0,bodyMax-2)*7;n-=Math.max(0,stress()-3)*5;return clamp(Math.round(n),10,100)}
  function nutritionScore(){const n=nutrition(),ct=profileTarget('calorieTarget',2050),pt=profileTarget('proteinTarget',115),protein=Math.min(1,n.protein/pt),cal=n.kcal?1-Math.min(1,Math.abs(n.kcal-ct)/ct):0.35;return Math.round(clamp((protein*.7+cal*.3)*100,0,100))}
  function trainingScore(){const s=st.sessions.filter(x=>x.workout_date>=add(day(),-6)),done=s.filter(x=>['complete','partial_counted'].includes(normStatus(x.status))).length;return Math.round(clamp(done/4*100,0,100))}
  function dailyScore(){const r=recoveryScore(),n=nutritionScore(),a=activityScore(),t=trainingScore();return{r,n,a,t,total:Math.round(r*.3+n*.28+a*.17+t*.25)}}

  function proteinDistribution(){const groups={breakfast:0,lunch:0,snack:0,preworkout:0,dinner:0,other:0};mealsToday().forEach(x=>{const k=x.payload?.mealType||'other';groups[k]=(groups[k]||0)+(+x.payload?.protein||0)});return groups}
  function lateDinnerOptions(){return (F.meals||[]).filter(x=>x.type==='dinner'&&(+x.time||99)<=20&&(+x.fat||99)<=20).sort((a,b)=>(b.protein||0)-(a.protein||0)).slice(0,5)}
  function officeBreakfasts(){return (F.meals||[]).filter(x=>x.type==='breakfast'&&(x.office===true||(x.tags||[]).includes('office-friendly'))).sort((a,b)=>(b.protein||0)-(a.protein||0)).slice(0,8)}

  function e1rm(x){return(+x.weight_kg||0)*(1+(+x.reps||0)/30)}
  function prBoard(){const by=new Map();st.sets.filter(x=>x.completed&&+x.weight_kg>0&&+x.reps>0).forEach(x=>{const v=e1rm(x),old=by.get(x.exercise_key);if(!old||v>old.v)by.set(x.exercise_key,{v,row:x})});return[...by.entries()].map(([key,o])=>({key,nameVi:D.exerciseLibrary?.[key]?.nameVi||key,name:D.exerciseLibrary?.[key]?.name||key,...o})).sort((a,b)=>b.v-a.v).slice(0,8)}
  function recentExerciseStats(){const start=add(day(),-20),by=new Map();st.sets.filter(x=>x.completed&&x.created_at?.slice(0,10)>=start&&+x.weight_kg>0&&+x.reps>0).forEach(x=>{if(!by.has(x.exercise_key))by.set(x.exercise_key,[]);by.get(x.exercise_key).push(x)});return[...by.entries()].map(([key,rows])=>{rows.sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at)));const half=Math.max(1,Math.floor(rows.length/2)),a=rows.slice(0,half).map(e1rm),b=rows.slice(half).map(e1rm),trend=a.length&&b.length?(Math.max(...b)-Math.max(...a))/Math.max(...a)*100:null;return{key,nameVi:D.exerciseLibrary?.[key]?.nameVi||key,trend,last:rows.at(-1),n:rows.length}}).sort((a,b)=>(a.trend??0)-(b.trend??0))}
  function warmupFor(key){const rows=st.sets.filter(x=>x.exercise_key===key&&x.completed&&+x.weight_kg>0).sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))),w=+rows.at(-1)?.weight_kg||0;if(!w)return[];const round=n=>Math.max(.5,Math.round(n*2)/2);return[{label:'Khởi động 1',weight:round(w*.4),reps:'10–12'},{label:'Khởi động 2',weight:round(w*.6),reps:'6–8'},{label:'Khởi động 3',weight:round(w*.8),reps:'3–5'},{label:'Working',weight:w,reps:'theo plan'}]}
  function muscleVolume(){const start=add(day(),-6),map=new Map();st.sets.filter(x=>x.completed&&x.created_at?.slice(0,10)>=start).forEach(s=>{const ex=D.exerciseLibrary?.[s.exercise_key],raw=String(ex?.primary||'Khác').split('•')[0].trim()||'Khác';map.set(raw,(map.get(raw)||0)+1)});return[...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10)}
  function consistency28(){return Array.from({length:28},(_,i)=>{const k=add(day(),i-27),todo=st.todos.filter(x=>x.todo_date===k),pct=todo.length?todo.filter(x=>x.completed).length/todo.length:0,trained=st.sessions.some(x=>x.workout_date===k&&['complete','partial_counted'].includes(normStatus(x.status)));return{k,pct,trained}})}
  function measurementTrend(){const rows=[...st.measurements].sort((a,b)=>String(a.measured_at).localeCompare(String(b.measured_at))).slice(-14),w=rows.map(x=>+x.weight_kg).filter(Number.isFinite),wa=rows.map(x=>+x.waist_cm).filter(Number.isFinite);return{rows,weight:w,waist:wa,weightAvg7:avg(w.slice(-7)),waistAvg7:avg(wa.slice(-7))}}
  function spark(values,w=300,h=70){if(values.length<2)return'<div class="v7-empty">Chưa đủ dữ liệu để vẽ trend.</div>';const mn=Math.min(...values),mx=Math.max(...values),span=mx-mn||1,pts=values.map((v,i)=>`${(i/(values.length-1))*w},${h-8-((v-mn)/span)*(h-16)}`).join(' ');return`<svg class="v7-spark" viewBox="0 0 ${w} ${h}" role="img"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/></svg>`}

  function dataAudit(){const issues=[];const c=checkin();if(!c.sleepHours)issues.push('Thiếu giờ ngủ hôm nay');if(!stress())issues.push('Chưa log stress');if(!steps())issues.push('Chưa log bước chân');if(!st.measurements.some(x=>x.measured_at>=add(day(),-7)))issues.push('Chưa có cân/vòng eo trong 7 ngày');const recent=st.sets.filter(x=>x.created_at?.slice(0,10)>=add(day(),-7)&&x.completed),missingRir=recent.filter(x=>x.rir==null).length;if(missingRir)issues.push(`${missingRir} set gần đây thiếu RIR`);if(!mealsToday().some(x=>+x.payload?.protein>0))issues.push('Chưa có meal log có protein hôm nay');return issues}
  function decisions(){const out=[],sl=sleepStats(),caf=caffeineStatus(),n=nutrition(),p=plan(),pl=recentExerciseStats().filter(x=>x.n>=4&&x.trend!=null&&x.trend<1).slice(0,3),mt=measurementTrend();if(sl.debt>=3)out.push(['sleep','Ưu tiên ngủ','Sleep debt 7 ngày đang cao; không nên đổi calories hay volume chỉ vì 1–2 buổi yếu.']);if(caf.after)out.push(['caffeine','Dừng caffeine hôm nay','Liều gần nhất sau giờ cutoff; ưu tiên nước/đồ uống không caffeine.']);if(new Date().getHours()>=20&&n.protein<profileTarget('proteinTarget',115)-30)out.push(['protein','Bữa tối cần protein rõ ràng',`Còn khoảng ${Math.max(0,profileTarget('proteinTarget',115)-n.protein)}g protein so với target.`]);if(p.type==='strength'&&recoveryScore()<55)out.push(['training','Giảm volume phụ','Recovery score thấp; giữ compound chính nhưng giảm accessory và tránh failure.']);if(pl.length)out.push(['plateau','Có dấu hiệu plateau',`${pl.map(x=>x.nameVi).join(', ')} chưa có tín hiệu tăng rõ trong dữ liệu gần đây.`]);if(mt.weight.length>=2&&mt.waist.length>=2){const dw=mt.weight.at(-1)-mt.weight[0],dwa=mt.waist.at(-1)-mt.waist[0];if(Math.abs(dw)<=.7&&dwa<0)out.push(['recomp','Recomp đang đúng hướng','Cân khá ổn định trong khi vòng eo giảm; chưa cần siết calories thêm.']);if(dw>.8&&dwa>.8)out.push(['trend','Theo dõi calories 7–14 ngày','Cân và eo cùng tăng; cần thêm dữ liệu trước khi đổi target.'])}if(!out.length)out.push(['ok','Chưa cần thay đổi lớn','Dữ liệu hiện chưa tạo tín hiệu đủ mạnh để chỉnh kế hoạch.']);return out}

  function ensureDom(){
    document.documentElement.classList.add('pt-v7');document.title='MyGym Personal PT v7';const eb=document.querySelector('.pt-header .eyebrow');if(eb)eb.textContent='PERSONAL FITNESS OS • V7';
    if($('panel-today')&&!$('v7-today')){const e=document.createElement('section');e.id='v7-today';const anchor=$('v6-evening')||$('v6-today')||$('today-hero');anchor?.insertAdjacentElement('afterend',e)}
    if($('panel-workout')&&!$('v7-workout')){const e=document.createElement('section');e.id='v7-workout';($('v6-workout')||$('workout-list'))?.insertAdjacentElement('afterend',e)}
    if($('panel-nutrition')&&!$('v7-nutrition')){const e=document.createElement('section');e.id='v7-nutrition';($('v6-nutrition')||$('nutrition-adaptation'))?.insertAdjacentElement('afterend',e)}
    if($('panel-progress')&&!$('v7-progress')){const e=document.createElement('section');e.id='v7-progress';($('v6-progress')||$('progress-summary'))?.insertAdjacentElement('afterend',e)}
    if($('panel-coach')&&!$('v7-coach')){const e=document.createElement('section');e.id='v7-coach';($('v6-coach')||$('coach-analysis'))?.insertAdjacentElement('afterend',e)}
  }

  function renderToday(){const e=$('v7-today');if(!e)return;const d=dailyScore(),sl=sleepStats(),hy=hydrationPace(),caf=caffeineStatus(),sm=sorenessMap(),c=checkin();e.innerHTML=`
    <div class="section-head"><div><p class="eyebrow">DAILY OPERATING SYSTEM</p><h2>Quick log & trạng thái trong ngày</h2></div><span class="pill ${d.total>=75?'good':d.total>=55?'warn':'danger'}">Score ${d.total}</span></div>
    <div class="v7-score-grid"><article class="v7-score"><b>${d.r}</b><span>Recovery</span></article><article class="v7-score"><b>${d.n}</b><span>Nutrition</span></article><article class="v7-score"><b>${d.a}</b><span>Activity</span></article><article class="v7-score"><b>${d.t}</b><span>Training</span></article></div>
    <div class="v7-grid">
      <article class="v7-card v7-span-7"><div class="v7-head"><div><p class="eyebrow">QUICK LOGGER</p><h3>Ghi trong 1 chạm</h3></div></div><div class="v7-quick"><button data-v7-water="250">+250 ml</button><button data-v7-water="500">+500 ml</button><button data-v7-steps="1000">+1k bước</button><button data-v7-steps="2000">+2k bước</button><button data-v7-caf="60">Cà phê ~60mg</button><button data-v7-caf="100">Cà phê ~100mg</button></div><div class="v7-inline-form"><label>Stress 1–5<select id="v7-stress">${[1,2,3,4,5].map(x=>`<option value="${x}" ${stress()===x?'selected':''}>${x}</option>`).join('')}</select></label><button id="v7-save-stress" class="mini-btn">Lưu stress</button></div></article>
      <article class="v7-card v7-span-5"><p class="eyebrow">PACE</p><h3>Đang ở đâu so với target?</h3><div class="v7-mini-list"><div><span>Nước</span><b>${(water()/1000).toFixed(1)} / ${(hy.target/1000).toFixed(1)}L</b><small>${hy.delta>=0?'đang đúng/nhanh hơn nhịp':'chậm hơn nhịp khoảng '+Math.abs(hy.delta)+' ml'}</small></div><div><span>Bước</span><b>${steps().toLocaleString('vi-VN')} / ${profileTarget('stepsTarget',8000).toLocaleString('vi-VN')}</b></div><div><span>Sleep debt 7 ngày</span><b>${sl.days?sl.debt.toFixed(1)+'h':'—'}</b><small>${sl.mean?`TB ${sl.mean.toFixed(1)}h`:''}</small></div><div><span>Caffeine</span><b>${caf.mg} mg</b><small>${esc(caf.label)}</small></div></div></article>
    </div>
    <div class="section-head"><div><p class="eyebrow">BODY CHECK</p><h2>Soreness theo vùng</h2></div><button id="v7-save-soreness" class="mini-btn">Lưu</button></div><div id="v7-soreness-grid" class="v7-soreness">${muscleParts.map(([k,n])=>`<label><span>${n}</span><select data-sore-part="${k}">${[0,1,2,3,4].map(v=>`<option value="${v}" ${(+sm[k]||0)===v?'selected':''}>${v}</option>`).join('')}</select><small>${(+sm[k]||0)>=4?'đau bất thường':(+sm[k]||0)>=3?'mỏi nhiều':(+sm[k]||0)>=1?'mỏi nhẹ/vừa':'ổn'}</small></label>`).join('')}</div>
    <div class="v7-context-note">Ngủ hôm nay: <b>${c.sleepHours||'—'}h</b> • Energy <b>${c.energy||'—'}/5</b> • Stress <b>${stress()||'—'}/5</b>. V7 dùng các tín hiệu này để đưa cảnh báo, không tự chẩn đoán chấn thương.</div>`;
    e.querySelectorAll('[data-v7-water]').forEach(b=>b.onclick=()=>addWater(+b.dataset.v7Water));e.querySelectorAll('[data-v7-steps]').forEach(b=>b.onclick=()=>addSteps(+b.dataset.v7Steps));e.querySelectorAll('[data-v7-caf]').forEach(b=>b.onclick=()=>addCaffeine(+b.dataset.v7Caf,b.textContent.trim()));$('v7-save-stress').onclick=()=>saveStress($('v7-stress').value);$('v7-save-soreness').onclick=saveSoreness}

  function renderWorkout(){const e=$('v7-workout');if(!e)return;const p=plan(),w=p.workoutId&&D.workouts?.[p.workoutId],prs=prBoard(),plat=recentExerciseStats().filter(x=>x.n>=4&&x.trend!=null&&x.trend<1).slice(0,5),vol=muscleVolume();const firstKey=w?.exercises?.[0]?.[0],warm=firstKey?warmupFor(firstKey):[];e.innerHTML=`
    <div class="section-head"><div><p class="eyebrow">PERFORMANCE LAB</p><h2>Warm-up • PR • plateau • volume</h2></div></div>
    <div class="v7-grid">
      <article class="v7-card v7-span-5"><p class="eyebrow">WARM-UP BUILDER</p><h3>${w?esc(D.exerciseLibrary?.[firstKey]?.nameVi||firstKey):'Không có strength hôm nay'}</h3>${warm.length?`<div class="v7-warmup">${warm.map(x=>`<div><span>${x.label}</span><b>${x.weight} kg</b><small>${x.reps} reps</small></div>`).join('')}</div><p class="v7-note">Đây là warm-up tương đối theo mức working gần nhất, không phải target bắt buộc.</p>`:'<p class="v7-empty">Cần ít nhất một set đã log có mức tạ để tính warm-up.</p>'}</article>
      <article class="v7-card v7-span-7"><p class="eyebrow">VOLUME 7 NGÀY</p><h3>Set theo nhóm cơ chính</h3><div class="v7-bars">${vol.length?vol.map(([name,n])=>`<div><span>${esc(name)}</span><i><b style="width:${Math.min(100,n/16*100)}%"></b></i><strong>${n}</strong></div>`).join(''):'<p class="v7-empty">Chưa có set gần đây.</p>'}</div></article>
    </div>
    <div class="v7-grid">
      <article class="v7-card v7-span-7"><p class="eyebrow">PR BOARD</p><h3>Best estimated 1RM</h3><div class="v7-table">${prs.length?prs.map((x,i)=>`<div><b>#${i+1}</b><span><strong>${esc(x.nameVi)}</strong><small>${x.row.weight_kg}kg × ${x.row.reps} reps</small></span><em>${x.v.toFixed(1)} kg e1RM</em></div>`).join(''):'<p class="v7-empty">Chưa đủ set để tạo PR board.</p>'}</div></article>
      <article class="v7-card v7-span-5"><p class="eyebrow">PLATEAU RADAR</p><h3>Bài cần để mắt</h3>${plat.length?`<div class="v7-mini-list">${plat.map(x=>`<div><span>${esc(x.nameVi)}</span><b>${x.trend==null?'—':x.trend.toFixed(1)+'%'}</b><small>${x.n} set gần đây</small></div>`).join('')}</div>`:'<p class="v7-empty">Chưa thấy plateau đủ rõ.</p>'}</article>
    </div>`}

  function renderNutrition(){const e=$('v7-nutrition');if(!e)return;const n=nutrition(),ct=profileTarget('calorieTarget',2050),pt=profileTarget('proteinTarget',115),dist=proteinDistribution(),office=officeBreakfasts(),late=lateDinnerOptions(),remK=Math.max(0,ct-n.kcal),remP=Math.max(0,pt-n.protein);e.innerHTML=`
    <div class="section-head"><div><p class="eyebrow">NUTRITION CONTROL</p><h2>Macro còn lại & phân bố protein</h2></div><span class="pill ${n.protein>=pt?'good':n.protein>=pt*.65?'warn':''}">${n.protein}/${pt}g protein</span></div>
    <div class="v7-score-grid"><article class="v7-score"><b>${n.kcal}</b><span>kcal đã log</span></article><article class="v7-score"><b>${remK}</b><span>kcal còn lại</span></article><article class="v7-score"><b>${n.protein}g</b><span>protein đã log</span></article><article class="v7-score"><b>${remP}g</b><span>protein còn lại</span></article></div>
    <div class="v7-grid"><article class="v7-card v7-span-6"><p class="eyebrow">PROTEIN DISTRIBUTION</p><h3>Mục tiêu 25–35g ở các bữa chính</h3><div class="v7-protein-dist">${[['breakfast','Sáng'],['lunch','Trưa'],['snack','Xế'],['preworkout','Pre'],['dinner','Tối']].map(([k,l])=>`<div><span>${l}</span><i><b style="width:${Math.min(100,(dist[k]||0)/35*100)}%"></b></i><strong>${Math.round(dist[k]||0)}g</strong></div>`).join('')}</div></article><article class="v7-card v7-span-6"><p class="eyebrow">LATE DINNER MODE</p><h3>Món nhanh, không quá nặng</h3><div class="v7-food-list">${late.map(x=>`<div><span><strong>${esc(x.name)}</strong><small>${x.time}' • ${x.kcal} kcal • P ${x.protein}g</small></span></div>`).join('')}</div></article></div>
    <div class="section-head"><div><p class="eyebrow">OFFICE BREAKFAST</p><h2>Mua trên đường • gọn • ít mùi</h2></div></div><div class="v7-office-food">${office.length?office.map(x=>`<article><strong>${esc(x.name)}</strong><small>${x.kcal} kcal • P ${x.protein}g • ${esc((x.tags||[]).slice(0,3).join(' · '))}</small></article>`).join(''):'<p class="v7-empty">Catalog chưa có món office-friendly.</p>'}</div>`}

  function renderProgress(){const e=$('v7-progress');if(!e)return;const mt=measurementTrend(),c28=consistency28(),audit=dataAudit();e.innerHTML=`
    <div class="section-head"><div><p class="eyebrow">TREND & CONSISTENCY</p><h2>Nhìn xu hướng thay vì một ngày</h2></div></div>
    <div class="v7-grid"><article class="v7-card v7-span-6"><p class="eyebrow">CÂN NẶNG</p><h3>${mt.weightAvg7?mt.weightAvg7.toFixed(1)+' kg TB gần đây':'Chưa đủ dữ liệu'}</h3>${spark(mt.weight)}</article><article class="v7-card v7-span-6"><p class="eyebrow">VÒNG EO</p><h3>${mt.waistAvg7?mt.waistAvg7.toFixed(1)+' cm TB gần đây':'Chưa đủ dữ liệu'}</h3>${spark(mt.waist)}</article></div>
    <div class="v7-grid"><article class="v7-card v7-span-7"><p class="eyebrow">28-DAY CONSISTENCY</p><h3>Không cần hoàn hảo, cần đều</h3><div class="v7-heat">${c28.map(x=>`<span title="${x.k} • ${Math.round(x.pct*100)}%" class="${x.trained?'trained':x.pct>=.8?'high':x.pct>=.4?'mid':''}"></span>`).join('')}</div><div class="v7-heat-label"><span>${fmt(add(day(),-27))}</span><span>Hôm nay</span></div></article><article class="v7-card v7-span-5"><p class="eyebrow">DATA QUALITY</p><h3>${audit.length?`${audit.length} điểm cần bổ sung`:'Dữ liệu khá sạch'}</h3>${audit.length?`<ul class="v7-audit">${audit.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p class="v7-empty">Các tín hiệu chính đang đủ để phân tích.</p>'}</article></div>`}

  function exportBackup(){const data={schema:'mygym-manual-backup-v1',exportedAt:nowIso(),source:S.sourceOfTruth||'Tu4nla/MyGym',profile:D.profile||{},equipment:S.equipment?.confirmedFromCurrentProfile||[],todos:st.todos,entries:st.entries,sessions:st.sessions,sets:st.sets,measurements:st.measurements,analyses:st.analyses,v7:{foodFavorites:L.get('mygym.v6.foodFavorites',[]),cookMinutes:L.get('mygym.v6.cookMinutes',20)}};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mygym-backup-${day()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Đã export backup JSON')}
  async function copyDeepReview(){const d=dailyScore(),sl=sleepStats(),mt=measurementTrend(),packet={task:'Hãy phân tích dữ liệu MyGym này như PT cá nhân. Ưu tiên thay đổi nhỏ, có lý do. Nếu cần update data, nói rõ record nào cần ghi.',date:day(),profile:D.profile,plan:plan(),scores:d,sleep:sl,nutrition:nutrition(),waterMl:water(),steps:steps(),caffeineMg:caffeine(),stress:stress(),soreness:sorenessMap(),recentSessions:st.sessions.filter(x=>x.workout_date>=add(day(),-14)),recentSets:st.sets.filter(x=>x.created_at?.slice(0,10)>=add(day(),-14)).slice(-160),measurements:st.measurements.slice(-12),decisions:decisions().map(x=>({type:x[0],title:x[1],detail:x[2]}))};await navigator.clipboard.writeText(JSON.stringify(packet,null,2));toast('Đã copy Deep Review packet')}
  function renderCoach(){const e=$('v7-coach');if(!e)return;const ds=decisions(),audit=dataAudit();e.innerHTML=`
    <div class="section-head"><div><p class="eyebrow">DECISION CENTER</p><h2>Hệ thống nên làm gì tiếp theo?</h2></div><span class="pill">${ds.length} signal</span></div><div class="v7-decisions">${ds.map(([type,title,detail])=>`<article class="v7-decision ${type}"><b>${esc(title)}</b><p>${esc(detail)}</p></article>`).join('')}</div>
    <div class="v7-grid"><article class="v7-card v7-span-7"><p class="eyebrow">MANUAL DEEP REVIEW</p><h3>1 nút copy packet sâu cho ChatGPT</h3><p>Gói này gồm recovery, nutrition, caffeine, soreness, 14 ngày workout/set, measurements và signal hiện tại. Không gọi API.</p><button id="v7-copy-review" class="primary">Copy Deep Review</button></article><article class="v7-card v7-span-5"><p class="eyebrow">DATA & BACKUP</p><h3>Xuất toàn bộ dữ liệu cá nhân</h3><p>${audit.length?`Hiện có ${audit.length} điểm thiếu dữ liệu nhỏ.`:'Dữ liệu chính đang đủ.'}</p><button id="v7-export" class="secondary">Export JSON backup</button></article></div>`;$('v7-copy-review').onclick=copyDeepReview;$('v7-export').onclick=exportBackup}

  function renderAll(){renderToday();renderWorkout();renderNutrition();renderProgress();renderCoach()}
  function refresh(){const h=rawHash();if(h===st.hash)return;read();renderAll()}
  async function init(){ensureDom();read();await cloudSession();renderAll();window.addEventListener('storage',e=>{if(e.key?.startsWith('mygym.v3.')){read();renderAll()}});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){read();renderAll()}});setInterval(refresh,1800)}
  init();
})();