import json
from pathlib import Path

ROOT=Path('android-learning/data')
CANON=['objectives','prerequisites','terminology','mechanism','purpose','problem','when-to-use','when-not-to-use','requirement','analysis','minimal-code','upzi-case','alternatives','tradeoffs','edge-cases','mistakes','interview-basic','interview-deep','experience-answer','practice','scenario','checklist','summary','quiz-guide']
def p(*xs): return [{'type':'paragraph','content':x} for x in xs]
def code(label,s): return {'type':'code','language':'kotlin','label':label,'content':s}
S=[]
def sec(i,t,*xs): S.append({'id':i,'title':t,'blocks':p(*xs)})
sec('objectives','1. Mục tiêu bài học','Hiểu Single Source of Truth (SSOT) là quy tắc về quyền sở hữu và thẩm quyền dữ liệu, không đơn giản là chỉ có một biến hoặc một database.','Phân biệt source of truth, cache, replica, projection, derived state, event stream và authoritative server.','Thiết kế luồng local-first/offline-first với Room, Flow, repository, network refresh, socket patch và optimistic write mà không tạo hai nguồn state cạnh tranh.','Xác định consistency model, freshness policy, conflict policy, lifecycle, process death, account isolation và test strategy cho sản phẩm Android thực tế.')
sec('prerequisites','2. Kiến thức nền','Cần nắm F03 MVI/UDF, F05 Repository Pattern, F06 Use Case và F07 Data Mapping.','Cần hiểu Flow, StateFlow, Room transaction, Paging, optimistic update, idempotency, outbox, process death, WorkManager và coroutine cancellation.','SSOT không tự sinh ra từ một thư viện. Nó là quyết định kiến trúc về ai được quyền công bố state hiện tại và các nguồn khác được hợp nhất thế nào.')
sec('terminology','3. Định nghĩa và chú giải thuật ngữ','Source of truth là representation được chọn làm trạng thái chuẩn mà consumer quan sát tại một boundary cụ thể.','Authoritative source là nơi có thẩm quyền cuối cùng theo nghiệp vụ, thường là server; local SSOT có thể là nguồn chuẩn cho UI trong process dù vẫn phải đồng bộ với server.','Cache là bản sao tối ưu latency; replica là bản sao có cơ chế đồng bộ; projection là view được suy ra từ dữ liệu gốc; derived state là dữ liệu tính toán từ state khác.','Freshness mô tả độ mới; consistency mô tả quan hệ giữa các bản sao; convergence là khả năng cuối cùng hội tụ về cùng trạng thái.','Write-through ghi nguồn chính rồi cache; write-back ghi local trước rồi đồng bộ; stale-while-revalidate trả dữ liệu cũ trong lúc refresh.','Outbox là bảng durable chứa mutation chờ gửi; tombstone biểu diễn xóa để tránh bản ghi sống lại khi đồng bộ.')
sec('mechanism','4. Cơ chế hoạt động bên trong','UI quan sát một stream duy nhất từ repository hoặc ViewModel. Repository hợp nhất network, database và socket nhưng chỉ phát model đã canonicalize từ source được chọn.','Mô hình phổ biến offline-first là network response được map và ghi Room trong transaction; UI chỉ collect Room Flow. Network không phát song song một list khác vào UI.','Socket event không nên trực tiếp sửa state UI nếu Room là SSOT. Event được validate, deduplicate và apply thành patch/transaction rồi Room phát snapshot mới.','Optimistic write tạo local pending record với stable clientId, cập nhật UI ngay, sau đó outbox hoặc transport gửi lên server. Ack reconcile serverId và delivery state trong cùng canonical record.','Refresh cần single-flight hoặc request generation để response cũ không ghi đè dữ liệu mới. Timestamp đơn thuần không luôn đủ vì clock có thể lệch.','Derived UI state nên được tính từ canonical data và input UI, không persist lại nếu có thể tái tạo rẻ và deterministic.','Khi local database không phù hợp, in-memory store scoped theo navigation graph vẫn có thể là SSOT cho feature; scope và restoration policy phải rõ.')
sec('purpose','5. Mục đích của kỹ thuật','SSOT giảm trạng thái mâu thuẫn giữa API response, cache, socket và UI local state.','Nó làm rõ ownership, giúp debug: mọi thay đổi state đi qua một đường canonical thay vì nhiều callback.','Nó hỗ trợ offline, process restart, multiple collectors và navigation quay lại mà vẫn có state nhất quán.','Mục tiêu không phải ép mọi dữ liệu vào Room mà chọn một nguồn chuẩn phù hợp với lifetime và requirement.')
sec('problem','6. Vấn đề kỹ thuật được giải quyết','Nếu ViewModel vừa giữ list từ API vừa collect Room, hai list có thể khác nhau và cập nhật theo thứ tự không xác định.','Nếu socket event sửa StateFlow trong khi refresh thay cả list, event mới có thể bị snapshot cũ ghi đè.','Nếu optimistic state chỉ tồn tại trong UI, rotation hoặc process death làm mất pending action dù server có thể đã nhận request.','SSOT giải quyết bằng ownership, canonical identity, merge policy và durable transition rõ ràng.')
sec('when-to-use','7. Dấu hiệu cần dùng','Dùng khi cùng dữ liệu đến từ nhiều nguồn: REST, Room, socket, notification, deep link hoặc background worker.','Dùng khi cần offline-first, stale data, optimistic update, retry sau process death hoặc nhiều màn hình cùng quan sát một domain object.','Dùng khi bug thường xuất hiện do state cũ ghi đè state mới, duplicate record hoặc UI khác nhau giữa các entry point.','Dùng khi product yêu cầu trạng thái phải sống lâu hơn Activity/ViewModel.')
sec('when-not-to-use','8. Khi không nên dùng','Không cần database SSOT cho dữ liệu tạm thời như dialog open, scroll offset ngắn hạn hoặc text focus nếu lifetime chỉ thuộc UI.','Không persist derived UI text, animation progress hoặc formatted date nếu có thể tính lại từ canonical state.','Không chọn server response trực tiếp làm UI SSOT nếu cần offline, multi-screen consistency hoặc socket merge phức tạp.','Không tạo global store cho toàn app khi feature-scoped store hoặc repository boundary đủ dùng.','Không gọi một MutableStateFlow là SSOT nếu nhiều nơi vẫn có quyền mutate nó ngoài owner.')
sec('requirement','9. Yêu cầu sản phẩm cụ thể','Chat phải hiển thị pending message ngay, giữ qua process death, reconcile clientId/serverId, không duplicate khi ack/socket/REST cùng trả về và không rollback delivered/read state bởi snapshot cũ.','Feed phải cho phép stale-while-revalidate, Paging không nhảy position vô lý, reaction optimistic có rollback hoặc reconcile và refresh cũ không ghi đè mutation mới.','Opportunity detail và list phải phản ánh cùng saved/applied state sau khi user thao tác ở bất kỳ màn hình nào.','Acceptance criteria phải nêu source chuẩn cho UI, authoritative source, freshness SLA, conflict policy, deletion policy, retry/idempotency và account partition.','Observability phải đo cache age, refresh result, conflict, duplicate suppression, outbox backlog và convergence latency mà không log PII.')
sec('analysis','10. Phân tích dependency, error policy, lifecycle và resource limits','Dependency: repository sở hữu orchestration; DAO/remote/socket là adapter. UI chỉ biết Flow/domain model và command use case.','Error policy: read có thể trả stale data cùng trạng thái refresh error; write failure cần phân biệt retryable, conflict, rejected và permanent failure.','Lifecycle: UI collector lifecycle-aware; repository/store không giữ Activity. Durable state nằm ở database/outbox; transient state nằm ở ViewModel hoặc SavedStateHandle nhỏ.','Resource limits: Room table cần eviction/retention, index và transaction batch; in-memory store cần bounded history; outbox cần backoff và dead-letter policy.','Consistency: strong consistency hiếm ở mobile offline. Thường dùng eventual consistency kèm monotonic merge, version hoặc server sequence.','Concurrency: serialize mutation theo entity khi cần, use compare-and-set/version, single-flight refresh và guard account/session generation.','Deletion: dùng tombstone hoặc server version để record đã xóa không sống lại từ page/cache cũ.','Security: database và cache phải partition theo account; logout xóa hoặc rotate key đúng policy; không phát dữ liệu user cũ vào session mới.','Testing: deterministic fake clock/server version, out-of-order response, duplicate event, process restart, account switch, refresh race và migration test.')
S.append({'id':'minimal-code','title':'11. Ví dụ code tối giản','blocks':p('Ví dụ Room làm SSOT: UI chỉ quan sát DAO; refresh chỉ cập nhật database.')+[code('Repository với Room SSOT','''class FeedRepositoryImpl(
 private val api:FeedApi,
 private val dao:PostDao,
 private val db:AppDatabase
):FeedRepository{
 override fun observeFeed():Flow<List<Post>> = dao.observeAll().map { rows -> rows.map(PostEntity::toDomain) }
 override suspend fun refresh(){
   val dto=api.getFeed()
   val entities=dto.items.mapNotNull { it.toEntityOrNull() }
   db.withTransaction {
     dao.replaceSnapshot(entities, serverVersion=dto.version)
   }
 }
}'''),code('Optimistic chat qua outbox','''suspend fun sendMessage(conversationId:String,text:String):String = db.withTransaction {
 val clientId=ids.next()
 messageDao.insert(MessageEntity.pending(clientId,conversationId,text,clock.now()))
 outboxDao.insert(OutboxEntity.sendMessage(clientId))
 clientId
}
// Worker/socket sender đọc outbox; ack cập nhật cùng record theo clientId.''')]})
sec('upzi-case','12. Ví dụ thực tế Upzi','confirmed: Upzi dùng Compose, StateFlow, Paging, Socket.IO, optimistic clientId, ack timeout, delivered/read/typing, WorkManager và deep link. Đây là bối cảnh có nhiều nguồn state cạnh tranh.','inferred: chat và feed hiện chắc chắn có ownership/state flow thực tế, nhưng chưa xác nhận Room có phải SSOT ở từng feature hoặc socket event có đi qua persistence hay không.','proposed: chọn Room canonical message table làm UI SSOT; socket/REST/ack đều apply transaction theo clientId/serverId/version; UI không giữ list song song.','proposed: Feed dùng PagingSource/RemoteMediator hoặc repository equivalent với database làm SSOT, stale-while-revalidate và reaction mutation overlay có version.','needs-confirmation: cần kiểm tra production code về database schema, socket merge, Paging source, optimistic persistence, account cleanup và outbox trước khi mô tả như kiến trúc đã triển khai.','needs-confirmation: cần xác nhận Opportunity saved/applied state đang được đồng bộ giữa list/detail bằng repository hay cập nhật cục bộ từng ViewModel.')
sec('alternatives','13. Phương án thay thế','Network-only phù hợp dữ liệu luôn online, không cần shared state và chấp nhận reload.','In-memory store phù hợp session ngắn, dữ liệu nhỏ và không cần survive process death.','Room SSOT phù hợp offline, shared observation và durable state nhưng tăng schema/migration cost.','DataStore phù hợp key-value hoặc preference nhỏ, không phù hợp relational feed/chat.','Server-driven UI có thể làm server authoritative hơn nhưng client vẫn cần state ownership cho lifecycle và offline.','Event sourcing lưu event làm source chính nhưng phức tạp hơn nhiều và không cần cho đa số app mobile.')
sec('tradeoffs','14. Lý do lựa chọn và trade-off','Database SSOT tăng consistency và durability nhưng thêm I/O, mapper, migration và latency ghi.','Local-first tăng responsiveness/offline nhưng cần conflict resolution, outbox và reconciliation.','Server-first đơn giản hơn nhưng UX yếu khi mạng chậm và khó giữ multi-screen consistency.','Một canonical model giảm duplicate state nhưng có thể không tối ưu cho mọi query; projection/materialized view có thể cần thiết.','Strict ordering theo server sequence chính xác hơn timestamp nhưng phụ thuộc backend contract.','Global SSOT dễ chia sẻ nhưng coupling lớn; feature/entity-scoped ownership thường cân bằng hơn.')
sec('edge-cases','15. Edge cases','REST snapshot cũ đến sau socket event mới và ghi đè trạng thái delivered/read.','Ack đến hai lần hoặc socket reconnect replay event.','Message pending đã persist nhưng app chết trước enqueue; worker phải tiếp tục từ outbox.','Server nhận mutation nhưng client timeout rồi retry; cần idempotency key.','User logout trong lúc refresh/write đang chạy; result cũ không được ghi vào account mới.','Pagination page cũ chứa record đã xóa; tombstone/version phải ngăn resurrection.','Clock thiết bị sai khiến freshness TTL hoặc last-write-wins sai.','Database migration làm mất pending state hoặc server version.','Multiple process hoặc widget đọc cùng database; transaction và invalidation phải được xét.','Derived Flow kết hợp nhiều bảng có intermediate inconsistent snapshot nếu update không transaction.','Storage full, database locked hoặc corruption; cần degraded mode và recovery policy.')
sec('mistakes','16. Sai lầm thường gặp','Gọi Room là SSOT nhưng UI vẫn hiển thị API response trực tiếp sau refresh.','Có nhiều MutableStateFlow cùng đại diện một entity và đều được mutate.','Dùng last-write-wins theo device timestamp cho dữ liệu nghiệp vụ quan trọng.','Không lưu version, sequence hoặc clientId nên không reconcile được event.','Xóa hard delete local rồi record sống lại từ cache/page cũ.','Persist mọi UI state vào database, làm schema ô nhiễm và migration nặng.','Global singleton store giữ dữ liệu vô hạn hoặc dữ liệu account cũ.','Nuốt refresh error và hiển thị stale data như fresh không có indicator.','Dùng mutex trong process thay cho idempotency server.','Không test process death, duplicate event và out-of-order response.')
sec('interview-basic','17. Câu hỏi phỏng vấn cơ bản','Single Source of Truth là gì?','SSOT có đồng nghĩa database không?','Server authoritative khác local SSOT thế nào?','Tại sao UI không nên vừa dùng API response vừa collect Room?','Derived state có phải source of truth không?','Khi nào dùng stale-while-revalidate?','Outbox giải quyết vấn đề gì?','Tombstone dùng để làm gì?')
sec('interview-deep','18. Câu hỏi xoáy sâu và câu hỏi bẫy','Socket event mới đến trước REST snapshot cũ: thiết kế merge thế nào?','Room là UI SSOT nhưng server từ chối optimistic mutation; rollback hay mark failed?','Làm sao bảo đảm message không duplicate khi có clientId và serverId?','Có thể có nhiều SSOT không? Trả lời theo boundary và scope.','Nếu UI cần state nhanh hơn database write thì có được cập nhật StateFlow trước không? Phân tích invariant và recovery.','RemoteMediator có tự động biến Room thành SSOT không?','Last-write-wins có an toàn không khi clock lệch?','Process chết giữa DB write và network send được xử lý thế nào?','Account switch khi Flow cũ còn emit: chặn bằng cơ chế nào?')
sec('experience-answer','19. Mẫu trả lời gắn với kinh nghiệm','Tôi coi SSOT là quyền sở hữu state theo feature, không chỉ là một database. Với chat, tôi ưu tiên một canonical message model có clientId để optimistic update và reconcile ack.','Trong Upzi, các chi tiết confirmed là Compose, StateFlow, Paging và Socket.IO với optimistic clientId/ack. Tôi không khẳng định Room đã là SSOT nếu chưa kiểm tra code production.','Phương án tôi đề xuất là mọi REST/socket/ack ghi qua một repository vào canonical storage, UI chỉ observe một stream; mutation durable đi qua outbox và idempotency.','Khi phỏng vấn, tôi nêu rõ phần đã làm, phần suy luận và trade-off về latency, migration, conflict thay vì nói SSOT như khẩu hiệu.')
sec('practice','20. Bài tập thực hành','Thiết kế Room schema cho message gồm clientId, serverId, status, serverVersion và pending operation.','Viết repository observe Room và refresh network không phát list trực tiếp.','Viết test response cũ về sau socket event mới.','Thêm outbox và worker retry idempotent cho send message.','Thiết kế stale-while-revalidate cho Opportunity detail.','Đo số query, transaction duration và allocation khi refresh 1.000 item.')
sec('scenario','21. Bài tập tình huống','Feed có API, Room, Paging và socket reaction count. Hãy chọn SSOT, version policy và transaction boundary.','Chat gửi message offline, app bị kill, mở lại rồi socket reconnect replay ack. Hãy mô tả state transition đầy đủ.','User save job ở detail rồi quay lại list. Hai màn hình đang có hai ViewModel khác nhau; thiết kế để trạng thái thống nhất.','Server không cung cấp version và timestamp đáng tin. Hãy đề xuất contract backend tối thiểu hoặc chiến lược client hạn chế rủi ro.','Logout trong lúc outbox còn message: quyết định xóa, giữ hay block theo privacy/product policy.')
sec('checklist','22. Checklist tự đánh giá','Tôi xác định rõ source chuẩn cho UI và authoritative source.','Consumer chỉ quan sát một canonical stream.','Mọi nguồn REST/socket/worker đi qua merge policy chung.','Có stable identity, version/sequence và dedup policy.','Optimistic mutation survive lifecycle cần thiết.','Có idempotency, outbox và retry boundary khi cần.','Có freshness, stale indicator và refresh error policy.','Có account partition, logout cleanup và session guard.','Có tombstone/deletion policy.','Có test race, duplicate, process death và account switch.','Có resource retention, index và observability budget.')
sec('summary','23. Tóm tắt cần nhớ','SSOT là quy tắc ownership và authority theo boundary.','Local database có thể là UI SSOT trong khi server vẫn authoritative.','UI không nên nhận hai representation cạnh tranh cho cùng state.','Socket, REST và optimistic mutation phải hội tụ vào canonical model.','Stable identity, version, idempotency, outbox và tombstone là nền tảng của consistency thực tế.','Chọn scope phù hợp; không biến mọi thứ thành global persistent store.','Test out-of-order, duplicate và process death quan trọng hơn test happy path.')
quiz=[
('SSOT nghĩa chính xác nhất là gì?',['Chỉ có một biến','Một nguồn có quyền công bố state chuẩn tại boundary','Luôn là server','Luôn là Room'],1,'SSOT nói về ownership và thẩm quyền state trong một scope.'),
('Room là UI SSOT thì refresh nên làm gì?',['Trả API list trực tiếp cho UI','Ghi Room rồi UI observe Room','Ghi cả Room và StateFlow list riêng','Bỏ cache'],1,'Một canonical stream tránh hai state cạnh tranh.'),
('Server authoritative và local SSOT có mâu thuẫn không?',['Có','Không, khác scope/thẩm quyền','Chỉ với offline','Chỉ với socket'],1,'Server có thể quyết định nghiệp vụ cuối cùng, local là nguồn chuẩn cho UI.'),
('Outbox hữu ích nhất khi nào?',['Format UI','Mutation cần survive process death','Đổi màu theme','Sort list nhỏ'],1,'Outbox lưu durable pending operation.'),
('Tombstone ngăn lỗi gì?',['ANR','Record đã xóa sống lại','OOM','Token hết hạn'],1,'Tombstone giữ thông tin xóa để merge snapshot cũ.'),
('Socket event nên làm gì khi Room là SSOT?',['Mutate composable trực tiếp','Apply canonical DB transaction','Bỏ qua','Tạo list thứ hai'],1,'Mọi nguồn phải hội tụ vào nguồn chuẩn.'),
('Last-write-wins theo device clock có rủi ro gì?',['Không có','Clock lệch làm chọn sai bản ghi','Chỉ chậm','Chỉ tốn RAM'],1,'Device clock không đáng tin cho ordering quan trọng.'),
('Derived state nên được xử lý thế nào?',['Luôn persist','Tính từ canonical state khi rẻ và deterministic','Làm nguồn chuẩn mới','Đưa vào API'],1,'Persist derived state dễ tạo inconsistency.'),
('Mutex trong process có thay idempotency server không?',['Có','Không','Chỉ Android 14','Chỉ socket'],1,'Process restart hoặc nhiều thiết bị vượt ngoài mutex.'),
('Refresh response cũ về sau event mới cần gì?',['Delay UI','Version/sequence/generation merge guard','Clear DB','Retry vô hạn'],1,'Ordering metadata ngăn stale overwrite.'),
('Nhiều SSOT có thể tồn tại không?',['Không bao giờ','Có theo boundary/scope khác nhau','Chỉ backend','Chỉ debug'],1,'Mỗi feature/entity/scope có thể có nguồn chuẩn riêng.'),
('Stale data cùng refresh error nên xử lý thế nào?',['Xóa dữ liệu','Có thể vẫn hiển thị stale và báo trạng thái refresh','Crash','Giả làm fresh'],1,'Availability và freshness cần được biểu diễn riêng.')]
S.append({'id':'quiz-guide','title':'24. Quiz có giải thích đáp án','blocks':[{'type':'quiz','questions':[{'question':q,'options':o,'answerIndex':a,'explanation':e} for q,o,a,e in quiz]}]})
assert [x['id'] for x in S]==CANON
lesson={'id':'f08','code':'F08','title':'Single Source of Truth','summary':'Thiết kế ownership và consistency giữa Room, network, socket, optimistic state và durable work để UI chỉ quan sát một canonical stream.','estimatedMinutes':360,'sections':S}
(ROOT/'lessons/f').mkdir(parents=True,exist_ok=True)
(ROOT/'lessons/f/f08.json').write_text(json.dumps(lesson,ensure_ascii=False,separators=(',',':')))
cat=json.loads((ROOT/'catalog.json').read_text())
for ch in cat:
  if ch.get('id')=='f':
    for x in ch['lessons']:
      if x['id']=='f08': x['status']='published'; x['estimatedMinutes']=360
(ROOT/'catalog.json').write_text(json.dumps(cat,ensure_ascii=False,indent=2)+'\n')
plan=json.loads((ROOT/'book-plan.json').read_text())
if 'f08' not in plan['completed']: plan['completed'].append('f08')
plan['current']='f09'
(ROOT/'book-plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
idx=json.loads((ROOT/'search-index.json').read_text())
entry={'id':'f08','code':'F08','title':'Single Source of Truth','chapter':'Architecture','path':'data/lessons/f/f08.json','keywords':['single source of truth','SSOT','Room','offline-first','outbox','consistency','socket merge','optimistic update','tombstone']}
if isinstance(idx,list):
 idx=[x for x in idx if x.get('id')!='f08']+[entry]
elif isinstance(idx,dict):
 arr=idx.get('lessons') or idx.get('items') or []
 arr=[x for x in arr if x.get('id')!='f08']+[entry]
 if 'lessons' in idx: idx['lessons']=arr
 else: idx['items']=arr
(ROOT/'search-index.json').write_text(json.dumps(idx,ensure_ascii=False,indent=2)+'\n')
paras=[b['content'] for s in S for b in s['blocks'] if b['type']=='paragraph']
val={'id':'f08','sections':len(S),'uniqueSectionIds':len(set(x['id'] for x in S)),'exactSectionOrder':[x['id'] for x in S]==CANON,'paragraphs':len(paras),'paragraphCharacters':sum(map(len,paras)),'codeBlocks':sum(b['type']=='code' for s in S for b in s['blocks']),'quizQuestions':len(quiz),'quizAnswersValid':all(0<=a<len(o) and e for q,o,a,e in quiz),'truthfulnessLabelsPresent':all(k in ' '.join(paras) for k in ['confirmed:','inferred:','proposed:','needs-confirmation:']),'nextLesson':'f09'}
(ROOT/'validation-f08.json').write_text(json.dumps(val,ensure_ascii=False,indent=2)+'\n')
print(val)
