import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'android-learning'/'data'; sections=[]
def sec(i,id,title,*paras,codes=None):
 b=[{'type':'paragraph','content':p} for p in paras]
 for label,code in (codes or []): b.append({'type':'code','language':'kotlin','label':label,'content':code})
 sections.append({'id':id,'title':f'{i}. {title}','blocks':b})
sec(1,'objectives','Mục tiêu bài học','Hiểu configuration change là việc Android tạo Configuration mới và thường recreate Activity để áp dụng resource qualifier phù hợp, không phải process death. Người học phải giải thích được rotation, locale, font scale, dark mode, density, keyboard, multi-window và foldable tác động thế nào đến Activity, Compose và state.','Mục tiêu thực hành là phân loại state theo ownership, giữ business state trong ViewModel, giữ UI state nhỏ bằng rememberSaveable hoặc SavedStateHandle, tránh android:configChanges như giải pháp mặc định và kiểm thử recreation có chủ đích.')
sec(2,'prerequisites','Kiến thức nền','Cần nắm E01 Activity Lifecycle, ViewModel, SavedStateHandle, remember và rememberSaveable, Navigation Compose, resource qualifier và process lifecycle. Configuration change thường phá hủy instance Activity cũ nhưng process và ViewModelStore có thể còn.','Cần phân biệt state tái tạo từ repository, transient UI state và durable domain data. Không phải mọi thứ đang hiển thị đều nên nhét vào Bundle.')
sec(3,'terminology','Định nghĩa và chú giải thuật ngữ','Configuration là tập thông tin môi trường như orientation, uiMode, locale, fontScale, smallestScreenWidthDp và densityDpi. Resource qualifier như values-land, values-night, sw600dp giúp hệ thống chọn resource phù hợp.','Recreation là tạo lại component để áp dụng configuration mới. ViewModel là API chuẩn cho non-config state. Saved instance state là dữ liệu nhỏ được serialize để khôi phục UI sau recreation và có thể cả process death.','Adaptive layout là layout phản ứng theo kích thước cửa sổ hiện tại, không giả định thiết bị cố định; multi-window và foldable có thể thay đổi size mà không đổi orientation truyền thống.')
sec(4,'mechanism','Cơ chế hoạt động bên trong','Khi configuration thay đổi, framework cập nhật Resources.Configuration. Nếu Activity không tự khai báo xử lý loại thay đổi đó, hệ thống gọi lifecycle kết thúc instance cũ rồi tạo instance mới với Resources đã cập nhật.','ViewModelStore được giữ qua non-configuration instance, nên ViewModel cũ gắn vào Activity mới. Compose composition bị hủy và tạo lại; remember mất, rememberSaveable có thể phục hồi qua SaveableStateRegistry nếu giá trị save được.','Navigation back stack và NavBackStackEntry state có thể được khôi phục nếu host và route contract ổn định; dữ liệu không saveable phải tải lại từ repository.',codes=[('Adaptive Compose','''@Composable
fun AdaptiveScreen() {
    val c = LocalConfiguration.current
    if (c.screenWidthDp >= 600) TwoPaneContent() else SinglePaneContent()
}''')])
sec(5,'purpose','Mục đích của kỹ thuật','Recreation bảo đảm app áp dụng đúng resource và layout cho môi trường mới thay vì giữ UI cũ không còn phù hợp. Đây là cơ chế platform để app thích nghi với rotation, locale, dark mode và kích thước cửa sổ.','Kiến trúc đúng giúp user không mất tiến trình, không request mạng trùng vô ích, không leak Activity cũ và vẫn render theo configuration mới.')
sec(6,'problem','Vấn đề kỹ thuật được giải quyết','Không xử lý configuration change đúng dẫn tới mất text form, reset tab, duplicate API call, crash vì stale reference, sai ngôn ngữ, layout vỡ khi split-screen hoặc giữ bitmap và View cũ gây leak.','Ngược lại, cố giữ mọi thứ bằng singleton hay configChanges sẽ che lỗi ownership và làm app bỏ qua cơ chế resource của Android.')
sec(7,'when-to-use','Dấu hiệu cần dùng','Cần thiết kế rõ khi màn có form nhập liệu, pager hoặc tab, scroll position, filter, upload đang chạy, media playback, deep link pending hoặc long-running request.','Cần adaptive UI khi app hỗ trợ tablet, foldable, multi-window, font scale lớn, dark mode và locale runtime.')
sec(8,'when-not-to-use','Khi không nên dùng','Không dùng android:configChanges để né recreate chỉ vì mất state. Chỉ dùng khi component thật sự cần tự xử lý thay đổi và team hiểu toàn bộ resource, layout và accessibility consequence.','Không lưu object lớn, coroutine, Context, View, bitmap hoặc repository vào Bundle hay SavedStateHandle; không giữ Activity reference trong ViewModel.')
sec(9,'requirement','Yêu cầu sản phẩm cụ thể','Form tạo bài đăng phải giữ nội dung, media selection và lỗi validation khi xoay màn hình; media upload tiếp tục theo task độc lập, UI reconnect theo ID. Đổi dark mode hoặc locale phải cập nhật ngay mà không dùng dữ liệu stale.','Feed giữ selected tab, filter và scroll anchor hợp lý; recreation không được tạo request trùng không cần thiết. Chat draft và reply target phải giữ, socket không reconnect nhiều lần chỉ vì Activity recreate.','Acceptance criteria gồm rotation liên tục, font scale 200%, dark/light mode, locale change, split-screen resize, process recreation riêng biệt và kiểm tra không leak Activity cũ.')
sec(10,'analysis','Phân tích dependency, error policy, lifecycle và resource limits','Dependency: Activity và Compose chỉ render configuration; ViewModel giữ business/UI state dài hơn Activity; repository giữ source of truth; SavedStateHandle chỉ giữ key nhỏ để phục hồi. Resource selection dựa qualifier hoặc adaptive layout.','Error policy: nếu state không khôi phục được, app reload hoặc fallback rõ ràng thay vì crash. Draft quan trọng persist local, không chỉ SavedStateHandle. Resource missing phải có default qualifier.','Lifecycle: collector dùng collectAsStateWithLifecycle hoặc repeatOnLifecycle để không nhân đôi sau recreation. Side effect phải keyed đúng; DisposableEffect giải phóng observer và resource của instance cũ.','Resource limits: Bundle có giới hạn Binder; lưu danh sách lớn gây TransactionTooLargeException. Bitmap, JSON lớn và paging snapshot phải tái tạo từ cache hoặc repository.',codes=[('State ownership','''class EditViewModel(
    private val savedStateHandle: SavedStateHandle,
    private val repository: DraftRepository
) : ViewModel() {
    val draftId = savedStateHandle.getStateFlow("draftId", "")
    val state = repository.observeDraft(draftId.value)
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), EditState())
}''')])
sec(11,'minimal-code','Ví dụ code tối giản','remember giữ state trong composition hiện tại; rememberSaveable giữ giá trị saveable qua recreation; ViewModel giữ state khi Activity recreate; SavedStateHandle giúp ViewModel khôi phục key nhỏ sau process death.','UI không tự gọi API trong body. ViewModel khởi tạo request idempotent hoặc repository cache để recreation không nhân đôi work.',codes=[('Compose state','''@Composable
fun SearchRoute(viewModel: SearchViewModel = viewModel()) {
    var query by rememberSaveable { mutableStateOf("") }
    val state by viewModel.state.collectAsStateWithLifecycle()
    SearchScreen(query, { query = it }, state)
}''')])
sec(12,'upzi-case','Ví dụ thực tế Upzi','confirmed: Upzi dùng single-activity Compose, ViewModel/StateFlow, Paging và deep link; các màn feed, chat, opportunity detail và form chịu configuration recreation trực tiếp.','inferred: project có thể đã giữ selected tab, paging state và chat draft qua ViewModel hoặc rememberSaveable nhưng chưa xác nhận đầy đủ chiến lược locale, multi-window hay process recreation. proposed: lập state ownership matrix cho từng màn, persist draft quan trọng bằng local DB, dùng adaptive layout và test rotation, font scale, dark mode. needs-confirmation: cần kiểm tra manifest configChanges, Activity launch mode, SavedStateHandle usage và test hiện tại trước khi kể là đã triển khai.')
sec(13,'alternatives','Phương án thay thế','ViewModel phù hợp non-config state; rememberSaveable phù hợp UI state nhỏ; local database hoặc DataStore phù hợp durable draft; repository cache phù hợp dữ liệu tải lại. Không có một cơ chế thay thế mọi loại state.','android:configChanges chuyển trách nhiệm sang Activity.onConfigurationChanged nhưng phải tự cập nhật resource và UI. Retained Fragment là legacy; singleton là sai ownership nếu chỉ để né recreation.')
sec(14,'tradeoffs','Lý do lựa chọn và trade-off','ViewModel đơn giản và lifecycle-aware nhưng không sống qua process death. SavedStateHandle phục hồi key nhỏ nhưng có serialization cost và size limit. Local persistence bền hơn nhưng thêm IO, schema và migration.','Adaptive layout theo window size phản ánh multi-window và foldable tốt hơn chỉ kiểm tra orientation, nhưng cần nhiều layout state và test. Tự xử lý configChanges giảm recreate nhưng tăng coupling platform và dễ bỏ sót thay đổi mới.')
sec(15,'edge-cases','Edge cases','Rotation xảy ra trong permission dialog, activity result, predictive back, deep link, image picker hoặc upload callback có thể deliver vào instance mới. Contract phải gắn với launcher và lifecycle đúng.','Locale đổi runtime có thể recreate nhiều Activity trong task; cache string cũ trong singleton sẽ sai. Font scale lớn làm layout overflow dù state được giữ đúng.','Multi-window resize liên tục, fold posture change, external display, keyboard attach hoặc density change có thể tạo nhiều configuration event; không giả định chỉ portrait-landscape.','Process death sau config change là hai sự kiện khác nhau: ViewModel giữ qua cái đầu nhưng mất ở cái sau; test phải tách riêng.',codes=[('ActivityResult','''val picker = rememberLauncherForActivityResult(
    ActivityResultContracts.PickVisualMedia()
) { uri -> viewModel.onMediaPicked(uri) }
Button(onClick = { picker.launch(PickVisualMediaRequest()) }) { Text("Chọn ảnh") }''')])
sec(16,'mistakes','Sai lầm thường gặp','Lỗi phổ biến: dùng configChanges để né bug, giữ Context hoặc View trong ViewModel, gọi API ở onCreate mỗi recreation, lưu toàn bộ response vào SavedStateHandle, dùng remember cho form cần giữ và assume onDestroy luôn chạy.','Một lỗi khác là đọc LocalConfiguration để ép recomposition toàn cây hoặc hard-code orientation thay vì thiết kế theo constraints. Không duplicate state giữa rememberSaveable và ViewModel mà không có source of truth.')
sec(17,'interview-basic','Câu hỏi phỏng vấn cơ bản','Câu hỏi nền: configuration change là gì; callback lifecycle nào chạy; ViewModel sống thế nào; remember khác rememberSaveable; onSaveInstanceState dùng khi nào; configChanges có tác dụng gì; process death khác rotation ra sao.','Mẫu trả lời tốt nói rõ Activity instance bị thay, process có thể còn, ViewModelStore được retain, resource được chọn lại và state cần phân loại theo ownership.')
sec(18,'interview-deep','Câu hỏi xoáy sâu và câu hỏi bẫy','Câu xoáy: tại sao ViewModel sống qua rotation nhưng không qua process death; duplicate network request tránh thế nào; SavedStateHandle có giới hạn gì; locale change với cache string; split-screen không đổi orientation xử lý ra sao; ActivityResult có mất callback không.','Câu bẫy: onDestroy có luôn được gọi không; configChanges có tốt hơn mặc định không; rememberSaveable có lưu được bitmap không; orientation lock có giải quyết adaptive UI không; ViewModel có được giữ Activity không.')
sec(19,'experience-answer','Mẫu trả lời gắn với kinh nghiệm','Trong app Compose tôi phân loại state: business state và request đặt trong ViewModel hoặc repository; UI state nhỏ như query hoặc tab dùng rememberSaveable; draft quan trọng persist local. Recreation chỉ tạo lại UI và reconnect collector lifecycle-aware.','Với Upzi, confirmed là single-activity Compose và các flow feed, chat, deep link. Những chi tiết configChanges, locale hoặc multi-window phải nói là inferred hoặc proposed nếu chưa kiểm tra repository production.')
sec(20,'practice','Bài tập thực hành','Tạo màn form gồm text, image URI, validation error và upload progress. Thử rotation, dark mode, locale, process recreation; ghi rõ state nào dùng rememberSaveable, ViewModel, SavedStateHandle và local DB.','Tạo adaptive master-detail theo window size. Resize split-screen liên tục và bảo đảm selected item không mất.','Viết test ActivityScenario.recreate và Compose test kiểm tra form, selected tab, request count và không duplicate collector.')
sec(21,'scenario','Bài tập tình huống','User đang upload video 80% thì xoay máy. Thiết kế ownership của upload worker, progress stream, draft và UI attachment; mô tả điều gì survive recreation và process death.','Locale đổi từ Việt sang Anh khi đang ở job detail. Title server giữ nguyên nhưng label local phải đổi; cache và analytics xử lý thế nào.','Chat app split-screen rồi resize nhỏ dần. Khi nào chuyển two-pane sang one-pane và back stack hoặc selected conversation giữ ra sao.')
sec(22,'checklist','Checklist tự đánh giá','Tôi phân biệt config change với process death; biết callback, ViewModel retention, remember, rememberSaveable, SavedStateHandle và Bundle limit.','Tôi có state ownership matrix, tránh Activity reference trong ViewModel, tránh duplicate side effect và dùng adaptive layout thay vì chỉ orientation.','Tôi test rotation, dark mode, locale, font scale, multi-window và process recreation riêng; biết chi tiết Upzi nào đã xác nhận.')
sec(23,'summary','Tóm tắt cần nhớ','Configuration change thường thay Activity instance để áp dụng resource và config mới; process có thể còn và ViewModel có thể được retain. Composition cũ bị hủy nên remember mất.','Chọn cơ chế theo durability: rememberSaveable cho UI state nhỏ, ViewModel cho non-config state, SavedStateHandle cho key nhỏ phục hồi, local storage cho draft bền vững.','Không dùng configChanges hoặc singleton để che lỗi ownership. Adaptive UI dựa kích thước cửa sổ và được test dưới nhiều configuration.')
sec(24,'quiz-guide','Quiz có giải thích đáp án','Làm quiz sau khi có thể vẽ timeline rotation và process death riêng. Mỗi đáp án phải nêu owner, lifetime, serialization và fallback.','Không học thuộc callback; hãy giải thích state nào mất, state nào còn và vì sao.')
quiz=[]
def q(i,question,correct,explanation,*options): quiz.append({'id':f'q{i}','question':question,'options':[{'id':chr(97+j),'text':o} for j,o in enumerate(options)],'correctOptionIds':[chr(97+correct)],'explanation':explanation})
q(1,'Configuration change thường làm gì với Activity?',0,'Framework thường destroy instance cũ và tạo instance mới với Configuration mới.','Recreate Activity','Luôn kill process','Chỉ redraw View','Không đổi gì')
q(2,'State nào survive rotation nhưng không bảo đảm survive process death?',1,'ViewModel được retain qua configuration change nhưng mất khi process chết.','remember','ViewModel','local database','server')
q(3,'rememberSaveable phù hợp nhất với gì?',0,'Nó dành cho UI state nhỏ và saveable.','Query text nhỏ','Bitmap lớn','Repository','Coroutine scope')
q(4,'Tại sao không lưu response lớn vào SavedStateHandle?',2,'Saved state dùng Bundle và Binder có giới hạn kích thước.','Không hỗ trợ String','Luôn mã hóa','Có giới hạn size và serialization cost','Không qua rotation')
q(5,'android:configChanges nên dùng thế nào?',1,'Chỉ dùng khi thật sự muốn tự xử lý và hiểu toàn bộ hệ quả.','Mặc định mọi Activity','Chọn lọc, có lý do rõ','Để giữ ViewModel','Để tránh process death')
q(6,'Process death khác rotation ở điểm nào?',0,'Process death làm mất ViewModel và memory state.','ViewModel mất','Activity không đổi','Resource không đổi','Không cần restore')
q(7,'Adaptive layout nên ưu tiên tín hiệu nào?',2,'Kích thước cửa sổ hiện tại phản ánh multi-window và foldable tốt hơn orientation đơn thuần.','Model thiết bị','Tên Activity','Window size hoặc constraints','API response')
q(8,'Collector Flow tránh duplicate sau recreation bằng gì?',1,'Lifecycle-aware collection tự cancel và restart theo owner mới.','GlobalScope','collectAsStateWithLifecycle hoặc repeatOnLifecycle','Thread.sleep','Singleton Activity')
q(9,'Draft quan trọng nên lưu ở đâu?',3,'Durable draft cần local persistence thay vì chỉ saved state.','remember','View field','Bundle lớn','Database hoặc DataStore phù hợp')
q(10,'onDestroy có luôn chạy trước process kill không?',1,'Hệ thống có thể kill process mà không gọi callback này.','Có','Không','Chỉ landscape','Chỉ debug')
q(11,'Đổi locale có rủi ro gì với singleton cache string?',0,'Cache có thể giữ string theo locale cũ.','Giữ string cũ','Tự dịch server data','Không ảnh hưởng','Xóa database')
q(12,'Test matrix đúng gồm gì?',2,'Cần tách recreation, configuration đa dạng và process death.','Chỉ rotation','Chỉ dark mode','Rotation, locale, font scale, multi-window và process death riêng','Chỉ unit test')
lesson={'id':'e02','code':'E02','title':'Configuration Change','summary':'Hiểu recreation, resource selection, adaptive UI và chiến lược giữ state đúng qua rotation, locale, dark mode, font scale và multi-window.','estimatedMinutes':360,'sections':sections,'quiz':quiz}
lesson_path=DATA/'lessons'/'e'/'e02.json'; lesson_path.parent.mkdir(parents=True,exist_ok=True); lesson_path.write_text(json.dumps(lesson,ensure_ascii=False,separators=(',',':')))
required=['objectives','prerequisites','terminology','mechanism','purpose','problem','when-to-use','when-not-to-use','requirement','analysis','minimal-code','upzi-case','alternatives','tradeoffs','edge-cases','mistakes','interview-basic','interview-deep','experience-answer','practice','scenario','checklist','summary','quiz-guide']
ids=[s['id'] for s in sections]; paragraphs=[b['content'] for s in sections for b in s['blocks'] if b['type']=='paragraph']; codes=[b for s in sections for b in s['blocks'] if b['type']=='code']; assert ids==required and len(set(ids))==24 and len(paragraphs)>=40 and sum(map(len,paragraphs))>=9000 and len(codes)>=4 and len(quiz)>=10
text=lesson_path.read_text(); assert all(x in text for x in ['confirmed:','inferred:','proposed:','needs-confirmation:'])
catalog_path=DATA/'catalog.json'; catalog=json.loads(catalog_path.read_text())
for chapter in catalog['chapters']:
 for item in chapter['lessons']:
  if item['id']=='e02': assert item['status']=='planned'; item['status']='published'; item['estimatedMinutes']=360
catalog_path.write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
plan_path=DATA/'book-plan.json'; plan=json.loads(plan_path.read_text()); assert plan['current']=='e02'; plan['completed'].append('e02'); plan['current']='e03'; plan_path.write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
index_path=DATA/'search-index.json'; index=json.loads(index_path.read_text()); index=[x for x in index if x.get('lessonId')!='e02']; index.append({'lessonId':'e02','code':'E02','title':'Configuration Change','keywords':['configuration change','rotation','locale','dark mode','font scale','multi-window','ViewModel','rememberSaveable','SavedStateHandle','adaptive layout','WindowSizeClass','Activity recreation'],'headings':['Recreation mechanism','State ownership','Adaptive UI','Saved state limits','Multi-window','Locale and dark mode','Testing recreation','Upzi case study']}); index_path.write_text(json.dumps(index,ensure_ascii=False,indent=2)+'\n')
report={'id':'e02','sections':24,'uniqueSectionIds':24,'exactSectionOrder':True,'paragraphs':len(paragraphs),'paragraphCharacters':sum(map(len,paragraphs)),'codeBlocks':len(codes),'quizQuestions':len(quiz),'quizAnswersValid':True,'truthfulnessLabelsPresent':True,'nextLesson':'e03'}; (ROOT/'validation-e02.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n'); print(json.dumps(report,ensure_ascii=False))