import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DATA=ROOT/'android-learning'/'data'

def p(text): return {'type':'paragraph','content':text}
def c(label,code): return {'type':'code','language':'kotlin','label':label,'content':code}
sections=[
{'id':'objectives','title':'1. Mục tiêu bài học','blocks':[p('Sau bài này, người học phải giải thích được LazyColumn chỉ compose và layout vùng nội dung cần thiết như thế nào, vì sao key và contentType ảnh hưởng identity, state reuse và hiệu năng, đồng thời phân biệt rõ composition cost, measurement cost, layout cost, draw cost và image loading cost.'),p('Mục tiêu thực hành là thiết kế danh sách feed hoặc chat có stable key, immutable item model, paging, placeholder hợp lý, scroll state đúng lifecycle và đo bằng profiler thay vì tối ưu theo cảm giác.')]},
{'id':'prerequisites','title':'2. Kiến thức nền','blocks':[p('Cần nắm Composition, recomposition, stability, remember, state hoisting, ViewModel, StateFlow và collectAsStateWithLifecycle. LazyColumn không thay thế các nguyên tắc này; nó chỉ là lazy layout giúp materialize item theo viewport.'),p('Cần phân biệt dataset trong memory với PagingData, nhận biết immutable snapshot, hiểu coroutine cancellation và biết rằng ảnh, text measurement hoặc overdraw có thể là bottleneck lớn hơn recomposition.')]},
{'id':'terminology','title':'3. Định nghĩa và chú giải thuật ngữ','blocks':[p('LazyColumn là vertical lazy layout. Item provider cung cấp mô tả item, runtime chỉ compose và measure nhóm item cần thiết quanh viewport. Visible item là item đang chiếm vùng nhìn; beyond-bounds item là phần được giữ thêm để hỗ trợ scroll, focus hoặc prefetch.'),p('key là identity ổn định của item qua thay đổi dataset. contentType mô tả nhóm cấu trúc tương thích để runtime tái sử dụng composition hiệu quả hơn. LazyListState chứa scroll position và layout info; firstVisibleItemIndex không đồng nghĩa item đầu tiên hiển thị toàn bộ.') ]},
{'id':'mechanism','title':'4. Cơ chế hoạt động bên trong','blocks':[p('LazyColumn nhận DSL items và tạo LazyLayoutItemProvider. Khi measure, nó yêu cầu item theo index, subcompose item cần thiết, đo theo constraints rồi đặt chúng nối tiếp trên trục dọc. Item rời vùng hoạt động có thể bị dispose hoặc giữ tạm tùy chiến lược runtime.'),p('Khi dataset chèn hoặc xóa, key giúp runtime ánh xạ composition cũ sang item logic mới. Không có key, identity mặc định dựa vào vị trí; state remember, animation và focus có thể gắn nhầm item sau reorder.'),c('Stable key và contentType','LazyColumn(state = state) {\n    items(\n        items = messages,\n        key = { it.id },\n        contentType = { if (it.isMine) "mine" else "other" }\n    ) { message ->\n        MessageRow(message)\n    }\n}') ]},
{'id':'purpose','title':'5. Mục đích của kỹ thuật','blocks':[p('LazyColumn giới hạn số item được compose và layout ở một thời điểm, giúp danh sách lớn không trả toàn bộ chi phí upfront như Column. Nó hỗ trợ scroll state, sticky header, animated placement, paging và accessibility trong một mô hình declarative.'),p('Mục tiêu đúng không phải đạt recomposition bằng không mà giữ frame work trong ngân sách, cập nhật đúng item, tránh allocation và measurement dư, đồng thời duy trì trải nghiệm khi dữ liệu thay đổi liên tục.') ]},
{'id':'problem','title':'6. Vấn đề kỹ thuật được giải quyết','blocks':[p('Một Column chứa hàng trăm row compose và measure toàn bộ nội dung, gây startup chậm, memory pressure và jank. Danh sách realtime còn có reorder, prepend, update từng item, retry và placeholder nên identity sai dễ tạo jump hoặc stale state.'),p('LazyColumn không tự giải quyết model mutable, key không ổn định, image decode nặng, nested scroll vô hạn hoặc side effect trong item. Những lỗi đó vẫn gây jank dù layout là lazy.') ]},
{'id':'when-to-use','title':'7. Dấu hiệu cần dùng','blocks':[p('Dùng LazyColumn khi số lượng item có thể vượt vùng nhìn, dataset tải theo trang, item thay đổi độc lập hoặc cần scroll dài. Feed, chat, search result, notification và danh sách job là các trường hợp điển hình.'),p('Cần tối ưu sâu khi profiler cho thấy dropped frames lúc scroll, nhiều item bị compose lại ngoài dự kiến, GC tăng, ảnh decode chặn main thread hoặc update một item làm toàn danh sách chạy lại.') ]},
{'id':'when-not-to-use','title':'8. Khi không nên dùng','blocks':[p('Không cần LazyColumn cho nhóm nội dung ngắn, cố định và cần đo toàn bộ cùng lúc; Column có thể đơn giản hơn. Không dùng nested LazyColumn cùng chiều trong parent có chiều cao không giới hạn vì measure constraints có thể lỗi hoặc trải nghiệm scroll kém.'),p('Không dùng key ngẫu nhiên để ép refresh, không thêm derivedStateOf hoặc remember khắp nơi trước khi đo, và không tách item thành quá nhiều composable chỉ để làm đẹp recomposition counter.') ]},
{'id':'requirement','title':'9. Yêu cầu sản phẩm cụ thể','blocks':[p('Màn chat phải prepend lịch sử mà vị trí người dùng không nhảy, update trạng thái sent hoặc read chỉ tác động message tương ứng, và giữ draft hoặc expansion state đúng message sau khi ack đổi ID tạm sang ID server.'),p('Màn job feed phải cuộn mượt trên thiết bị trung bình, tải trang tiếp theo có retry riêng, placeholder không làm thay đổi chiều cao đột ngột, và khi bookmark thay đổi thì item giữ identity, image cache và accessibility focus.') ]},
{'id':'analysis','title':'10. Phân tích dependency, error policy, lifecycle và resource limits','blocks':[p('Dependency: ViewModel sở hữu stream immutable UI item hoặc PagingData; UI sở hữu LazyListState và transient interaction state. Repository không nên phát entity mutable dùng chung. Error policy cần phân biệt initial load, append error và item action error để không thay toàn danh sách bằng một màn lỗi chung.'),p('Lifecycle: collection phải lifecycle-aware; scroll restoration dùng rememberLazyListState hoặc rememberSaveable tùy navigation behavior. Resource: giới hạn image size, cache, prefetch, số item giữ state, text complexity và allocation trong item. Paging config cần cân bằng pageSize, prefetchDistance và maxSize.'),p('Concurrency: update realtime và paging có thể tới khác thứ tự. Cần reducer hoặc source of truth xác định version mới nhất; key không thể sửa race condition. Khi prepend, phải giữ anchor theo key hoặc dùng API scroll phù hợp thay vì giả định index cũ còn đúng.'),c('Paging và lifecycle','@Composable\nfun JobRoute(vm: JobViewModel) {\n    val jobs = vm.jobs.collectAsLazyPagingItems()\n    JobList(\n        jobs = jobs,\n        onRetry = jobs::retry,\n        onBookmark = vm::toggleBookmark\n    )\n}') ]},
{'id':'minimal-code','title':'11. Ví dụ code tối giản','blocks':[p('Ví dụ chuẩn dùng key từ domain identity, contentType theo cấu trúc row và tránh tạo object nặng trong lambda item. Callback mang ID thay vì capture toàn bộ mutable object.'),p('derivedStateOf chỉ dùng khi output thay đổi ít hơn input, ví dụ nút scroll-to-top chỉ đổi khi vượt qua item đầu. Đọc layoutInfo ở composition cho logic thay đổi mỗi pixel có thể gây recomposition dày.'),c('Danh sách tối giản','@Composable\nfun JobList(items: List<JobUi>, onOpen: (String) -> Unit) {\n    LazyColumn {\n        items(items, key = { it.id }, contentType = { "job" }) { job ->\n            JobRow(job = job, onClick = { onOpen(job.id) })\n        }\n    }\n}'),c('Derived scroll state','val showScrollTop by remember {\n    derivedStateOf { listState.firstVisibleItemIndex > 2 }\n}') ]},
{'id':'upzi-case','title':'12. Ví dụ thực tế Upzi','blocks':[p('confirmed: Upzi dùng Jetpack Compose, Paging3 và có các màn danh sách như job, chat hoặc feed; đây là bối cảnh trực tiếp của LazyColumn, stable key và paging load state.'),p('inferred: các item nhiều khả năng có ID domain và cập nhật trạng thái độc lập, nhưng chưa xác nhận contentType, compiler metrics, baseline profile hoặc chiến lược scroll anchoring hiện tại. proposed: chuẩn hóa immutable UI model, key theo ID, contentType theo row family, benchmark scroll và kiểm tra append error riêng. needs-confirmation: cần đối chiếu implementation thực tế trước khi dùng các chi tiết tối ưu này như kinh nghiệm đã triển khai.') ]},
{'id':'alternatives','title':'13. Phương án thay thế','blocks':[p('Column phù hợp nội dung ngắn; LazyVerticalGrid dùng cho lưới; Pager dùng cho trang ngang; RecyclerView vẫn hữu ích trong legacy screen, custom LayoutManager hoặc ecosystem adapter phức tạp. ComposeView trong RecyclerView là phương án chuyển đổi nhưng có ownership và disposal cost riêng.'),p('Paging không bắt buộc cho mọi danh sách. Dataset nhỏ có thể load một lần; dataset rất lớn hoặc remote nên dùng Paging3. Server-side aggregation, thumbnail sizing và database index có thể cải thiện nhiều hơn tối ưu UI cục bộ.') ]},
{'id':'tradeoffs','title':'14. Lý do lựa chọn và trade-off','blocks':[p('Stable key cải thiện identity và restoration nhưng yêu cầu ID thật sự duy nhất, ổn định. contentType tăng cơ hội reuse nhưng phân loại sai cấu trúc có thể gây assumptions không đúng hoặc ít lợi ích. Immutable copy dễ reasoning nhưng có allocation; persistent collection hoặc Paging giảm copy ở quy mô lớn.'),p('Giữ nhiều item state giúp trải nghiệm nhưng tăng memory. Prefetch giảm latency khi scroll nhưng tiêu CPU, network hoặc image decode sớm. Placeholder cố định chiều cao giảm layout shift nhưng có thể không phản ánh nội dung thật.') ]},
{'id':'edge-cases','title':'15. Edge cases','blocks':[p('Key trùng gây hành vi không xác định hoặc exception tùy API. Key đổi khi server ack ID có thể làm mất state; nên có identity strategy thống nhất giữa clientId và serverId. Reorder có animation cần animateItem và key ổn định.'),p('Reverse layout trong chat thay đổi semantics index và scroll-to-bottom. Sticky header, item cao biến thiên, nested horizontal list, accessibility focus, keyboard inset và foldable width đều có thể làm phép đo khác giả định.'),p('Đọc firstVisibleItemIndex để analytics cần snapshotFlow và distinctUntilChanged; đọc trực tiếp trong composition rồi gửi event là side effect sai. layoutInfo.visibleItemsInfo thay đổi rất thường xuyên nên phải tránh biến nó thành state toàn màn.'),c('Scroll analytics đúng cách','LaunchedEffect(listState) {\n    snapshotFlow { listState.firstVisibleItemIndex }\n        .distinctUntilChanged()\n        .collect(analytics::onFirstVisibleChanged)\n}') ]},
{'id':'mistakes','title':'16. Sai lầm thường gặp','blocks':[p('Lỗi phổ biến gồm dùng index làm key cho dataset có insert, tạo UUID mỗi recomposition, truyền MutableList rồi sửa tại chỗ, gọi network trong item body, decode bitmap kích thước gốc, tạo formatter hoặc parser mỗi row và đặt LazyColumn trong Column không bounded height.'),p('Một lỗi khác là kết luận mọi recomposition đều xấu. Recomposition rẻ có thể bình thường; vấn đề là work nặng trong item, invalidation scope rộng, measurement lặp, allocation cao hoặc frame miss.')]},
{'id':'interview-basic','title':'17. Câu hỏi phỏng vấn cơ bản','blocks':[p('Câu hỏi nền: LazyColumn khác Column thế nào, key dùng để làm gì, contentType là gì, LazyListState lưu gì, vì sao item ngoài viewport không nên được giả định tồn tại, và Paging3 tích hợp bằng collectAsLazyPagingItems ra sao.'),p('Mẫu trả lời tốt nêu pipeline item provider, subcomposition theo viewport, measure/layout, identity theo key và load state; không chỉ nói LazyColumn nhanh hơn vì render ít item.') ]},
{'id':'interview-deep','title':'18. Câu hỏi xoáy sâu và câu hỏi bẫy','blocks':[p('Câu xoáy: prepend chat mà không jump xử lý thế nào; key đổi từ clientId sang serverId có hậu quả gì; contentType có liên quan stability không; vì sao row không recompose nhưng scroll vẫn jank; khi nào derivedStateOf làm chậm hơn; nested lazy cùng chiều xử lý ra sao.'),p('Câu trả lời sâu phải phân tách identity, state restoration, composition, measurement, draw, image pipeline, allocation và data race. Không quy mọi vấn đề scroll về recomposition.') ]},
{'id':'experience-answer','title':'19. Mẫu trả lời gắn với kinh nghiệm','blocks':[p('Mẫu trung thực: trong màn danh sách Compose, tôi dùng immutable UI model và key theo ID để update cục bộ; với dữ liệu phân trang tôi đặt Paging ở ViewModel và xử lý refresh/append error riêng. Tôi đo bằng profiler và frame metrics trước khi tối ưu image size, allocation hoặc recomposition scope.'),p('Khi nói về Upzi, chỉ khẳng định phần confirmed. Những chi tiết như contentType, baseline profile hoặc anchor strategy phải ghi là proposed hoặc needs-confirmation nếu chưa kiểm tra code và số liệu thực tế.') ]},
{'id':'practice','title':'20. Bài tập thực hành','blocks':[p('Xây màn job list 1.000 item với key, contentType, image thumbnail, bookmark update và nút scroll-to-top. Tạo phiên bản lỗi dùng index key và MutableList, sau đó so sánh behavior khi insert đầu danh sách.'),p('Tích hợp Paging3 với refresh, append loading, append error và retry. Ghi trace scroll trước và sau khi cache formatter, resize ảnh và thu hẹp state read; báo cáo phải chỉ ra metric thay đổi, không chỉ cảm giác.') ]},
{'id':'scenario','title':'21. Bài tập tình huống','blocks':[p('Tình huống chat: đang đứng giữa lịch sử, app prepend 30 message cũ rồi nhận ack cho 5 message mới. Hãy thiết kế identity, merge policy, scroll anchor và test để bảo đảm không jump, không duplicate và không mất state item.'),p('Tình huống feed: scroll jank chỉ xảy ra với row có markdown và ảnh. Hãy lập kế hoạch đo để tách text measurement, image decode, composition và network; đề xuất fix theo thứ tự tác động và rủi ro.') ]},
{'id':'checklist','title':'22. Checklist tự đánh giá','blocks':[p('Tôi có thể giải thích item provider, viewport composition, key, contentType, LazyListState, Paging load states và scroll restoration. Tôi biết kiểm tra key duy nhất, immutable model, bounded constraints và side effect ngoài item body.'),p('Tôi có thể dùng profiler hoặc benchmark để phân biệt composition, measure, draw, image và GC; có thể thiết kế test cho insert, reorder, prepend, process recreation, retry và accessibility focus.') ]},
{'id':'summary','title':'23. Tóm tắt cần nhớ','blocks':[p('LazyColumn tiết kiệm bằng cách materialize vùng cần thiết, nhưng hiệu năng phụ thuộc toàn pipeline. Key bảo vệ identity; contentType hỗ trợ reuse; immutable state và state read hẹp giúp update chính xác; Paging quản lý dataset lớn và load state.'),p('Tối ưu danh sách phải dựa trên đo đạc. Hãy ưu tiên correctness của identity và data flow, sau đó xử lý work nặng, image sizing, measurement, allocation, prefetch và frame timing theo bằng chứng.') ]},
{'id':'quiz-guide','title':'24. Quiz có giải thích đáp án','blocks':[p('Mỗi câu hỏi kiểm tra một ranh giới quan trọng: lazy materialization, identity, state, paging, lifecycle, side effect và profiling. Không học thuộc API mà phải giải thích cơ chế và hậu quả khi chọn sai.') ]}
]
quiz=[]
def q(i,text,opts,correct,exp): quiz.append({'id':f'd07-q{i}','question':text,'options':[{'id':k,'text':v} for k,v in opts],'correctOptionIds':correct,'explanation':exp})
q(1,'Vai trò quan trọng nhất của key là gì?',[('a','Trang trí debug'),('b','Giữ identity item qua thay đổi dataset'),('c','Ép item luôn recompose'),('d','Tăng page size')],['b'],'Key ánh xạ composition và state với item logic ổn định khi insert, delete hoặc reorder.')
q(2,'Vì sao index thường là key kém cho feed có insert đầu?',[('a','Index không phải Int'),('b','Identity của item đổi khi vị trí dịch chuyển'),('c','Compose không hỗ trợ index'),('d','Index làm ảnh lớn hơn')],['b'],'Khi insert đầu, mọi index sau đó đổi dù item logic không đổi, dễ gắn state sai.')
q(3,'contentType dùng chủ yếu để làm gì?',[('a','Mã hóa dữ liệu'),('b','Nhóm cấu trúc item tương thích cho reuse'),('c','Tạo stable key'),('d','Thay ViewModel')],['b'],'contentType mô tả family của item để lazy layout tối ưu reuse; nó không thay key hay stability.')
q(4,'Cách đúng để theo dõi firstVisibleItemIndex cho analytics?',[('a','Gửi event trực tiếp trong composition'),('b','snapshotFlow trong LaunchedEffect'),('c','Network call trong item'),('d','while true trên main thread')],['b'],'snapshotFlow chuyển snapshot read thành Flow và side effect được đặt trong lifecycle của effect.')
q(5,'LazyColumn có tự sửa MutableList bị mutate tại chỗ không?',[('a','Có'),('b','Không'),('c','Chỉ ở debug'),('d','Chỉ khi có contentType')],['b'],'Lazy layout không thay data observability; mutation ngoài state có thể không invalidate UI.')
q(6,'Append error trong Paging nên xử lý thế nào?',[('a','Thay toàn màn bằng initial error'),('b','Hiển thị retry ở cuối danh sách và giữ dữ liệu cũ'),('c','Xóa cache'),('d','Đóng app')],['b'],'Append error là lỗi tải trang tiếp theo; dữ liệu hiện có vẫn hợp lệ và nên được giữ.')
q(7,'Dấu hiệu key không ổn định là gì?',[('a','Key dựa trên UUID tạo lúc compose'),('b','Key từ database ID'),('c','Key từ server ID cố định'),('d','Key từ clientId bền vững')],['a'],'UUID mới mỗi lần phá identity, khiến state và reuse bị reset.')
q(8,'Nếu scroll jank nhưng row không recompose nhiều, nguyên nhân có thể là gì?',[('a','Image decode hoặc measurement nặng'),('b','Không thể có'),('c','Chỉ do key'),('d','Chỉ do Flow')],['a'],'Frame có thể miss ở measure, layout, draw, bitmap decode hoặc GC dù recomposition ít.')
q(9,'Khi nào derivedStateOf phù hợp?',[('a','Cho mọi phép cộng'),('b','Khi output đổi ít hơn input và tránh invalidation dư'),('c','Để gọi API'),('d','Để thay rememberSaveable')],['b'],'derivedStateOf hữu ích khi state nguồn đổi thường xuyên nhưng giá trị dẫn xuất đổi thưa hơn.')
q(10,'Nested LazyColumn cùng chiều trong parent không bounded có rủi ro gì?',[('a','Constraint vô hạn và lỗi measure'),('b','Tăng bảo mật'),('c','Tự động paging'),('d','Không có rủi ro')],['a'],'Lazy layout cần constraints hữu hạn trên trục scroll; nesting sai có thể gây exception hoặc UX kém.')
q(11,'Key đổi từ clientId sang serverId sau ack có thể gây gì?',[('a','Mất identity và state item'),('b','Tăng FPS chắc chắn'),('c','Không ảnh hưởng bao giờ'),('d','Tự retry network')],['a'],'Runtime có thể coi đó là item mới. Cần identity strategy bền vững hoặc mapping rõ ràng.')
q(12,'Bước đầu tiên khi tối ưu scroll là gì?',[('a','Gắn @Stable mọi class'),('b','Đo và xác định phase hoặc resource gây bottleneck'),('c','Xóa key'),('d','Tăng delay')],['b'],'Tối ưu dựa trên profiler và benchmark giúp tránh sửa sai nguồn chi phí.')
lesson={'id':'d07','code':'D07','title':'LazyColumn và hiệu năng danh sách','summary':'Hiểu cơ chế lazy layout, identity, key, contentType, Paging, scroll state và phương pháp đo tối ưu danh sách Compose.','estimatedMinutes':360,'sections':sections,'quiz':quiz}
lesson_path=DATA/'lessons'/'d'/'d07.json'; lesson_path.parent.mkdir(parents=True,exist_ok=True); lesson_path.write_text(json.dumps(lesson,ensure_ascii=False,separators=(',',':'))+'\n')
required=['objectives','prerequisites','terminology','mechanism','purpose','problem','when-to-use','when-not-to-use','requirement','analysis','minimal-code','upzi-case','alternatives','tradeoffs','edge-cases','mistakes','interview-basic','interview-deep','experience-answer','practice','scenario','checklist','summary','quiz-guide']
ids=[s['id'] for s in sections]; assert ids==required and len(set(ids))==24
paragraphs=[b['content'] for s in sections for b in s['blocks'] if b['type']=='paragraph']; codes=[b for s in sections for b in s['blocks'] if b['type']=='code']
assert len(paragraphs)>=40 and sum(map(len,paragraphs))>=9000 and len(codes)>=5 and len(quiz)>=10
for item in quiz:
 opts={o['id'] for o in item['options']}; assert item['correctOptionIds'] and set(item['correctOptionIds'])<=opts and item['explanation'].strip()
text=lesson_path.read_text()
for label in ['confirmed:','inferred:','proposed:','needs-confirmation:']: assert label in text
catalog_path=DATA/'catalog.json'; catalog=json.loads(catalog_path.read_text()); found=False
for chapter in catalog['chapters']:
 for item in chapter['lessons']:
  if item['id']=='d07': assert item['status']=='planned'; item['status']='published'; item['estimatedMinutes']=360; found=True
assert found; catalog_path.write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
plan_path=DATA/'book-plan.json'; plan=json.loads(plan_path.read_text()); assert plan['current']=='d07'; plan['completed'].append('d07'); plan['current']='d08'; plan_path.write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
index_path=DATA/'search-index.json'; index=json.loads(index_path.read_text()); entry={'lessonId':'d07','code':'D07','title':'LazyColumn và hiệu năng danh sách','keywords':['LazyColumn','LazyListState','stable key','contentType','Paging3','collectAsLazyPagingItems','scroll performance','snapshotFlow','prefetch','load state','list identity','jank'],'headings':['Cơ chế LazyLayout','Key và identity','contentType','Paging và load state','Scroll state và restoration','Đo hiệu năng danh sách','Chat prepend','Upzi case study']}; index[:]=[x for x in index if x.get('lessonId')!='d07']+[entry]; index_path.write_text(json.dumps(index,ensure_ascii=False,indent=2)+'\n')
report={'id':'d07','sections':len(ids),'uniqueSectionIds':len(set(ids)),'exactSectionOrder':ids==required,'paragraphs':len(paragraphs),'paragraphCharacters':sum(map(len,paragraphs)),'codeBlocks':len(codes),'quizQuestions':len(quiz),'quizAnswersValid':True,'truthfulnessLabelsPresent':True,'nextLesson':'d08'}
(ROOT/'validation-d07.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n'); print(json.dumps(report,ensure_ascii=False))