import json
from pathlib import Path

ROOT=Path('android-learning/data')
CANON=['objectives','prerequisites','terminology','mechanism','purpose','problem','when-to-use','when-not-to-use','requirement','analysis','minimal-code','upzi-case','alternatives','tradeoffs','edge-cases','mistakes','interview-basic','interview-deep','experience-answer','practice','scenario','checklist','summary','quiz-guide']
def p(*xs): return [{'type':'paragraph','content':x} for x in xs]
def code(label,s): return {'type':'code','language':'kotlin','label':label,'content':s}
S=[]
def sec(i,t,*xs): S.append({'id':i,'title':t,'blocks':p(*xs)})
sec('objectives','1. Mục tiêu bài học','Hiểu Data Mapping là việc chuyển dữ liệu giữa các representation có contract và mục đích khác nhau, không phải thao tác copy field máy móc.','Phân biệt DTO, persistence entity, domain model, application model và UI model; xác định boundary nào cần mapper riêng.','Thiết kế mapper an toàn trước nullability, versioning, enum lạ, timestamp, pagination, partial response, localization và dữ liệu không hợp lệ.','Đánh giá trade-off giữa tách model nghiêm ngặt và dùng chung model; xây chiến lược test, observability và migration phù hợp sản phẩm Android thực tế.')
sec('prerequisites','2. Kiến thức nền','Cần nắm F01 Separation of Concerns, F04 Clean Architecture, F05 Repository Pattern và F06 Use Case.','Cần hiểu Kotlin data class, sealed interface, nullable type, serialization, Retrofit DTO, Room Entity, Flow, Paging và immutable UI state.','Mapping chỉ có ý nghĩa khi boundary và ownership rõ. Nếu chưa biết model thuộc tầng nào, mapper dễ biến thành nơi che giấu kiến trúc mơ hồ.')
sec('terminology','3. Định nghĩa và chú giải thuật ngữ','DTO là representation của transport contract như JSON request/response; tên field, nullability và enum chịu ảnh hưởng API.','Persistence Entity là representation tối ưu cho schema local như Room table, index, foreign key và migration. Nó không đồng nghĩa domain entity.','Domain Model biểu diễn khái niệm và invariant nghiệp vụ bằng ngôn ngữ sản phẩm. UI Model biểu diễn dữ liệu sẵn sàng render, có thể chứa text đã format, icon key hoặc trạng thái hiển thị.','Mapper là hàm hoặc object chuyển representation. Adapter chuyển interface hoặc protocol; assembler thường ghép nhiều nguồn thành object lớn hơn; normalizer chuẩn hóa dữ liệu trước khi lưu hoặc so sánh.','Lossless mapping bảo toàn toàn bộ thông tin cần thiết để map ngược; lossy mapping chủ động bỏ dữ liệu không cần ở tầng đích. Round-trip mapping chỉ hợp lệ khi contract yêu cầu.')
sec('mechanism','4. Cơ chế hoạt động bên trong','Dữ liệu đi qua boundary theo pipeline phổ biến: network DTO -> normalized local entity -> domain model -> UI model. Chiều ghi đi ngược nhưng không nhất thiết đối xứng.','Mapper giải quyết khác biệt về tên, type, default, timezone, enum, identity, ordering và nested structure. Nó cũng là nơi từ chối hoặc phân loại dữ liệu không hợp lệ.','Mapping nên là pure function khi có thể để deterministic và dễ test. Dependency như Clock, Locale, formatter hoặc feature flag chỉ inject khi mapping thật sự phụ thuộc chúng.','Khi API trả partial object, mapper phải biết field absent khác field null. Nếu serializer làm mất distinction này, update có thể xóa dữ liệu hợp lệ.','Với collection lớn, map tạo allocation và có thể gây jank nếu chạy trên main thread. Tuy nhiên chuyển dispatcher không sửa được thuật toán hoặc model quá nặng.','Stable identity phải được giữ xuyên mapping để Paging, LazyColumn, optimistic update và diffing không xem cùng một item thành item mới.')
sec('purpose','5. Mục đích của kỹ thuật','Data Mapping bảo vệ domain và UI khỏi thay đổi của API, database hoặc SDK bên ngoài.','Nó cho phép mỗi representation tối ưu cho concern riêng: DTO tương thích wire format, entity tối ưu query, domain giữ invariant, UI tối ưu render.','Mapper tạo một điểm kiểm soát để xử lý compatibility, validation, default và telemetry thay vì rải logic trong ViewModel hoặc composable.','Mục tiêu không phải tạo nhiều class nhất mà giảm coupling và làm rõ semantic transformation.')
sec('problem','6. Vấn đề kỹ thuật được giải quyết','Dùng Retrofit DTO trực tiếp trong UI làm API rename, nullable field hoặc enum mới lan đến toàn bộ presentation.','Dùng Room Entity làm domain khiến schema migration và quan hệ bảng chi phối business rule.','Copy field rải rác tạo inconsistency: màn hình A dùng UTC, màn hình B dùng local time; nơi này coi null là 0, nơi khác coi là unknown.','Mapping tập trung giúp audit rule, test edge case và thay đổi contract mà không gây ripple không kiểm soát.')
sec('when-to-use','7. Dấu hiệu cần dùng','Dùng mapper khi hai tầng có lifecycle, owner, schema, nullability hoặc reason to change khác nhau.','Dùng khi API có versioning, nullable/optional phức tạp, enum mở, timestamp, polymorphism hoặc partial payload.','Dùng khi local database là source of truth và cần normalize network data trước khi transaction.','Dùng UI mapper khi presentation cần derive badge, grouped item, accessibility label hoặc trạng thái render không thuộc domain.')
sec('when-not-to-use','8. Khi không nên dùng','Không cần model và mapper riêng cho mọi tầng nếu representation thật sự ổn định, nhỏ và không tạo coupling đáng kể.','Không tạo mapper chỉ copy 20 field giống hệt rồi không có boundary value; cân nhắc typealias, shared immutable model hoặc factory có chủ đích.','Không đặt network call, database write, navigation hay analytics side effect trong mapper.','Không dùng mapper để nuốt dữ liệu sai và trả default giả làm dữ liệu hợp lệ.','Không format string phụ thuộc locale trong domain mapper nếu đó là concern presentation.')
sec('requirement','9. Yêu cầu sản phẩm cụ thể','Feed phải giữ postId ổn định, phân biệt reaction count unknown với 0, map media ratio an toàn và không crash khi backend thêm loại post mới.','Chat phải reconcile clientId và serverId, giữ delivery state, timestamp chuẩn, reply reference và không tạo duplicate khi map socket event cùng REST snapshot.','Opportunity phải phân biệt salary absent, confidential và numeric range; deadline phải xử lý timezone, expired state và server clock.','Acceptance criteria gồm policy cho unknown enum, malformed timestamp, partial update, null/default, round-trip cần thiết, logging PII và benchmark collection lớn.','Mọi mapper phải xác định input contract, output invariant và failure mode: reject, skip item, degraded model hay typed error.')
sec('analysis','10. Phân tích dependency, error policy, lifecycle và resource limits','Dependency: mapper thuần không phụ thuộc Android. Formatter UI có thể phụ thuộc Locale/Resources qua abstraction ở presentation.','Error policy: malformed critical identity nên reject; field phụ có thể degrade với Unknown. Không catch Throwable rồi trả object rỗng.','Lifecycle: mapper không giữ Context, View, Cursor, ResponseBody hoặc mutable buffer sau khi hoàn tất.','Resource limits: tránh map toàn bộ Paging dataset, decode Base64 bitmap trong mapper hoặc giữ nested DTO khổng lồ trong UI state.','Threading: CPU-heavy mapping cần đo; dùng mapLatest hoặc dispatcher phù hợp nhưng giữ cancellation cooperative.','Consistency: network snapshot -> database phải map và write trong transaction khi nhiều bảng liên quan.','Versioning: unknown enum nên dùng sealed Unknown(raw) hoặc fallback có telemetry; ordinal enum không bền vững.','Security: không log raw token, nội dung chat, CV hoặc PII khi mapping lỗi; dùng field path và category đã redact.','Testing: property-based test hữu ích cho timestamp/range; golden test hữu ích cho payload version; contract test giữ fake và production mapper nhất quán.')
S.append({'id':'minimal-code','title':'11. Ví dụ code tối giản','blocks':p('Mapper nên encode policy rõ thay vì dùng !! hoặc default mơ hồ.')+[code('DTO sang domain với unknown enum','''data class JobDto(val id:String?,val title:String?,val status:String?)
sealed interface JobStatus { data object Open:JobStatus; data object Closed:JobStatus; data class Unknown(val raw:String?):JobStatus }
data class Job(val id:String,val title:String,val status:JobStatus)
fun JobDto.toDomain():Result<Job> = runCatching {
 val stableId=requireNotNull(id?.takeIf(String::isNotBlank))
 Job(stableId,title?.trim().orEmpty(),when(status){
  "OPEN"->JobStatus.Open; "CLOSED"->JobStatus.Closed; else->JobStatus.Unknown(status)
 })
}'''),code('Entity và UI mapper','''fun MessageEntity.toDomain()=Message(id=id,clientId=clientId,text=text,createdAt=Instant.ofEpochMilli(createdAtMs))
fun Message.toUi(zone:ZoneId)=MessageUi(key=id?:clientId,text=text,time=createdAt.atZone(zone).toLocalTime().toString())''')]})
sec('upzi-case','12. Ví dụ thực tế Upzi','confirmed: Upzi có Compose, Paging, chat Socket.IO, optimistic clientId, ack timeout, delivered/read/typing, feed và opportunity data. Các flow này có nhiều representation cần identity ổn định.','inferred: code hiện tại chắc chắn có một mức mapping giữa API JSON, model và UI, nhưng chưa xác nhận boundary, mapper class hay policy unknown enum ở từng module.','proposed: chuẩn hóa ChatMessageDto/Entity/Domain/Ui; resolver identity ưu tiên serverId nhưng giữ clientId; map socket patch theo field presence; contract test REST và socket cùng tạo canonical message.','proposed: tách Opportunity mapper xử lý salary semantics, timezone và unknown employment type; Feed mapper giữ stable key, media metadata và pagination cursor ngoài item domain.','needs-confirmation: cần kiểm tra production code về SwiftyJSON/JSON model tương ứng Android, DTO reuse, database schema, mapper location và telemetry trước khi trình bày như kinh nghiệm đã triển khai.','needs-confirmation: cần xác nhận API có partial update, enum versioning và server timestamp contract cụ thể.')
sec('alternatives','13. Phương án thay thế','Dùng chung một immutable model phù hợp khi boundary nhỏ, contract đồng nhất và chi phí tách model lớn hơn rủi ro coupling.','Factory hoặc secondary constructor phù hợp mapping đơn giản gắn chặt với type đích. Extension function phù hợp discoverability nhưng có thể khó inject dependency.','Dedicated Mapper class phù hợp khi cần dependency, nhiều chiều mapping hoặc test riêng.','Kotlin serialization custom serializer xử lý wire-level conversion; Room TypeConverter xử lý storage-level scalar conversion, không thay thế domain mapper.','Code generation giảm boilerplate nhưng không tự quyết định semantic default, invariant hay unknown policy.')
sec('tradeoffs','14. Lý do lựa chọn và trade-off','Tách model tăng isolation và explicitness nhưng thêm class, allocation, mapping code và cognitive load.','Dùng chung model giảm boilerplate nhưng tăng ripple khi API hoặc database đổi.','Strict mapping phát hiện lỗi sớm nhưng có thể làm mất toàn bộ màn hình vì một item xấu; lenient mapping tăng availability nhưng dễ che data quality issue.','Map eager đơn giản nhưng tốn CPU/memory; lazy mapping tiết kiệm nhưng có thể lặp computation và kéo dependency sống lâu.','UI model đã format giúp composable đơn giản nhưng phải rebuild khi locale/timezone thay đổi.','Map ngược hai chiều tiện edit flow nhưng dễ giả định round-trip không có thật; command DTO nên được xây từ input nghiệp vụ riêng.')
sec('edge-cases','15. Edge cases','Backend thêm enum mới; app cũ không được crash hoặc coi nhầm thành giá trị mặc định nguy hiểm.','Timestamp thiếu offset, leap second, DST transition hoặc clock server/client lệch.','JSON field absent khác explicit null trong PATCH; merge sai có thể xóa avatar hoặc metadata.','REST snapshot đến sau socket event và ghi đè delivery state mới hơn.','Pagination trả trùng item hoặc item đổi sort key giữa các trang.','Numeric overflow khi map Long sang Int; currency scale và floating-point rounding.','Unicode normalization làm identity/search khác nhau; blank string khác null.','Database migration giữ legacy sentinel như -1; mapper phải chuyển đúng Unknown chứ không thành số thật.','Polymorphic payload có subtype không biết; degraded placeholder cần stable key.','Locale đổi khi app đang mở khiến UI model format cũ.')
sec('mistakes','16. Sai lầm thường gặp','Dùng cùng một data class cho Retrofit, Room, domain và Compose chỉ để giảm file.','Dùng !! trong mapper vì tin backend luôn đúng.','Biến null thành 0, false hoặc chuỗi rỗng mà không xét semantic.','Map enum bằng ordinal hoặc when không có Unknown strategy.','Format ngày, tiền và plural trong repository domain mapper.','Nuốt mọi lỗi và bỏ item âm thầm, khiến số liệu sai nhưng không có telemetry.','Đặt mapper trong ViewModel và lặp lại ở nhiều màn hình.','Tạo generic reflection mapper che logic nghiệp vụ và khó debug.','Giữ ResponseBody, Cursor hoặc Context trong output.','Không test payload cũ/mới, partial update và collection lớn.')
sec('interview-basic','17. Câu hỏi phỏng vấn cơ bản','Data Mapping là gì và tại sao không nên dùng DTO trực tiếp trong UI?','Phân biệt DTO, Room Entity, domain model và UI model.','Mapper nên nằm ở layer nào?','Khi nào nên tách model, khi nào dùng chung?','Unknown enum nên xử lý thế nào?','Null, absent và default khác nhau ra sao?','Tại sao mapping nên là pure function?','Có nên dùng extension function cho mapper không?')
sec('interview-deep','18. Câu hỏi xoáy sâu và câu hỏi bẫy','Một item malformed trong page 50 phần tử: fail cả page hay skip item? Hãy nêu tiêu chí sản phẩm và telemetry.','REST snapshot và socket patch về sai thứ tự: mapper hay repository chịu trách nhiệm version reconciliation?','Làm sao giữ round-trip cho edit draft khi UI model đã format và bỏ dữ liệu?','Mapping 10.000 item gây jank: bạn đo và tối ưu ở đâu trước?','API PATCH cần phân biệt absent/null nhưng DTO nullable không làm được; thiết kế type nào?','Unknown enum ảnh hưởng authorization hoặc payment thì có được fallback không?','Mapper có được gọi repository để tra dữ liệu bổ sung không? Vì sao assembler/use case có thể phù hợp hơn?','Bạn test timezone, currency precision, integer overflow và schema version bằng cách nào?')
sec('experience-answer','19. Mẫu trả lời gắn với kinh nghiệm của người học','Tôi xem mapping là boundary contract, không chỉ copy field. Với chat, điều quan trọng là canonical identity giữa clientId và serverId, delivery state và ordering từ REST/socket.','Trong Upzi, confirmed là có optimistic chat, Paging và nhiều model dữ liệu. Tôi chỉ khẳng định kiến trúc mapper cụ thể sau khi kiểm tra code; phần chuẩn hóa DTO/Entity/Domain/Ui hiện nên trình bày là proposed hoặc needs-confirmation.','Khi thiết kế, tôi ưu tiên pure mapper, typed Unknown, không dùng !!, giữ stable key và test payload malformed. Repository chịu source-of-truth/reconciliation; mapper chịu transformation và output invariant.','Tôi không tách model theo giáo điều. Với model nhỏ ổn định có thể dùng chung; khi API, DB và UI có reason to change khác nhau thì tách giúp giảm coupling đáng kể.')
sec('practice','20. Bài tập thực hành','Tạo JobDto có nullable field, enum lạ và timestamp; viết mapper Result<Job> cùng 15 unit test.','Thiết kế OptionalField gồm Absent và Present(value) để map PATCH không mất semantic.','Benchmark map 1.000, 10.000 và 100.000 item; đo allocation và main-thread time.','Viết mapper ChatMessage giữa DTO, Entity, Domain, UI; giữ clientId/serverId và reply reference.','Thêm property-based test cho salary range, timestamp và integer overflow.','Refactor một ViewModel đang dùng DTO trực tiếp sang boundary rõ, ghi lại trade-off.')
sec('scenario','21. Bài tập tình huống','Backend thêm status ARCHIVED nhưng app chỉ biết OPEN/CLOSED. Thiết kế degraded UI, analytics và rollout policy.','Socket gửi deliveredAt trước khi REST trả message có serverId. Mô tả canonical merge, identity resolver và transaction.','API trả 49 item tốt và 1 item thiếu id. Quyết định fail/skip/placeholder dựa trên acceptance criteria.','Người dùng đổi timezone khi app nền; xác định model nào cần rebuild và dữ liệu nào vẫn lưu UTC.','Database có legacy salary=-1. Lập migration và mapper để không hiển thị -1 đồng.')
sec('checklist','22. Checklist tự đánh giá','Tôi xác định rõ owner và reason to change của mỗi model.','Tôi phân biệt absent, null, unknown và default.','Tôi có policy cho malformed critical field và optional field.','Tôi giữ stable identity qua network, database, domain và UI.','Tôi không rò DTO/Entity/Context/ResponseBody qua boundary.','Tôi xử lý enum mở, timezone, precision và overflow.','Tôi biết mapping nào lossless, lossy hoặc cần round-trip.','Tôi đo mapping collection lớn thay vì đoán.','Tôi test payload version, partial update và out-of-order event.','Tôi log lỗi mapping đã redact và có metric theo category.')
sec('summary','23. Tóm tắt cần nhớ','Data Mapping bảo vệ boundary và semantic, không phải nghi thức copy field.','DTO, persistence entity, domain model và UI model phục vụ contract khác nhau; chỉ tách khi isolation có giá trị.','Null, absent, unknown, default và malformed phải có policy rõ.','Mapper nên thuần, deterministic, không side effect và không giữ resource lifecycle ngắn.','Stable identity, timestamp, enum mở, partial update và precision là các điểm dễ gây bug sản phẩm.','Repository chịu source of truth và reconciliation; mapper chịu transformation và output invariant.','Strict hay lenient phải là quyết định sản phẩm có telemetry, không phải catch-all tùy tiện.','Test mapping cần cả example, property, golden/contract và benchmark khi dataset lớn.')
quiz=[
('Mục tiêu chính của mapper là gì?',['Giảm số file','Chuyển representation và bảo vệ boundary','Thay repository','Chạy network'],'B','Mapper chuyển dữ liệu giữa contract khác nhau và cô lập thay đổi.'),
('Unknown enum nên xử lý mặc định ra sao?',['Crash','Ép về giá trị đầu','Có policy Unknown/fail theo mức độ nguy hiểm','Bỏ qua luôn'],'C','Enum mở cần chiến lược rõ; hành vi nguy hiểm có thể phải fail closed.'),
('Field absent trong PATCH khác null thế nào?',['Không khác','Absent giữ giá trị cũ, null có thể yêu cầu xóa','Null luôn là 0','Absent là lỗi JSON'],'B','Hai trạng thái mang ý nghĩa cập nhật khác nhau.'),
('Room Entity có phải domain entity không?',['Luôn luôn','Không nhất thiết','Chỉ khi dùng Compose','Chỉ khi có primary key'],'B','Room Entity tối ưu persistence schema; domain entity tối ưu nghiệp vụ.'),
('Mapper nên làm network call không?',['Có','Không; orchestration thuộc use case/repository/assembler','Chỉ main thread','Chỉ GET'],'B','Mapper nên là transformation thuần khi có thể.'),
('Dùng enum ordinal có vấn đề gì?',['Chậm','Không bền khi thứ tự enum đổi','Tốn RAM','Không serialize được'],'B','Ordinal phụ thuộc thứ tự và dễ hỏng compatibility.'),
('Stable identity quan trọng cho gì?',['Chỉ log','Paging, diffing và optimistic reconciliation','Chỉ database','Chỉ analytics'],'B','Identity không ổn định gây duplicate và UI churn.'),
('Strict mapping luôn tốt hơn lenient?',['Đúng','Sai; phụ thuộc criticality và availability requirement','Chỉ Android 14','Chỉ offline'],'B','Cần trade-off sản phẩm và telemetry.'),
('UI formatting nên nằm đâu?',['DTO mapper','Presentation/UI mapper','Room migration','Socket adapter'],'B','Locale, plural và display text là concern presentation.'),
('Map 10000 item gây jank, bước đầu là gì?',['Thêm Dispatchers.IO ngay','Đo trace/allocation và kiểm tra có cần map toàn bộ không','Dùng reflection','Tăng heap'],'B','Đo và giảm công việc trước khi chuyển thread mù quáng.'),
('Round-trip mapping có luôn cần không?',['Có','Không; chỉ khi contract edit/persist yêu cầu bảo toàn thông tin','Chỉ JSON','Chỉ Room'],'B','Nhiều mapping chủ động lossy và không nên giả định đối xứng.'),
('Ai chịu source-of-truth reconciliation?',['Composable','Mapper đơn lẻ','Repository/application policy','Serializer'],'C','Mapper chuyển representation; repository/application layer quản lý nguồn dữ liệu và ordering.')]
S.append({'id':'quiz-guide','title':'24. Quiz có giải thích đáp án','blocks':[{'type':'quiz','questions':[{'question':q,'options':o,'answer':a,'explanation':e} for q,o,a,e in quiz]}]})
lesson={'id':'f07','code':'F07','title':'Data Mapping','summary':'Thiết kế mapping an toàn giữa DTO, persistence entity, domain model và UI model với semantic rõ, compatibility, identity ổn định và kiểm thử sâu.','estimatedMinutes':360,'sections':S}
(ROOT/'lessons/f').mkdir(parents=True,exist_ok=True)
(ROOT/'lessons/f/f07.json').write_text(json.dumps(lesson,ensure_ascii=False,separators=(',',':')),encoding='utf-8')
cat=json.loads((ROOT/'catalog.json').read_text())
for ch in cat.get('chapters',cat if isinstance(cat,list) else []):
 for x in ch.get('lessons',[]):
  if x.get('id')=='f07': x.update(status='published',estimatedMinutes=360)
(ROOT/'catalog.json').write_text(json.dumps(cat,ensure_ascii=False,indent=2)+'\n')
plan=json.loads((ROOT/'book-plan.json').read_text()); plan['current']='f08';
if 'f07' not in plan['completed']: plan['completed'].append('f07')
(ROOT/'book-plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
idx=json.loads((ROOT/'search-index.json').read_text())
entry={'id':'f07','code':'F07','title':'Data Mapping','path':'data/lessons/f/f07.json','summary':lesson['summary'],'keywords':['data mapping','DTO','entity','domain model','UI model','mapper','unknown enum','partial update','stable identity']}
if isinstance(idx,list): idx=[x for x in idx if x.get('id')!='f07']+[entry]
elif 'items' in idx: idx['items']=[x for x in idx['items'] if x.get('id')!='f07']+[entry]
(ROOT/'search-index.json').write_text(json.dumps(idx,ensure_ascii=False,indent=2)+'\n')
valid={'id':'f07','sections':len(S),'uniqueSectionIds':len(set(x['id'] for x in S)),'exactSectionOrder':[x['id'] for x in S]==CANON,'paragraphs':sum(1 for s in S for b in s['blocks'] if b['type']=='paragraph'),'paragraphCharacters':sum(len(b['content']) for s in S for b in s['blocks'] if b['type']=='paragraph'),'codeBlocks':sum(1 for s in S for b in s['blocks'] if b['type']=='code'),'quizQuestions':len(quiz),'quizAnswersValid':all(a in 'ABCD' for _,_,a,_ in quiz),'truthfulnessLabelsPresent':all(k in json.dumps(lesson,ensure_ascii=False) for k in ['confirmed','inferred','proposed','needs-confirmation']),'nextLesson':'f08'}
(ROOT/'validation-f07.json').write_text(json.dumps(valid,ensure_ascii=False,indent=2)+'\n')
assert valid['sections']==24 and valid['exactSectionOrder'] and valid['quizQuestions']>=10 and valid['quizAnswersValid'] and valid['truthfulnessLabelsPresent']
