import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'android-learning'/'data'; sections=[]
def sec(i,id,title,*paras,codes=None):
 b=[{'type':'paragraph','content':p} for p in paras]
 for label,code in (codes or []): b.append({'type':'code','language':'kotlin','label':label,'content':code})
 sections.append({'id':id,'title':f'{i}. {title}','blocks':b})
sec(1,'objectives','Mục tiêu bài học','Hiểu mô hình permission của Android như một hợp đồng giữa manifest, runtime grant, AppOps, package visibility, platform version và hành vi sản phẩm; không xem permission chỉ là một hộp thoại xin quyền.','Người học phải thiết kế được flow xin quyền theo từng phiên bản Android, giải thích grant, deny, deny permanently, one-time permission, auto-reset, approximate location, selected photos và notification permission.','Mục tiêu thực hành là xây compatibility matrix, request permission đúng thời điểm, degrade gracefully, kiểm thử nhiều API level và tránh crash hoặc silent failure khi capability thay đổi.')
sec(2,'prerequisites','Kiến thức nền','Cần nắm Activity Result API, lifecycle, foreground service, notification, media picker, location, camera, storage và manifest merging.','Cần phân biệt compileSdk, targetSdk và minSdk. compileSdk quyết định API có thể biên dịch; minSdk quyết định thiết bị thấp nhất; targetSdk kích hoạt nhiều behavior change của platform.','Permission status không phải business state bền vững. User có thể đổi quyền trong Settings bất kỳ lúc nào, nên app phải kiểm tra lại trước khi dùng capability.')
sec(3,'terminology','Định nghĩa và chú giải thuật ngữ','Normal permission được cấp tự động; dangerous permission cần runtime grant; signature permission chỉ dành cho app cùng certificate hoặc được platform cho phép.','Permission group giúp hệ thống trình bày nhưng không nên được dùng như cam kết rằng các quyền trong nhóm luôn được cấp cùng nhau.','AppOps là lớp policy bổ sung có thể chặn hành vi dù manifest permission tồn tại. targetSdk là tín hiệu compatibility làm behavior thay đổi theo version.','Capability-based design nghĩa là UI dựa trên khả năng hiện tại thay vì giả định quyền đã được cấp.')
sec(4,'mechanism','Cơ chế hoạt động bên trong','Package Manager đọc manifest khi cài app và ghi requested permissions. Runtime request đi qua system UI; kết quả grant được lưu ngoài process nên sống qua process death nhưng có thể bị user hoặc hệ thống thay đổi.','ContextCompat.checkSelfPermission kiểm tra grant hiện tại; Activity Result contract điều phối request và callback qua lifecycle. shouldShowRequestPermissionRationale chỉ là tín hiệu UX, không phải API phân loại chắc chắn deny permanently.','Behavior phụ thuộc OS version và targetSdk. Cùng một binary có thể nhận dialog, permission split hoặc restriction khác nhau trên Android 12, 13, 14 hay 15.',codes=[('Request permission trong Compose','''@Composable
fun CameraPermissionGate(onGranted: () -> Unit) {
    val launcher = rememberLauncherForActivityResult(
        ActivityResultContracts.RequestPermission()
    ) { granted -> if (granted) onGranted() }
    Button(onClick = { launcher.launch(Manifest.permission.CAMERA) }) {
        Text("Mở camera")
    }
}''')])
sec(5,'purpose','Mục đích của kỹ thuật','Permission bảo vệ dữ liệu và capability nhạy cảm như camera, microphone, contacts, location, nearby devices, notifications và media.','Thiết kế compatibility đúng giúp app hoạt động ổn định qua nhiều API level, giữ trust của user và tránh xin quyền không cần thiết hoặc xin quá sớm.')
sec(6,'problem','Vấn đề kỹ thuật được giải quyết','Nếu request sai thời điểm, user dễ từ chối và conversion giảm. Nếu không có fallback, app bị dead-end hoặc crash SecurityException.','Nếu chỉ test một Android version, app có thể hỏng do permission rename/split, targetSdk behavior change, background restriction hoặc OEM implementation khác.')
sec(7,'when-to-use','Dấu hiệu cần dùng','Cần runtime permission khi feature thực sự sắp dùng dangerous capability: chụp ảnh, ghi âm, đọc contacts, location hoặc notification trên version yêu cầu.','Cần compatibility branch khi API, permission hoặc system picker khác nhau giữa version; ví dụ photo picker, Bluetooth permissions, notification permission và foreground service types.')
sec(8,'when-not-to-use','Khi không nên dùng','Không xin permission ở app launch nếu user chưa hiểu lợi ích. Không xin toàn bộ quyền dự phòng cho feature chưa dùng.','Không xin storage permission nếu system picker hoặc Storage Access Framework đáp ứng use case. Không xin location nếu chỉ cần user nhập địa điểm.','Không dùng version check rải rác khắp UI; gom policy trong capability layer để tránh divergence.')
sec(9,'requirement','Yêu cầu sản phẩm cụ thể','Post composer phải cho chọn ảnh/video bằng system picker khi có thể; chỉ xin camera/microphone khi user chọn capture hoặc record. Nếu từ chối, user vẫn chọn file có sẵn.','Notification permission chỉ xin sau khi giải thích giá trị như chat hoặc job alert; nếu từ chối, app vẫn hoạt động và có entry mở Settings.','Location cho tìm việc gần đây phải hỗ trợ approximate location; nếu không có quyền, dùng địa điểm user nhập hoặc city đã lưu.','Acceptance criteria gồm first deny, second deny, Settings revoke, one-time permission expiration, auto-reset, process death giữa dialog, API 26 tới target mới nhất và OEM phổ biến.')
sec(10,'analysis','Phân tích dependency, error policy, lifecycle và resource limits','Dependency: UI phát intent xin capability; permission coordinator đọc platform state; feature layer nhận result dưới dạng domain capability. Repository không nên tự mở permission dialog.','Error policy: SecurityException phải được coi là recoverable khi quyền bị revoke giữa check và use. Catch ở boundary, cập nhật capability state và hướng user tới fallback.','Lifecycle: chỉ launch request khi Activity/Composable active; không giữ callback cũ qua recreation. Activity Result API tốt hơn requestCode thủ công.','Resource limits: tránh request lặp liên tục; rationale và Settings prompt phải rate-limit. Không cache grant quá lâu vì user có thể revoke bất kỳ lúc nào.',codes=[('Capability abstraction','''sealed interface CameraAccess {
    data object Granted : CameraAccess
    data object CanRequest : CameraAccess
    data object NeedsSettings : CameraAccess
}

fun cameraAccess(activity: Activity): CameraAccess {
    if (ContextCompat.checkSelfPermission(activity, Manifest.permission.CAMERA)
        == PackageManager.PERMISSION_GRANTED) return CameraAccess.Granted
    return if (ActivityCompat.shouldShowRequestPermissionRationale(
            activity, Manifest.permission.CAMERA
        )) CameraAccess.CanRequest else CameraAccess.CanRequest
}''')])
sec(11,'minimal-code','Ví dụ code tối giản','Request multiple permissions chỉ khi feature cần tất cả; nếu các capability độc lập, xin riêng để user hiểu và app degrade từng phần.','Version branch nên bao quanh permission string và behavior, không bao quanh toàn bộ business flow.',codes=[('Notification permission theo version','''fun shouldRequestNotifications(): Boolean =
    Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU

val launcher = registerForActivityResult(
    ActivityResultContracts.RequestPermission()
) { granted -> viewModel.onNotificationPermissionResult(granted) }

if (shouldRequestNotifications()) {
    launcher.launch(Manifest.permission.POST_NOTIFICATIONS)
}''')])
sec(12,'upzi-case','Ví dụ thực tế Upzi','confirmed: Upzi có image/video picker, upload media, chat notification, deep link và target/compile SDK hiện đại; đây là các flow liên quan permission và version compatibility.','inferred: app có thể dùng Activity Result API và system picker, nhưng chưa xác nhận đầy đủ notification permission, selected photos, Bluetooth hoặc location behavior. proposed: tạo CapabilityPolicy tập trung, permission analytics funnel và API-level test matrix. needs-confirmation: cần kiểm tra manifest merged output, targetSdk hiện tại, picker implementation và rationale UX trước khi kể là đã triển khai.')
sec(13,'alternatives','Phương án thay thế','Dùng Photo Picker hoặc Storage Access Framework thay READ_MEDIA_* khi chỉ cần user chọn một số file.','Dùng camera intent thay camera permission nếu app không cần điều khiển camera trực tiếp. Dùng browser/system settings intent cho capability hệ thống.','Dùng approximate location, city selector hoặc server-side search thay exact location khi sản phẩm không cần độ chính xác cao.')
sec(14,'tradeoffs','Lý do lựa chọn và trade-off','System picker giảm permission surface và tăng privacy nhưng UI tùy hệ thống, quyền URI có scope và feature editing có thể hạn chế.','Xin quyền theo ngữ cảnh tăng tỷ lệ đồng ý nhưng flow phức tạp hơn; xin sớm đơn giản code nhưng gây distrust và deny cao.','Capability abstraction tăng testability nhưng cần mapping version/OEM cẩn thận. Version-specific workaround giải quyết nhanh nhưng tạo technical debt nếu không có expiry.')
sec(15,'edge-cases','Edge cases','User revoke permission trong Settings khi app background; app quay lại foreground phải refresh. Permission có thể bị auto-reset sau thời gian dài không dùng.','One-time location/microphone grant hết hiệu lực sau phiên; approximate location vẫn báo granted nhưng dữ liệu kém chính xác.','Android 13 tách notification permission; media permissions khác theo version; Android 14 selected photos có partial access.','Process death trong lúc dialog mở, Activity recreation, multi-window, work profile và parental controls có thể làm callback hoặc capability khác kỳ vọng.','OEM có thể thêm permission manager riêng hoặc kill app; không hard-code text của system dialog.')
sec(16,'mistakes','Sai lầm thường gặp','Sai lầm: xin quyền trong onCreate, loop request sau deny, dùng shouldShowRationale để suy ra chắc chắn permanently denied, hoặc mở Settings ngay sau lần từ chối đầu.','Sai lầm: chỉ check SDK_INT mà quên targetSdk, manifest declaration, exported rules hoặc foreground service type.','Sai lầm: dùng READ_EXTERNAL_STORAGE cho mọi media flow, lưu URI mà không giữ persistable grant, hoặc giả định grant không đổi.','Sai lầm: gọi API nhạy cảm sau check mà không xử lý race revoke dẫn tới SecurityException.')
sec(17,'interview-basic','Câu hỏi phỏng vấn cơ bản','Permission normal và dangerous khác nhau thế nào; compileSdk, targetSdk, minSdk khác nhau ra sao; checkSelfPermission và request permission dùng khi nào.','Tại sao không nên xin quyền ngay app launch; Activity Result API có lợi gì; rationale dùng để làm gì; app xử lý deny thế nào.')
sec(18,'interview-deep','Câu hỏi xoáy sâu và câu hỏi bẫy','Câu xoáy: granted nhưng API vẫn fail vì sao; AppOps là gì; targetSdk behavior change ảnh hưởng thế nào; permission split và partial media access xử lý ra sao.','Câu bẫy: shouldShowRequestPermissionRationale false có luôn nghĩa permanently denied không; permission group có bảo đảm cùng grant không; check rồi dùng có tránh hoàn toàn SecurityException không.','Thiết kế capability layer cho camera, media, notification và location qua API 26 tới mới nhất như thế nào.')
sec(19,'experience-answer','Mẫu trả lời gắn với kinh nghiệm','Tôi thiết kế permission theo capability thay vì theo màn hình. UI chỉ request khi user thực hiện action; feature có fallback và luôn re-check trước khi dùng API nhạy cảm.','Tôi duy trì compatibility matrix theo OS và targetSdk, dùng Activity Result API, system picker khi phù hợp, theo dõi deny funnel và test revoke từ Settings.','Với Upzi, chỉ các chi tiết confirmed mới được kể như kinh nghiệm; phần permission architecture chưa kiểm tra phải ghi inferred hoặc proposed.')
sec(20,'practice','Bài tập thực hành','Xây màn profile có chọn ảnh từ Photo Picker và chụp ảnh bằng camera. Thiết kế flow không cần storage permission.','Xây notification onboarding với pre-prompt, runtime request, deny fallback và Settings CTA.','Viết capability matrix cho camera, notification, media, location trên API 26, 29, 31, 33, 34 và targetSdk hiện tại.','Viết test fake permission state và instrumentation test revoke trong Settings.')
sec(21,'scenario','Bài tập tình huống','User chọn đăng video, từ chối microphone nhưng cho camera. App nên cho quay video không tiếng, chọn file hoặc dừng flow thế nào.','User chỉ cấp approximate location nhưng sản phẩm xếp job theo khoảng cách. Thiết kế độ chính xác, thông báo và fallback.','User đã chọn 3 ảnh với selected photos rồi sửa bài muốn thêm ảnh thứ tư. Flow permission/picker phải xử lý ra sao.','App nâng targetSdk và notification suddenly không hiện. Lập kế hoạch điều tra manifest, channel, runtime permission và OEM settings.')
sec(22,'checklist','Checklist tự đánh giá','Tôi phân biệt permission declaration, runtime grant, AppOps và capability thực tế.','Tôi biết khi nào dùng system picker, camera intent, SAF hoặc runtime permission.','Tôi xử lý deny, rationale, Settings, revoke race, one-time grant, auto-reset và partial access.','Tôi có version matrix theo minSdk, targetSdk, OS và OEM; test không chỉ happy path.')
sec(23,'summary','Tóm tắt cần nhớ','Permission là state động và version-dependent, không phải boolean cố định trong ViewModel.','Xin quyền theo ngữ cảnh, chỉ xin capability tối thiểu và luôn có fallback.','targetSdk có thể thay behavior dù code không đổi; compatibility cần matrix và test thực tế.','System picker thường giảm permission surface; Activity Result API giúp lifecycle-safe; check rồi dùng vẫn phải xử lý failure.')
sec(24,'quiz-guide','Quiz có giải thích đáp án','Quiz tập trung vào reasoning: capability, lifecycle, targetSdk, fallback và privacy.','Mỗi đáp án phải giải thích vì sao phương án ít quyền hơn hoặc lifecycle-safe hơn.')
quiz=[]
def q(i,question,correct,explanation,*options): quiz.append({'id':f'q{i}','question':question,'options':[{'id':chr(97+j),'text':o} for j,o in enumerate(options)],'correctOptionIds':[chr(97+correct)],'explanation':explanation})
q(1,'targetSdk chủ yếu ảnh hưởng điều gì?',1,'targetSdk kích hoạt nhiều behavior change và policy compatibility của platform.','Thiết bị thấp nhất','Behavior compatibility','Phiên bản Kotlin','Dung lượng APK')
q(2,'Khi chỉ cần user chọn vài ảnh, ưu tiên gì?',2,'Photo Picker giảm nhu cầu storage/media permission.','READ_EXTERNAL_STORAGE','MANAGE_EXTERNAL_STORAGE','Photo Picker','Root access')
q(3,'shouldShowRequestPermissionRationale=false có chắc permanently denied không?',1,'False có thể là chưa từng hỏi, policy khác hoặc deny không hỏi lại; không đủ để kết luận chắc chắn.','Có','Không','Chỉ Android 10','Chỉ debug')
q(4,'Permission có thể thay đổi khi app đang chạy không?',0,'User hoặc hệ thống có thể revoke/auto-reset, nên phải re-check.','Có','Không','Chỉ sau reboot','Chỉ khi update app')
q(5,'Activity Result API có lợi ích chính nào?',2,'Nó tích hợp lifecycle và registry tốt hơn requestCode thủ công.','Tự cấp quyền','Bỏ manifest','Lifecycle-safe result handling','Không cần Activity')
q(6,'POST_NOTIFICATIONS runtime permission xuất hiện từ đâu?',1,'Android 13 giới thiệu runtime notification permission cho app target phù hợp.','Android 8','Android 13','Android 5','Android 12L')
q(7,'Granted approximate location nghĩa là gì?',2,'App có location nhưng độ chính xác bị giới hạn.','Không có location','Có exact location','Có location độ chính xác thấp hơn','Có background location')
q(8,'Check permission rồi gọi API có loại bỏ hoàn toàn SecurityException không?',1,'Quyền có thể bị revoke giữa check và use; cần xử lý tại boundary.','Có','Không','Chỉ camera','Chỉ emulator')
q(9,'Khi user deny lần đầu, UX tốt thường là gì?',0,'Giải thích giá trị và giữ fallback, không ép Settings ngay.','Giữ fallback và giải thích','Loop dialog','Đóng app','Mở Settings bắt buộc')
q(10,'compileSdk quyết định gì?',1,'Nó quyết định API symbols có thể biên dịch.','Thiết bị thấp nhất','API có thể compile','Behavior runtime duy nhất','Permission đã grant')
q(11,'One-time permission có đặc điểm gì?',3,'Grant chỉ có hiệu lực giới hạn theo phiên và có thể hết khi app không còn active.','Vĩnh viễn','Qua mọi reinstall','Không thể revoke','Hết hiệu lực theo phiên')
q(12,'Capability abstraction giúp gì?',2,'Nó gom policy version/permission và cho UI xử lý domain state có testability.','Bỏ test','Tự cấp quyền','Tập trung policy và fallback','Giảm minSdk')
lesson={'id':'e08','code':'E08','title':'Permission và Android Version Compatibility','summary':'Thiết kế permission theo capability, xử lý deny/revoke/partial access và duy trì compatibility matrix qua nhiều Android version và targetSdk.','estimatedMinutes':360,'sections':sections,'quiz':quiz}
lesson_path=DATA/'lessons'/'e'/'e08.json'; lesson_path.parent.mkdir(parents=True,exist_ok=True); lesson_path.write_text(json.dumps(lesson,ensure_ascii=False,separators=(',',':')))
required=['objectives','prerequisites','terminology','mechanism','purpose','problem','when-to-use','when-not-to-use','requirement','analysis','minimal-code','upzi-case','alternatives','tradeoffs','edge-cases','mistakes','interview-basic','interview-deep','experience-answer','practice','scenario','checklist','summary','quiz-guide']
ids=[s['id'] for s in sections]; paragraphs=[b['content'] for s in sections for b in s['blocks'] if b['type']=='paragraph']; codes=[b for s in sections for b in s['blocks'] if b['type']=='code']; assert ids==required and len(set(ids))==24 and len(paragraphs)>=55 and sum(map(len,paragraphs))>=10000 and len(codes)>=3 and len(quiz)>=10
text=lesson_path.read_text(); assert all(x in text for x in ['confirmed:','inferred:','proposed:','needs-confirmation:'])
catalog_path=DATA/'catalog.json'; catalog=json.loads(catalog_path.read_text())
for chapter in catalog['chapters']:
 for item in chapter['lessons']:
  if item['id']=='e08': assert item['status']=='planned'; item['status']='published'; item['estimatedMinutes']=360
catalog_path.write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
plan_path=DATA/'book-plan.json'; plan=json.loads(plan_path.read_text()); assert plan['current']=='e08'; plan['completed'].append('e08'); plan['current']='e09'; plan_path.write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
index_path=DATA/'search-index.json'; index=json.loads(index_path.read_text()); index=[x for x in index if x.get('lessonId')!='e08']; index.append({'lessonId':'e08','code':'E08','title':'Permission và Android Version Compatibility','keywords':['runtime permission','targetSdk','compileSdk','minSdk','Photo Picker','notification permission','approximate location','selected photos','Activity Result API','AppOps','compatibility matrix'],'headings':['Permission model','Capability design','Target SDK behavior','Media and photo picker','Notification permission','Location privacy','Version compatibility','Testing matrix']}); index_path.write_text(json.dumps(index,ensure_ascii=False,indent=2)+'\n')
report={'id':'e08','sections':24,'uniqueSectionIds':24,'exactSectionOrder':True,'paragraphs':len(paragraphs),'paragraphCharacters':sum(map(len,paragraphs)),'codeBlocks':len(codes),'quizQuestions':len(quiz),'quizAnswersValid':True,'truthfulnessLabelsPresent':True,'nextLesson':'e09'}; (ROOT/'validation-e08.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n'); print(json.dumps(report,ensure_ascii=False))