import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'android-learning'/'data'; sections=[]
def sec(i,id,title,*paras,codes=None):
 b=[{'type':'paragraph','content':p} for p in paras]
 for label,code in (codes or []): b.append({'type':'code','language':'kotlin','label':label,'content':code})
 sections.append({'id':id,'title':f'{i}. {title}','blocks':b})
sec(1,'objectives','Mục tiêu bài học','Hiểu process death là việc Android chấm dứt Linux process của ứng dụng để thu hồi tài nguyên, có thể không gọi onDestroy, trong khi task và saved state vẫn được hệ thống dùng để tái tạo UI khi user quay lại. Người học phải phân biệt process death, configuration change, finish, force-stop và app update.','Mục tiêu thực hành là thiết kế state restoration theo nhiều tầng: state có thể tái tạo từ repository, state nhỏ lưu bằng SavedStateHandle hoặc rememberSaveable, draft quan trọng persist bằng local storage, và long-running work được chuyển sang WorkManager hoặc service phù hợp.')
sec(2,'prerequisites','Kiến thức nền','Cần nắm Activity Lifecycle, Configuration Change, ViewModel, SavedStateHandle, rememberSaveable, Navigation Compose, Room hoặc DataStore, coroutine scope và Android task/back stack. ViewModel không phải durable storage.','Cần hiểu Android có thể giữ record của Activity và task ở system_server dù process app đã chết; khi user quay lại, framework tạo Application, Activity và graph mới rồi truyền saved state nếu có.')
sec(3,'terminology','Định nghĩa và chú giải thuật ngữ','Process death là chấm dứt toàn bộ process và memory heap. Low-memory kill thường xảy ra khi app ở background; force-stop là hành động mạnh hơn, ngăn nhận nhiều loại event cho tới khi user mở app lại.','Saved instance state là Bundle do framework và app cung cấp để khôi phục UI state nhỏ. SavedStateRegistry phối hợp provider/consumer. SavedStateHandle là abstraction cho ViewModel backed bởi saved-state registry.','Durable state là dữ liệu cần sống qua process death như draft, transaction hoặc job ID. Reconstructible state là dữ liệu có thể tải lại từ database, cache hoặc server. Ephemeral state là animation progress, object reference hoặc coroutine đang chạy.')
sec(4,'mechanism','Cơ chế hoạt động bên trong','Khi Activity chuyển nền, framework có thể gọi onSaveInstanceState và giữ Bundle liên kết với task entry. Sau đó process có thể bị kill mà không callback thêm. Khi task được mở lại, Activity mới nhận savedInstanceState và ViewModel mới được tạo với SavedStateHandle đã restore.','Compose SaveableStateRegistry lưu giá trị từ rememberSaveable nếu Saver có thể serialize chúng. Navigation cũng lưu back stack và destination state theo cơ chế saved state; điều này không bảo đảm repository, singleton, coroutine hay socket cũ còn tồn tại.','Process mới chạy Application.onCreate, DI graph và singleton đều tạo lại. Vì vậy mọi in-memory cache phải được coi là empty và initialization phải idempotent.',codes=[('SavedStateHandle state','''class SearchViewModel(
    private val savedStateHandle: SavedStateHandle
) : ViewModel() {
    val query = savedStateHandle.getStateFlow("query", "")
    fun updateQuery(value: String) { savedStateHandle["query"] = value }
}''')])
sec(5,'purpose','Mục đích của kỹ thuật','State restoration giúp user tiếp tục tác vụ sau khi app bị hệ thống thu hồi process, giảm cảm giác app reset ngẫu nhiên và tránh mất dữ liệu đang nhập.','Thiết kế đúng cũng làm kiến trúc rõ hơn: UI không phụ thuộc memory sống mãi, repository là source of truth, task dài hạn có owner độc lập với Activity và mọi entry point đều có thể bootstrap từ trạng thái rỗng.')
sec(6,'problem','Vấn đề kỹ thuật được giải quyết','Nếu chỉ dựa ViewModel hoặc singleton, app sẽ mất form, selected item, pending navigation, auth cache và upload progress sau process death. Nếu restore object cũ không validate, app có thể hiển thị dữ liệu stale hoặc mở resource không còn quyền.','Lưu quá nhiều vào Bundle lại gây TransactionTooLargeException, tăng startup cost và tạo coupling serialization. Bài toán không phải giữ mọi byte, mà là giữ identifier tối thiểu để tái tạo an toàn.')
sec(7,'when-to-use','Dấu hiệu cần dùng','Cần chiến lược process-death rõ khi app có form dài, draft, media upload, checkout, chat compose, deep link pending, multi-step onboarding, editor hoặc playback position.','Cũng cần khi app có nhiều process entry point như notification, broadcast, worker hoặc service; mọi entry point phải chịu được singleton chưa được warm-up.')
sec(8,'when-not-to-use','Khi không nên dùng','Không lưu bitmap, list lớn, response JSON, repository, coroutine, Context, socket connection hoặc access token vào SavedStateHandle hay rememberSaveable.','Không dùng process-death restoration thay database cho dữ liệu nghiệp vụ quan trọng. Không giả định callback save state luôn chạy trong crash, force-stop, battery removal hoặc kill -9.')
sec(9,'requirement','Yêu cầu sản phẩm cụ thể','Form tạo bài đăng phải phục hồi draft ID, text và media reference sau process death; file URI phải còn quyền đọc hoặc được copy vào app storage. Upload đang chạy phải tiếp tục hoặc resume qua worker, UI reconnect bằng uploadId.','Chat phải phục hồi conversationId, draft và reply target, nhưng message list được tải lại từ Room/server. Deep link pending phải có TTL và validate auth lại sau khi process mới khởi động.','Acceptance criteria gồm background app, dùng adb kill process, mở từ Recents, mở từ notification, đổi account, mất mạng, token hết hạn và version app thay đổi. Không được crash, duplicate submit hoặc hiển thị private data sai user.')
sec(10,'analysis','Phân tích dependency, error policy, lifecycle và resource limits','Dependency: UI layer giữ state trình bày nhỏ; ViewModel nhận SavedStateHandle; repository và local database giữ source of truth; WorkManager giữ durable work; auth manager đọc credential từ secure storage.','Error policy: saved ID invalid hoặc resource bị xóa phải fallback recoverable. Schema/version của saved state phải có default và migration đơn giản. Pending command hết TTL thì bỏ và ghi telemetry an toàn.','Lifecycle: không dựa onDestroy để persist. Draft nên được ghi incremental/debounce trong lúc user nhập hoặc ở lifecycle phù hợp. Collector và worker observation phải reconnect khi process mới tạo.','Resource limits: Bundle đi qua Binder và bị giới hạn; chỉ lưu primitive, enum, ID, timestamp và small Parcelable. Large text draft có thể lưu DB rồi SavedStateHandle giữ draftId.',codes=[('Persist draft ID','''class EditorViewModel(
    private val savedStateHandle: SavedStateHandle,
    private val drafts: DraftRepository
) : ViewModel() {
    private val draftId = savedStateHandle.get<String>("draftId")
        ?: drafts.createDraft().also { savedStateHandle["draftId"] = it }
}''')])
sec(11,'minimal-code','Ví dụ code tối giản','Route chỉ truyền ID; ViewModel lấy ID từ SavedStateHandle rồi tải dữ liệu từ repository. rememberSaveable chỉ dùng cho state UI nhỏ không cần chia sẻ với ViewModel.','Activity hoặc NavHost không nên tự giữ object domain qua process death. UI render loading trong lúc source of truth được rehydrate.',codes=[('rememberSaveable','''@Composable
fun EditorScreen(viewModel: EditorViewModel) {
    var selectedTab by rememberSaveable { mutableIntStateOf(0) }
    val state by viewModel.state.collectAsStateWithLifecycle()
    EditorContent(state, selectedTab, onTabChange = { selectedTab = it })
}''')])
sec(12,'upzi-case','Ví dụ thực tế Upzi','confirmed: Upzi dùng single-activity Compose, ViewModel, StateFlow, Paging, chat socket, deep link và media flow; các thành phần này đều cần khởi tạo lại an toàn sau process death.','inferred: app có thể đã dùng SavedStateHandle cho route ID và local cache cho chat, nhưng chưa xác nhận draft persistence, upload resume, pending deep-link TTL hay test process death. proposed: lập restoration matrix cho feed, chat, opportunity, form và media; chỉ lưu key nhỏ, dùng Room/WorkManager cho state bền và test kill process. needs-confirmation: cần đối chiếu code production trước khi dùng như kinh nghiệm đã triển khai.')
sec(13,'alternatives','Phương án thay thế','SavedStateHandle và rememberSaveable phù hợp state nhỏ; Room hoặc DataStore phù hợp durable state; file storage phù hợp media draft; WorkManager phù hợp công việc cần hoàn thành sau process death.','Server-side draft có thể phù hợp multi-device nhưng tăng network và conflict handling. Không lưu gì và tải lại hoàn toàn phù hợp màn read-only nếu UX chấp nhận được.')
sec(14,'tradeoffs','Lý do lựa chọn và trade-off','Saved state nhanh và tích hợp lifecycle nhưng size nhỏ, serialization giới hạn và không bảo đảm trong mọi kiểu kill. Local DB bền, query được và versionable nhưng thêm IO, schema và cleanup.','Persist draft liên tục giảm mất dữ liệu nhưng tăng write amplification; debounce giảm IO nhưng có cửa sổ mất dữ liệu. WorkManager bền nhưng không dành cho tác vụ cần tương tác realtime từng frame.')
sec(15,'edge-cases','Edge cases','App update có thể thay route schema hoặc Parcelable class khiến saved state cũ không decode. Ưu tiên primitive và version key; fallback nếu dữ liệu không tương thích.','User logout hoặc đổi account sau khi state được lưu: mọi restored ID phải scope theo account và authorization lại. Không tự mở chat private chỉ vì Bundle có conversationId.','Persisted URI permission có thể mất nếu chỉ giữ URI tạm. File draft có thể bị cleanup. Worker hoàn thành khi UI chưa mở; process mới phải đọc result từ database.','Navigation back stack restore có thể mở destination sâu trước khi auth bootstrap xong; cần root coordinator quyết định graph và pending destination.',codes=[('WorkManager observation','''val workInfo = workManager.getWorkInfoByIdFlow(uploadWorkId)
    .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), null)''')])
sec(16,'mistakes','Sai lầm thường gặp','Lỗi phổ biến: tin ViewModel sống mãi, lưu object lớn vào Bundle, persist trong onDestroy, dùng singleton làm source of truth, restore token hoặc permission decision cũ, và submit lại request khi process mới tạo.','Một lỗi khác là test rotation rồi kết luận process death đã được xử lý. Rotation giữ process và ViewModel; process death tạo toàn bộ graph mới.','Không nên dùng Parcelable phức tạp có dependency vào class implementation dài hạn; route và saved state nên tối giản, có default và validate.')
sec(17,'interview-basic','Câu hỏi phỏng vấn cơ bản','Câu hỏi nền: process death là gì; khác configuration change thế nào; ViewModel còn không; onDestroy có chắc chạy không; onSaveInstanceState dùng khi nào; SavedStateHandle và Room khác gì.','Mẫu trả lời tốt phân loại state theo ephemeral, reconstructible và durable; mô tả bootstrap process mới và giới hạn Bundle.')
sec(18,'interview-deep','Câu hỏi xoáy sâu và câu hỏi bẫy','Câu xoáy: process chết khi upload đang chạy xử lý sao; duplicate submit ngăn thế nào; saved-state schema đổi qua app update; deep link pending với auth; URI permission survive không; WorkManager result reconnect thế nào.','Câu bẫy: onSaveInstanceState có luôn gọi không; force-stop có giống low-memory kill không; rememberSaveable có thay database không; ViewModel có survive process death không; Recents card có nghĩa process còn sống không.')
sec(19,'experience-answer','Mẫu trả lời gắn với kinh nghiệm','Trong app Compose tôi không coi ViewModel là persistence. Tôi lưu route ID và UI state nhỏ trong SavedStateHandle hoặc rememberSaveable, tải domain data lại từ repository, persist draft quan trọng vào Room và giao upload bền cho WorkManager.','Với Upzi, confirmed là có chat, deep link, Paging và media flow. Những chi tiết process-death test, draft DB hoặc upload resume phải nói là inferred hoặc proposed nếu chưa kiểm tra.')
sec(20,'practice','Bài tập thực hành','Tạo editor có draftId, text, image URI và upload worker. Kill process bằng adb khi app background rồi mở từ Recents; kiểm tra state và không duplicate upload.','Tạo deep link pending qua login, lưu command tối thiểu có TTL, kill process ở màn login rồi hoàn tất flow.','Viết test cho SavedStateHandle, repository rehydrate và instrumentation scenario process recreation; log process ID để chứng minh process mới.')
sec(21,'scenario','Bài tập tình huống','User submit job application, server nhận thành công nhưng process chết trước response. Thiết kế idempotency key và reconciliation để không gửi trùng.','Chat draft chứa ảnh từ picker với URI tạm; process chết qua đêm. Thiết kế copy file, cleanup và permission policy.','App update đổi route opportunity/{id} sang typed route mới. Xử lý saved back stack cũ và fallback ra sao.')
sec(22,'checklist','Checklist tự đánh giá','Tôi phân biệt process death, rotation, finish, force-stop và crash; biết ViewModel, singleton và coroutine đều mất khi process chết.','Tôi chỉ lưu state nhỏ trong Bundle, giữ durable data ở storage thích hợp, validate auth/account và có idempotency cho request.','Tôi test bằng process kill thật, mở từ Recents và notification, kiểm tra app update/schema, URI permission và worker reconnect; biết chi tiết Upzi nào đã xác nhận.')
sec(23,'summary','Tóm tắt cần nhớ','Process death xóa toàn bộ memory nhưng task và saved state có thể giúp framework tái tạo UI. onDestroy không phải điểm persist đáng tin cậy.','SavedStateHandle và rememberSaveable giữ key nhỏ; repository, Room, DataStore, file storage và WorkManager mới là nền tảng cho dữ liệu hoặc công việc bền.','Khôi phục luôn phải validate lại resource, auth, account, TTL và schema; tránh duplicate side effect bằng idempotency.')
sec(24,'quiz-guide','Quiz có giải thích đáp án','Làm quiz sau khi tự vẽ timeline background, onSaveInstanceState, process kill và process recreation.','Mỗi câu cần nêu state owner, durability, size limit, validation và fallback.')
quiz=[]
def q(i,question,correct,explanation,*options): quiz.append({'id':f'q{i}','question':question,'options':[{'id':chr(97+j),'text':o} for j,o in enumerate(options)],'correctOptionIds':[chr(97+correct)],'explanation':explanation})
q(1,'ViewModel có sống qua process death không?',1,'ViewModel chỉ sống qua configuration change trong cùng process.','Có','Không','Chỉ khi dùng Hilt','Chỉ Compose')
q(2,'onDestroy có chắc được gọi trước low-memory kill không?',1,'Hệ thống có thể kill process mà không callback thêm.','Có','Không','Chỉ debug','Chỉ service')
q(3,'Nên lưu gì trong SavedStateHandle?',0,'Identifier và UI state nhỏ phù hợp giới hạn Bundle.','ID nhỏ','Bitmap','Repository','Socket')
q(4,'Draft quan trọng nên đặt ở đâu?',2,'Draft bền cần local hoặc server persistence.','remember','ViewModel','Room hoặc storage bền','GlobalScope')
q(5,'Process mới khởi động lại điều gì?',3,'Application, DI graph, singleton và Activity đều được tạo mới.','Chỉ Compose','Chỉ Activity','Chỉ ViewModel','Toàn bộ app graph trong process')
q(6,'Vì sao cần idempotency key khi submit?',0,'Process có thể chết sau khi server xử lý nhưng trước khi app nhận response.','Tránh duplicate request','Tăng animation','Giảm Bundle','Giữ Context')
q(7,'rememberSaveable có thay Room không?',1,'Nó chỉ dành state nhỏ và không bảo đảm durable như database.','Có','Không','Chỉ tablet','Chỉ offline')
q(8,'WorkManager phù hợp trường hợp nào?',2,'Công việc cần tiếp tục hoặc retry sau process death.','Animation','Scroll state','Upload bền','Composable state')
q(9,'Restored conversationId cần làm gì?',3,'Phải kiểm tra account và quyền truy cập lại.','Mở ngay','Log token','Tin Bundle','Validate auth và authorization')
q(10,'Rotation test có đủ cho process death không?',1,'Rotation giữ process và ViewModel nên không đại diện process death.','Đủ','Không đủ','Chỉ API 26','Chỉ emulator')
q(11,'URI từ picker có thể gặp vấn đề gì?',0,'Quyền tạm có thể mất nếu không persist hoặc copy file.','Mất quyền đọc','Tự thành bitmap','Không đổi','Tự upload')
q(12,'State restoration tốt ưu tiên điều gì?',2,'Lưu key tối thiểu rồi tái tạo source of truth an toàn.','Lưu toàn object','Giữ singleton','Key tối thiểu và rehydrate','Dựa onDestroy')
lesson={'id':'e03','code':'E03','title':'Process Death và State Restoration','summary':'Thiết kế phục hồi state an toàn sau khi Android kill process bằng SavedStateHandle, rememberSaveable, durable storage, WorkManager và idempotency.','estimatedMinutes':360,'sections':sections,'quiz':quiz}
lesson_path=DATA/'lessons'/'e'/'e03.json'; lesson_path.parent.mkdir(parents=True,exist_ok=True); lesson_path.write_text(json.dumps(lesson,ensure_ascii=False,separators=(',',':')))
required=['objectives','prerequisites','terminology','mechanism','purpose','problem','when-to-use','when-not-to-use','requirement','analysis','minimal-code','upzi-case','alternatives','tradeoffs','edge-cases','mistakes','interview-basic','interview-deep','experience-answer','practice','scenario','checklist','summary','quiz-guide']
ids=[s['id'] for s in sections]; ps=[b['content'] for s in sections for b in s['blocks'] if b['type']=='paragraph']; cs=[b for s in sections for b in s['blocks'] if b['type']=='code']; assert ids==required and len(set(ids))==24 and len(ps)>=40 and sum(map(len,ps))>=9000 and len(cs)>=4 and len(quiz)>=10; assert all(x in lesson_path.read_text() for x in ['confirmed:','inferred:','proposed:','needs-confirmation:'])
catalog_path=DATA/'catalog.json'; catalog=json.loads(catalog_path.read_text())
for chapter in catalog['chapters']:
 for item in chapter['lessons']:
  if item['id']=='e03': assert item['status']=='planned'; item['status']='published'; item['estimatedMinutes']=360
catalog_path.write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
plan_path=DATA/'book-plan.json'; plan=json.loads(plan_path.read_text()); assert plan['current']=='e03'; plan['completed'].append('e03'); plan['current']='e04'; plan_path.write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
index_path=DATA/'search-index.json'; index=json.loads(index_path.read_text()); index=[x for x in index if x.get('lessonId')!='e03']; index.append({'lessonId':'e03','code':'E03','title':'Process Death và State Restoration','keywords':['process death','state restoration','SavedStateHandle','rememberSaveable','SavedStateRegistry','Room','WorkManager','idempotency','task restoration','TransactionTooLargeException'],'headings':['Process death mechanism','State durability','Saved state limits','Draft persistence','WorkManager recovery','Idempotent submit','Navigation restoration','Upzi case study']}); index_path.write_text(json.dumps(index,ensure_ascii=False,indent=2)+'\n')
report={'id':'e03','sections':24,'uniqueSectionIds':24,'exactSectionOrder':True,'paragraphs':len(ps),'paragraphCharacters':sum(map(len,ps)),'codeBlocks':len(cs),'quizQuestions':len(quiz),'quizAnswersValid':True,'truthfulnessLabelsPresent':True,'nextLesson':'e04'}; (ROOT/'validation-e03.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n'); print(json.dumps(report,ensure_ascii=False))