import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'android-learning'/'data'; sections=[]
def sec(i,id,title,*paras,codes=None):
 b=[{'type':'paragraph','content':p} for p in paras]
 for label,code in (codes or []): b.append({'type':'code','language':'kotlin','label':label,'content':code})
 sections.append({'id':id,'title':f'{i}. {title}','blocks':b})
sec(1,'objectives','Mục tiêu bài học','Hiểu WorkManager là API lập lịch công việc trì hoãn, có ràng buộc và cần bảo đảm thực thi ngay cả khi app rời foreground hoặc process bị kill. Phân biệt rõ WorkManager với coroutine, Service, foreground service, AlarmManager và job chạy tức thời trong ViewModel.','Thiết kế worker idempotent, có retry/backoff, constraint, cancellation, progress, chaining, unique work và khả năng phục hồi sau process death. Biết khi nào cần foreground execution bên trong Worker cho tác vụ dài và user-visible.')
sec(2,'prerequisites','Kiến thức nền','Cần nắm coroutine, Flow, process death, Service/Foreground Service, Room, repository pattern, notification và lifecycle. WorkManager quản lý lịch và độ bền của work; nó không thay thế kiến trúc dữ liệu hoặc transaction phía server.','Guaranteed execution nghĩa hệ thống sẽ cố thực hiện khi constraint thỏa; không có nghĩa chạy chính xác tại thời điểm tuyệt đối hoặc không bao giờ bị trì hoãn.')
sec(3,'terminology','Định nghĩa và chú giải thuật ngữ','WorkRequest mô tả công việc. OneTimeWorkRequest dùng một lần; PeriodicWorkRequest lặp theo khoảng tối thiểu và có tính inexact. Worker, CoroutineWorker và ListenableWorker là các kiểu thực thi.','Constraints gồm network, charging, battery-not-low, storage-not-low và device idle tùy phiên bản. Backoff policy điều khiển retry theo linear hoặc exponential.','Unique work ngăn nhiều chuỗi cùng mục đích bằng name và ExistingWorkPolicy. WorkInfo có state ENQUEUED, RUNNING, SUCCEEDED, FAILED, BLOCKED, CANCELLED cùng progress và output Data.','Expedited work dành cho công việc khẩn cấp, chịu quota và fallback policy. Foreground Worker hiển thị notification khi công việc dài cần user awareness.')
sec(4,'mechanism','Cơ chế hoạt động bên trong','WorkManager lưu WorkSpec và dependency graph vào database nội bộ, chọn scheduler phù hợp theo API level và trạng thái app. Khi constraint thỏa, scheduler kích hoạt processor chạy Worker trong process ứng dụng.','Nếu process chết, metadata còn trong database và work có thể được chạy lại. Vì vậy doWork có thể được gọi nhiều lần; side effect phải idempotent, transaction-safe và không dựa vào biến memory.','Result.success hoàn tất, Result.failure kết thúc vĩnh viễn cho request đó, Result.retry đưa về ENQUEUED và áp dụng backoff. Cancellation là cooperative: CoroutineWorker nhận cancellation nhưng code blocking hoặc SDK không hỗ trợ cancel vẫn có thể tiếp tục.',codes=[('CoroutineWorker cơ bản','''class SyncWorker(
    appContext: Context,
    params: WorkerParameters,
    private val repository: SyncRepository
) : CoroutineWorker(appContext, params) {
    override suspend fun doWork(): Result = try {
        repository.sync()
        Result.success()
    } catch (e: IOException) {
        Result.retry()
    } catch (e: AuthenticationException) {
        Result.failure()
    }
}''')])
sec(5,'purpose','Mục đích của kỹ thuật','WorkManager giải quyết deferred durable work như đồng bộ dữ liệu, upload, log batching, cleanup, backup và retry sau mất mạng. Nó cho phép hệ thống tối ưu pin bằng cách gom việc và chờ constraint phù hợp.','Nó tách lifetime của công việc khỏi Activity, ViewModel và process hiện tại, đồng thời cung cấp observability qua WorkInfo.')
sec(6,'problem','Vấn đề kỹ thuật được giải quyết','Nếu launch coroutine từ UI cho upload, rotation có thể còn nhờ ViewModel nhưng process death sẽ mất job. Nếu dùng foreground service cho mọi retry, app tiêu pin và vướng policy. Nếu dùng AlarmManager cho sync, developer phải tự xử lý persistence, constraint và backoff.','WorkManager chuẩn hóa persistence, scheduling, retry, dependency graph và cancellation nhưng không tự giải quyết duplicate server mutation, auth refresh hoặc data consistency.')
sec(7,'when-to-use','Dấu hiệu cần dùng','Dùng khi task có thể trì hoãn, phải tiếp tục sau process death, cần constraint hoặc retry, và kết quả không cần trả ngay trong interaction hiện tại. Ví dụ upload draft, sync offline action, refresh cache, send analytics batch.','Dùng unique work khi cùng một mục đích không nên enqueue nhiều bản, hoặc chain khi bước sau phụ thuộc output và thành công của bước trước.')
sec(8,'when-not-to-use','Khi không nên dùng','Không dùng cho công việc phải chạy ngay và chỉ sống cùng màn hình; dùng coroutine trong scope phù hợp. Không dùng cho thời điểm chính xác như alarm clock; dùng AlarmManager theo policy.','Không dùng PeriodicWork cho realtime polling vài phút, socket hoặc location liên tục. Không truyền object lớn, bitmap, token nhạy cảm hoặc repository qua Data; chỉ truyền ID/key nhỏ và đọc dữ liệu từ source of truth.')
sec(9,'requirement','Yêu cầu sản phẩm cụ thể','Upload video phải tiếp tục sau app background/process recreation, tạm dừng khi mất mạng, retry có backoff, không tạo file server trùng và hiển thị trạng thái từ local database. Người dùng có thể cancel và retry thủ công.','Offline apply/save action phải được serialize theo entity hoặc user, xử lý logout và token hết hạn, không gửi dữ liệu account cũ. Sync feed chạy khi network có và không làm thức thiết bị vô ích.','Acceptance criteria gồm process kill, reboot, network flap, constraint change, duplicate enqueue, force-stop, logout/login, server 409, timeout, cancellation và app update giữa chừng.')
sec(10,'analysis','Phân tích dependency, error policy, lifecycle và resource limits','Dependency: Worker nhận repository qua WorkerFactory hoặc DI; inputData chỉ chứa stable ID. Local DB là source of truth cho status/progress; server mutation dùng idempotency key. UI observe WorkInfo hoặc DB, không giữ callback trực tiếp tới Worker.','Error policy: phân loại retryable như timeout, 5xx, network; permanent như malformed payload, revoked permission; auth error thường cần refresh hoặc đánh dấu blocked chứ không retry vô hạn. Giới hạn attempt và lưu last error cho support.','Lifecycle: work không phụ thuộc Activity. Cancellation phải lan tới HTTP call, stream copy và child coroutine. Cleanup temp file trong finally nhưng không xóa artifact cần resume.','Resource limits: WorkManager Data có giới hạn nhỏ; progress update quá dày gây IO. Periodic work là inexact. Tác vụ dài cần foreground info và notification phù hợp; upload chunk để resume và kiểm soát memory.',codes=[('Unique upload','''val request = OneTimeWorkRequestBuilder<UploadWorker>()
    .setInputData(workDataOf("draftId" to draftId))
    .setConstraints(Constraints(requiredNetworkType = NetworkType.CONNECTED))
    .setBackoffCriteria(BackoffPolicy.EXPONENTIAL, 30, TimeUnit.SECONDS)
    .build()
workManager.enqueueUniqueWork("upload:$draftId", ExistingWorkPolicy.KEEP, request)''')])
sec(11,'minimal-code','Ví dụ code tối giản','Worker đọc draftId, tải record từ Room, đánh dấu RUNNING trong transaction, upload với idempotency key, cập nhật progress có throttle và commit SUCCEEDED khi server xác nhận.','Không coi runAttemptCount là business retry count duy nhất; app update hoặc replace work có thể tạo request mới. Business state nên nằm trong DB.',codes=[('Progress và foreground','''override suspend fun doWork(): Result {
    val draftId = inputData.getString("draftId") ?: return Result.failure()
    setForeground(createForegroundInfo(draftId, 0))
    return repository.uploadDraft(draftId) { percent ->
        if (percent % 5 == 0) setProgress(workDataOf("percent" to percent))
    }.fold(
        onSuccess = { Result.success() },
        onFailure = { if (it.isRetryable) Result.retry() else Result.failure() }
    )
}''')])
sec(12,'upzi-case','Ví dụ thực tế Upzi','confirmed: Upzi có WorkManager trong stack Android và có các flow upload/media, feed/cache, chat/offline state có thể hưởng lợi từ durable background work.','inferred: có thể WorkManager đang dùng cho upload hoặc sync nhưng chưa xác nhận worker names, policies, constraints, retry taxonomy hay foreground notification. proposed: chuẩn hóa unique work theo draftId, Room status, idempotency key, chunk resume, auth/account guard và test process kill. needs-confirmation: cần kiểm tra catalog worker hiện tại, custom WorkerFactory/Koin integration và backend idempotency trước khi kể là đã triển khai.')
sec(13,'alternatives','Phương án thay thế','Coroutine trong viewModelScope cho immediate UI work; foreground service cho tác vụ dài user-initiated cần chạy ngay và hiển thị liên tục; AlarmManager cho thời điểm chính xác; Media3 cho playback; DownloadManager cho tải file phù hợp use case.','Server-side job phù hợp khi task nặng, cần chạy độc lập thiết bị hoặc yêu cầu reliability cao hơn mạng di động. App chỉ enqueue request và poll hoặc nhận push trạng thái.')
sec(14,'tradeoffs','Lý do lựa chọn và trade-off','WorkManager đơn giản hóa persistence và constraints nhưng thời điểm chạy không chính xác, có scheduler latency và database overhead. Foreground service phản hồi ngay hơn nhưng chịu notification, policy và pin.','Unique KEEP tránh duplicate nhưng có thể giữ request cấu hình cũ; REPLACE cập nhật mới nhưng cancel work đang chạy; APPEND tạo chain có nguy cơ chain dài hoặc bị block sau failure.','Room source of truth tăng code nhưng làm UI nhất quán qua process death. WorkInfo nhanh cho trạng thái scheduler nhưng không đủ domain state lâu dài.')
sec(15,'edge-cases','Edge cases','Force-stop đưa app vào stopped state; work không chạy lại cho tới khi user mở app. Reboot thường được WorkManager phục hồi nhưng phụ thuộc component enablement và hệ thống.','Constraint có thể mất giữa lúc RUNNING; behavior phụ thuộc scheduler và phiên bản, vì vậy worker vẫn phải xử lý network error. Expedited quota hết có thể fallback hoặc fail theo OutOfQuotaPolicy.','Unique work với APPEND_OR_REPLACE, failed prerequisite, cancelled parent và app update đổi worker class có thể tạo chain khó phục hồi. Stable worker contract và migration strategy là cần thiết.','URI permission có thể mất; media từ picker cần persist hoặc copy vào app storage trước deferred upload. Logout khi worker chạy phải kiểm tra owner trước từng mutation.',codes=[('Observe WorkInfo','''@Composable
fun UploadStatus(id: UUID, workManager: WorkManager) {
    val info by workManager.getWorkInfoByIdFlow(id)
        .collectAsStateWithLifecycle(initialValue = null)
    Text(info?.state?.name ?: "UNKNOWN")
}''')])
sec(16,'mistakes','Sai lầm thường gặp','Lỗi phổ biến: enqueue mỗi recomposition, dùng random unique name, retry mọi exception, không backoff, truyền JSON lớn, không idempotent, update progress mỗi byte và assume worker chỉ chạy một lần.','Dùng PeriodicWork như timer chính xác, giữ Context UI trong Worker, thực hiện network blocking không cancel được, hoặc chỉ observe WorkInfo mà không persist domain status.','Không xử lý logout/account switch, force-stop, server duplicate và app version migration là lỗi production thường gặp.')
sec(17,'interview-basic','Câu hỏi phỏng vấn cơ bản','Câu hỏi nền: WorkManager dùng khi nào; khác Service; Result.retry khác failure; constraint là gì; unique work; periodic work; process death; input/output Data; foreground worker.','Mẫu trả lời tốt nhấn mạnh deferred guaranteed work, persistence, scheduler, idempotency và inexact timing.')
sec(18,'interview-deep','Câu hỏi xoáy sâu và câu hỏi bẫy','Câu xoáy: doWork có thể chạy mấy lần; force-stop ảnh hưởng gì; constraint mất giữa chừng; retry taxonomy; server idempotency; chain failure; expedited quota; cancellation của OkHttp.','Câu bẫy: WorkManager có chạy đúng 9:00 không; worker có process riêng không; PeriodicWork tối thiểu có nghĩa luôn đúng chu kỳ không; Result.success có nghĩa server transaction chắc chắn chưa duplicate không.')
sec(19,'experience-answer','Mẫu trả lời gắn với kinh nghiệm','Tôi dùng WorkManager khi công việc cần tồn tại qua process death và có thể trì hoãn. Tôi lưu domain status trong Room, enqueue unique work theo entity, truyền ID nhỏ, dùng constraint mạng, retry có backoff và idempotency key phía server.','Với Upzi, chỉ khẳng định confirmed là stack có WorkManager và có các flow phù hợp. Chi tiết worker production phải gắn nhãn inferred, proposed hoặc needs-confirmation nếu chưa đọc code/backend contract.')
sec(20,'practice','Bài tập thực hành','Xây upload worker có Room entity, unique name, network constraint, progress throttle, cancel, retry và foreground notification. Mô phỏng process kill và mở lại UI.','Tạo sync chain: refresh token nếu cần, upload pending actions, pull remote changes, cleanup. Quy định failure của từng bước và tránh chain bị block vĩnh viễn.','Viết unit test CoroutineWorker với fake repository và integration test WorkManagerTestInitHelper, constraint, retry, unique policy và cancellation.')
sec(21,'scenario','Bài tập tình huống','User chọn video 500 MB rồi thoát app. Thiết kế copy URI, chunk upload, DB schema, unique work, notification, retry và resume sau reboot.','Có 20 offline apply action, user logout rồi login account khác. Quyết định cancel, quarantine hay gửi; mô tả guard theo ownerId và auth generation.','Server trả 200 nhưng app chết trước khi lưu success. Lần chạy sau tránh tạo duplicate bằng idempotency key và reconcile server state thế nào.')
sec(22,'checklist','Checklist tự đánh giá','Tôi phân biệt WorkManager, coroutine, service, foreground service và AlarmManager; hiểu persistence, constraint, retry, unique work, chain và periodic inexact.','Worker của tôi idempotent, input nhỏ, dependency inject đúng, progress throttle, cancellation cooperative, auth/account guard và DB source of truth.','Tôi test process kill, reboot, force-stop, network flap, duplicate enqueue, app update và backend duplicate.')
sec(23,'summary','Tóm tắt cần nhớ','WorkManager dành cho deferred durable work, không phải realtime hay exact alarm. Scheduler và database giúp work sống qua process death nhưng doWork có thể chạy lại.','Thiết kế production cần idempotency, retry taxonomy, backoff, unique policy, local source of truth, cancellation và giới hạn resource.','Foreground Worker chỉ dùng khi tác vụ dài cần user-visible execution; WorkManager không miễn trừ notification và platform policy.')
sec(24,'quiz-guide','Quiz có giải thích đáp án','Làm quiz bằng cách luôn hỏi: task có cần chạy ngay không, có cần survive process death không, constraint nào, side effect có idempotent không và state nằm ở đâu.','Không chọn WorkManager chỉ vì từ background; chọn theo durability, timing và user visibility.')
quiz=[]
def q(i,question,correct,explanation,*options): quiz.append({'id':f'q{i}','question':question,'options':[{'id':chr(97+j),'text':o} for j,o in enumerate(options)],'correctOptionIds':[chr(97+correct)],'explanation':explanation})
q(1,'WorkManager phù hợp nhất với tác vụ nào?',1,'Nó dành cho deferred durable work cần survive process death.','Animation UI','Upload có thể trì hoãn và retry','Socket realtime','Exact alarm')
q(2,'Worker có thể chạy nhiều lần không?',0,'Process death hoặc retry có thể làm doWork chạy lại.','Có','Không','Chỉ debug','Chỉ periodic')
q(3,'Result.retry dùng khi nào?',2,'Dùng cho lỗi tạm thời có khả năng thành công ở lần sau.','Payload sai vĩnh viễn','User bị khóa','Network timeout','Schema không hỗ trợ')
q(4,'Tại sao cần idempotency key?',1,'Để retry không tạo side effect server trùng.','Tăng tốc UI','Tránh mutation trùng','Giảm APK','Thay auth')
q(5,'Input Data nên chứa gì?',0,'Chỉ nên chứa ID hoặc scalar nhỏ.','draftId nhỏ','Bitmap','Repository','File 100MB')
q(6,'PeriodicWork có chạy chính xác từng chu kỳ không?',1,'Periodic work là inexact và chịu tối ưu hệ thống.','Có','Không','Chỉ khi charging','Chỉ emulator')
q(7,'Unique KEEP có ý nghĩa gì?',2,'Giữ work hiện có và bỏ request mới cùng tên.','Cancel cũ','Append mới','Giữ cũ, bỏ mới','Chạy song song')
q(8,'Force-stop ảnh hưởng gì?',0,'App vào stopped state cho tới khi user mở lại.','Work tạm ngừng tới khi user mở app','Work chạy ngay','Xóa database','Không ảnh hưởng')
q(9,'Foreground Worker cần gì?',3,'Tác vụ dài user-visible cần foreground info và notification phù hợp.','Activity','Wake lock luôn luôn','Exact alarm','ForegroundInfo/notification')
q(10,'Source of truth tốt cho upload domain state là gì?',1,'Room giữ trạng thái bền qua process death và UI recreation.','WorkInfo duy nhất','Room/entity','Composable local state','Notification text')
q(11,'Constraint network có loại bỏ mọi lỗi mạng không?',0,'Mạng có thể mất khi worker đang chạy; worker vẫn phải xử lý lỗi.','Không','Có','Chỉ API 35','Chỉ Wi-Fi')
q(12,'WorkManager thay exact alarm được không?',2,'Nó không bảo đảm thời điểm chính xác.','Luôn được','Chỉ periodic','Không, dùng AlarmManager khi thật sự cần exact','Chỉ foreground')
lesson={'id':'e06','code':'E06','title':'WorkManager','summary':'Thiết kế deferred durable work với constraint, retry, backoff, unique work, chaining, foreground execution, idempotency và state bền qua process death.','estimatedMinutes':360,'sections':sections,'quiz':quiz}
p=DATA/'lessons'/'e'/'e06.json'; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(lesson,ensure_ascii=False,separators=(',',':')))
required=['objectives','prerequisites','terminology','mechanism','purpose','problem','when-to-use','when-not-to-use','requirement','analysis','minimal-code','upzi-case','alternatives','tradeoffs','edge-cases','mistakes','interview-basic','interview-deep','experience-answer','practice','scenario','checklist','summary','quiz-guide']
ids=[s['id'] for s in sections]; paragraphs=[b['content'] for s in sections for b in s['blocks'] if b['type']=='paragraph']; codes=[b for s in sections for b in s['blocks'] if b['type']=='code']; assert ids==required and len(set(ids))==24 and len(paragraphs)>=50 and sum(map(len,paragraphs))>=10000 and len(codes)>=4 and len(quiz)>=10
text=p.read_text(); assert all(x in text for x in ['confirmed:','inferred:','proposed:','needs-confirmation:'])
catalog_path=DATA/'catalog.json'; catalog=json.loads(catalog_path.read_text())
for c in catalog['chapters']:
 for item in c['lessons']:
  if item['id']=='e06': assert item['status']=='planned'; item['status']='published'; item['estimatedMinutes']=360
catalog_path.write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
plan_path=DATA/'book-plan.json'; plan=json.loads(plan_path.read_text()); assert plan['current']=='e06'; plan['completed'].append('e06'); plan['current']='e07'; plan_path.write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
idx_path=DATA/'search-index.json'; idx=json.loads(idx_path.read_text()); idx=[x for x in idx if x.get('lessonId')!='e06']; idx.append({'lessonId':'e06','code':'E06','title':'WorkManager','keywords':['WorkManager','CoroutineWorker','constraints','unique work','retry','backoff','periodic work','expedited work','foreground worker','process death','idempotency','chaining'],'headings':['Scheduler mechanism','Constraints and backoff','Unique work','Foreground worker','Idempotency','Room source of truth','Cancellation','Testing WorkManager']}); idx_path.write_text(json.dumps(idx,ensure_ascii=False,indent=2)+'\n')
report={'id':'e06','sections':24,'uniqueSectionIds':24,'exactSectionOrder':True,'paragraphs':len(paragraphs),'paragraphCharacters':sum(map(len,paragraphs)),'codeBlocks':len(codes),'quizQuestions':len(quiz),'quizAnswersValid':True,'truthfulnessLabelsPresent':True,'nextLesson':'e07'}; (ROOT/'validation-e06.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n'); print(json.dumps(report,ensure_ascii=False))