import json
from pathlib import Path
R=Path(__file__).resolve().parents[1]; D=R/'android-learning'/'data'
def p(x): return {'type':'paragraph','content':x}
def c(l,x): return {'type':'code','language':'kotlin','label':l,'content':x}
def s(i,k,t,*xs,codes=()): return {'id':k,'title':f'{i}. {t}','blocks':[p(x) for x in xs]+[c(*z) for z in codes]}
S=[]
S.append(s(1,'objectives','Mục tiêu bài học','Hiểu MVVM trên Android như cách phân chia trách nhiệm và luồng dữ liệu giữa View, ViewModel và Model, không chỉ là quy ước đặt tên lớp.','Thiết kế ViewModel làm screen-level state holder, nhận action từ UI, gọi dependency phù hợp, phát immutable UiState và xử lý effect theo contract rõ ràng.','Phân tích lifecycle, process death, cancellation, retry, concurrent action và testing trong một triển khai MVVM production.'))
S.append(s(2,'prerequisites','Kiến thức nền','Cần nắm Separation of Concerns, dependency direction, state ownership, coroutine, Flow, StateFlow, SavedStateHandle, Compose state hoisting, repository và use case.','Cần phân biệt configuration change với process death: AndroidX ViewModel thường sống qua configuration change nhưng không phải persistent storage.'))
S.append(s(3,'terminology','Định nghĩa và chú giải thuật ngữ','View là Activity, Fragment hoặc composable chịu trách nhiệm render và chuyển tương tác thành action.','ViewModel là state holder theo scope của màn hình hoặc navigation graph; nó điều phối logic trình bày nhưng không phải nơi chứa mọi business rule.','Model gồm domain policy, repository, data source và các model mà ViewModel sử dụng, không chỉ là một data class.','UiState là snapshot đầy đủ để render; UiAction hoặc UiIntent là input; UiEffect là tác động một lần như điều hướng hoặc snackbar.','Unidirectional data flow là action đi vào và state đi ra. MVVM có thể áp dụng UDF mà không cần trở thành MVI đầy đủ.'))
S.append(s(4,'mechanism','Cơ chế hoạt động bên trong','View gửi action tới ViewModel. ViewModel xử lý trong viewModelScope, gọi use case hoặc repository, rồi cập nhật StateFlow. View collect theo lifecycle và render từ state.','ViewModelStore giữ instance qua configuration change. Khi owner thực sự bị finish hoặc back-stack entry bị remove, onCleared được gọi và viewModelScope bị cancel.','StateFlow giữ giá trị hiện tại và phát lại giá trị mới nhất cho collector mới, phù hợp với render state nhưng có thể làm lặp effect nếu dùng sai.','SavedStateHandle chỉ nên giữ dữ liệu nhỏ cần restore như ID, filter hoặc draft; dữ liệu thật phải đọc lại từ source of truth.','Trong Compose, recomposition chỉ nên đọc state; không gọi repository trực tiếp mỗi lần compose.',codes=(("ViewModel với UiState và action","data class FeedUiState(val items: List<PostUi> = emptyList(), val loading: Boolean = false, val error: String? = null)\nsealed interface FeedAction { data object Refresh : FeedAction; data class Open(val id: String) : FeedAction }\nclass FeedViewModel(private val refreshFeed: RefreshFeed) : ViewModel() {\n private val _state = MutableStateFlow(FeedUiState())\n val state: StateFlow<FeedUiState> = _state.asStateFlow()\n fun onAction(a: FeedAction) { if (a is FeedAction.Refresh) refresh() }\n private fun refresh() = viewModelScope.launch {\n  _state.update { it.copy(loading = true, error = null) }\n  runCatching { refreshFeed() }.onFailure { e -> _state.update { it.copy(error = e.message) } }\n  _state.update { it.copy(loading = false) }\n }\n}"),)))
S.append(s(5,'purpose','Mục đích của kỹ thuật','MVVM giúp View tập trung render và input, ViewModel giữ state theo vòng đời màn hình, còn model layer giữ business và data concern.','Nó giảm logic trong Activity hoặc Fragment, hỗ trợ Compose reactive và cho phép unit test state transition không cần khởi chạy UI.','MVVM tạo contract rõ về input, state, loading, error, retry và side effect của màn hình.'))
S.append(s(6,'problem','Vấn đề kỹ thuật được giải quyết','Không có state holder, UI dễ gọi API trực tiếp, giữ Job, cache dữ liệu và xử lý lifecycle; rotation gây request lặp, state mất hoặc callback vào View đã chết.','God ViewModel cũng là lỗi kiến trúc: một lớp chứa navigation, database, formatter, analytics, permission và business rule của nhiều màn.','Nhiều boolean loading/error độc lập và nhiều source of truth có thể tạo trạng thái UI mâu thuẫn.'))
S.append(s(7,'when-to-use','Dấu hiệu cần dùng','Dùng ViewModel khi màn hình có state cần sống qua configuration change, gọi bất đồng bộ, kết hợp nhiều nguồn dữ liệu, cần retry, validation hoặc unit test.','Graph-scoped ViewModel phù hợp khi nhiều destination thật sự chia sẻ một workflow state có owner rõ.','MVVM phù hợp với app Android dùng repository, use case và UI reactive bằng Flow.'))
S.append(s(8,'when-not-to-use','Khi không nên dùng','Không cần ViewModel cho composable thuần chỉ nhận parameter và callback hoặc component nhỏ do parent sở hữu state.','Không đưa mọi mapper, formatter và helper vào ViewModel chỉ để tránh code trong UI.','Không dùng shared Activity ViewModel như global event bus vì scope quá rộng tạo coupling và stale state.'))
S.append(s(9,'requirement','Yêu cầu sản phẩm cụ thể','Feed phải hiển thị cache, refresh nền, giữ filter qua rotation, không request trùng khi recomposition và biểu diễn loading, empty, error có ưu tiên rõ.','Chat phải collect message stream, gửi optimistic message, xử lý ack timeout, retry và reconnect; draft có policy restore riêng.','Post Detail nhận postId từ SavedStateHandle, xử lý not-found, network và auth error, đồng thời chỉ focus comment một lần khi deep link yêu cầu.','Acceptance criteria gồm state transition deterministic, state public immutable, cancellation đúng và test action concurrent.'))
S.append(s(10,'analysis','Phân tích dependency, error policy, lifecycle và resource limits','Dependency: ViewModel phụ thuộc abstraction domain hoặc repository, không phụ thuộc Activity, NavController, Retrofit response hay Room entity.','Error policy: map exception thành lỗi có nghĩa; lỗi transient cho retry, validation hiển thị theo field, auth expiry thuộc session concern.','Lifecycle: UI collect bằng repeatOnLifecycle hoặc collectAsStateWithLifecycle; long-running work phải có owner và cancellation phù hợp.','Resource limits: không giữ bitmap, View, Cursor, response lớn hoặc list vô hạn trong UiState; dùng Paging khi dữ liệu lớn.','Concurrency: action liên tiếp cần policy latest-wins, first-wins, serialize hoặc deduplicate; không launch coroutine vô hạn cho mỗi tap.','Process death: chỉ lưu identifier và checkpoint nhỏ; dữ liệu thật đọc lại từ Room, DataStore hoặc backend.'))
S.append(s(11,'minimal-code','Ví dụ code tối giản','Expose StateFlow immutable và hàm nhận action. Route collect state, còn Screen thuần chỉ nhận dữ liệu và callback.','Navigation nên đi qua callback từ route hoặc effect có single-consumption rõ; không inject NavController vào ViewModel.',codes=(("Collect state trong Compose","@Composable fun FeedRoute(vm: FeedViewModel, onOpen: (String) -> Unit) {\n val state by vm.state.collectAsStateWithLifecycle()\n FeedScreen(state = state, onRefresh = { vm.onAction(FeedAction.Refresh) }, onOpen = onOpen)\n}"),("Đọc argument qua SavedStateHandle","class PostViewModel(savedStateHandle: SavedStateHandle, observePost: ObservePost) : ViewModel() {\n private val postId: String = requireNotNull(savedStateHandle[\"postId\"])\n val state = observePost(postId).map(::toUiState).stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), PostUiState.Loading)\n}"))))
S.append(s(12,'upzi-case','Ví dụ thực tế Upzi','confirmed: Upzi dùng single-activity Compose, ViewModel, StateFlow hoặc Flow, Paging3 và Koin; chat có optimistic clientId, ack timeout, typing, read và delivered.','inferred: các feature có khả năng dùng screen state holder và repository, nhưng chưa xác nhận contract UiAction, UiState, effect strategy hay scope ViewModel của từng màn.','proposed: chuẩn hóa mỗi screen bằng immutable UiState, typed action, explicit concurrency policy, error mapping và route callback; socket hoặc session có lifetime dài hơn màn nên thuộc owner riêng.','needs-confirmation: cần đối chiếu code về shared ViewModel, SavedStateHandle, event channel, lifecycle collection và ownership của Paging hoặc socket trước khi kể như kinh nghiệm đã triển khai.'))
S.append(s(13,'alternatives','Phương án thay thế','MVC dễ làm Activity hoặc Fragment thành controller quá lớn.','MVP dùng Presenter và View interface, dễ test với View system nhưng nhiều callback và lifecycle wiring.','MVI nhấn mạnh reducer, intent và single state; mạnh với state machine phức tạp nhưng thêm ceremony.','Redux-style global store tập trung state nhưng tăng coupling nếu lạm dụng.','State hoisting đơn giản ở parent composable đủ cho component nhỏ.'))
S.append(s(14,'tradeoffs','Lý do lựa chọn và trade-off','MVVM tận dụng AndroidX ViewModel và Flow tốt, nhưng ranh giới Model mơ hồ nếu team không có quy ước.','Một UiState tạo snapshot nhất quán nhưng copy object lớn có chi phí; có thể tách sub-state theo ownership thật.','Use case gom policy và giảm coupling nhưng use case pass-through cho mọi thao tác tạo ceremony.','Graph-scoped ViewModel thuận tiện cho workflow chung nhưng tăng lifetime và coupling giữa destination.','Effect stream tránh nhét navigation vào state nhưng có thể mất khi không có collector; event durable phải trở thành state hoặc persisted command.'))
S.append(s(15,'edge-cases','Edge cases','Collector attach lại sau rotation nhận state mới nhất; snackbar nằm trong state có thể hiện lại nếu không có consumption protocol.','Hai refresh chạy song song có thể để response cũ ghi đè mới; dùng mutex, flatMapLatest, generation ID hoặc disable action.','stateIn với WhileSubscribed có thể restart upstream sau khi không còn collector; chọn sharing policy theo cost và freshness.','SavedStateHandle key sai hoặc argument thiếu phải fail có kiểm soát, không gọi API với ID rỗng.','PagingData không nên bị copy thành List trong UiState.','Channel có thể chờ collector; SharedFlow replay=0 có thể mất event; replay>0 có thể lặp. Chọn theo semantics.','Test dispatcher có thể che race; cần test scheduler và case concurrent action.'))
S.append(s(16,'mistakes','Sai lầm thường gặp','Giữ Activity, Fragment, NavController hoặc UI Context trong ViewModel gây coupling và leak.','Expose MutableStateFlow hoặc cho View sửa state trực tiếp.','Dùng StateFlow cho toast hoặc navigation rồi reset bằng delay, khiến logic phụ thuộc timing.','Khởi chạy network trong init không có policy collector, retry hoặc argument readiness.','Bắt Throwable và nuốt CancellationException.','Để DTO, Room entity hoặc string resource ID rò qua boundary.','Tạo BaseViewModel khổng lồ chứa loading, error, analytics, navigator và exception handler.','Test chỉ verify repository được gọi mà không kiểm tra chuỗi state.'))
S.append(s(17,'interview-basic','Câu hỏi phỏng vấn cơ bản','MVVM gồm những phần nào trên Android? ViewModel khác Presenter ra sao? onCleared khi nào chạy?','Tại sao StateFlow phù hợp với UiState? SavedStateHandle giải quyết gì và không giải quyết gì?','Tại sao không giữ Activity Context trong ViewModel? ViewModel nên gọi repository hay Retrofit trực tiếp?','Câu trả lời tốt mô tả action đến ViewModel, dependency model, state phát ra và lifecycle-aware rendering.'))
S.append(s(18,'interview-deep','Câu hỏi xoáy sâu và câu hỏi bẫy','ViewModel sống qua rotation nhưng request vẫn có thể lặp nếu effect đặt trong composable, key sai hoặc upstream restart theo sharing policy.','SharedFlow replay=1 không phải event hoàn hảo vì collector mới có thể nhận event cũ.','Application context đôi khi dùng được cho adapter platform hẹp, nhưng nên inject abstraction và không giữ UI context.','StateFlow update atomic cho giá trị nhưng side effect bên ngoài không tự atomic.','Search query nhanh nên dùng debounce, distinctUntilChanged và flatMapLatest với policy loading rõ.','Repository không nên chỉ là proxy Retrofit khi concern source selection, cache hoặc error mapping tồn tại.'))
S.append(s(19,'experience-answer','Mẫu trả lời gắn với kinh nghiệm','Trong dự án Compose, tôi để route collect StateFlow bằng collectAsStateWithLifecycle và truyền state cùng callback xuống screen thuần. ViewModel nhận action, gọi dependency và expose state immutable.','Với feed hoặc chat, tôi xác định source of truth và concurrency policy trước: refresh có dedup, send message có optimistic state và ack timeout, lỗi được map thành trạng thái UI có retry.','Tôi không khẳng định mọi feature Upzi đã theo đúng mẫu này; các chuẩn typed action hoặc effect chưa xác nhận phải ghi proposed hay needs-confirmation.'))
S.append(s(20,'practice','Bài tập thực hành','Refactor một composable đang gọi repository trực tiếp thành Route, Screen, ViewModel, UiState và UiAction.','Viết ViewModel tìm kiếm dùng debounce, distinctUntilChanged, flatMapLatest và test query cũ không ghi đè query mới.','Thiết kế PostDetailViewModel đọc postId từ SavedStateHandle, observe Room, refresh network và map lỗi.','Viết test bằng runTest và Turbine cho loading-content, loading-error, retry và action liên tiếp.','Xác nhận Job bị cancel khi ViewModel clear bằng fake repository treo.'))
S.append(s(21,'scenario','Bài tập tình huống','Rotate khi đang upload video: phân loại phần thuộc ViewModel màn và phần thuộc WorkManager hoặc foreground service.','Notification mở ChatDetail khi chưa đăng nhập: thiết kế coordinator, auth state, ViewModel scope và pending destination.','Hai tab cùng sửa filter feed: quyết định state chung hay riêng, owner và persistence.','Snackbar gửi tin thành công bị lặp sau rotation: đề xuất state hoặc effect protocol và test.','Shared Activity ViewModel chứa dữ liệu của 12 màn: lập kế hoạch tách theo workflow mà không rewrite toàn bộ.'))
S.append(s(22,'checklist','Checklist tự đánh giá','Tôi xác định rõ owner và lifetime của ViewModel.','View chỉ render state và gửi action.','ViewModel không giữ View, Activity hoặc NavController.','State public immutable và có source of truth rõ.','Business rule không bị nhét tùy tiện vào ViewModel.','Có policy cho loading, error, retry và concurrent action.','UI collection lifecycle-aware.','State nhỏ cần restore dùng SavedStateHandle; dữ liệu thật ở persistence.','Effect có semantics và test rõ.','Tôi kiểm tra process death, rotation, back stack và onCleared.','Unit test kiểm tra state transition.','Tôi tránh BaseViewModel và shared ViewModel quá rộng.'))
S.append(s(23,'summary','Tóm tắt cần nhớ','MVVM là kiến trúc trách nhiệm và data flow, không phải bộ tên lớp.','ViewModel là screen-level state holder, không phải persistent singleton hay nơi chứa mọi logic.','UiState đủ để render; action đi vào; effect chỉ dùng khi semantics thực sự một lần.','Lifecycle, concurrency, process death và error mapping là phần cốt lõi của MVVM production.','Đánh giá thiết kế bằng ownership, dependency direction, testability và tính nhất quán state.'))
Q=[('Q1','Vai trò chính của ViewModel là gì?',['Render UI','Giữ screen state và điều phối logic màn','Lưu vĩnh viễn','Thay repository'],1,'ViewModel là state holder và coordinator của màn hình.'),('Q2','ViewModel thường sống qua gì?',['Process death','Configuration change cùng owner','Force-stop','Uninstall'],1,'ViewModelStore giữ instance qua configuration change.'),('Q3','Kiểu phù hợp nhất cho UiState?',['MutableSharedFlow public','StateFlow immutable','BroadcastReceiver','Intent extras'],1,'StateFlow có giá trị hiện tại và replay state mới nhất.'),('Q4','Vì sao không giữ Activity trong ViewModel?',['Chậm','Coupling và leak lifecycle','Không compile','Không dùng Kotlin'],1,'ViewModel có thể sống lâu hơn Activity instance.'),('Q5','SavedStateHandle hợp với gì?',['Bitmap','ID, filter, draft nhỏ','Toàn feed','Socket'],1,'Nó dành cho state nhỏ có thể restore.'),('Q6','Event cần sống qua process death nên làm gì?',['SharedFlow replay=0','Persist thành pending state có identity','Toast','Delay'],1,'Event durable phải được mô hình hóa thành state hoặc persistence.'),('Q7','Search latest-wins dùng gì?',['flatMapLatest','zip','combine mọi request','GlobalScope'],0,'flatMapLatest hủy flow cũ khi query mới đến.'),('Q8','ViewModel nên phụ thuộc vào gì?',['Activity','NavController','Use case hoặc repository abstraction','Composable'],2,'Dependency hướng vào abstraction không phụ thuộc UI.'),('Q9','onCleared chạy khi nào?',['Mọi rotation','Owner bỏ ViewModel khỏi store','Mỗi recomposition','Mỗi onStop'],1,'Rotation thường giữ store; finish hoặc pop owner mới clear.'),('Q10','God ViewModel là gì?',['Ít state','Chứa concern nhiều màn và layer','Dùng StateFlow','Có test'],1,'Quá nhiều reason to change là dấu hiệu boundary sai.'),('Q11','StateFlow có lý tưởng cho navigation một lần không?',['Luôn','Không mặc định vì replay state','Chỉ Android 8','Chỉ XML'],1,'Collector mới có thể nhận lại giá trị cũ.'),('Q12','Test MVVM quan trọng nhất kiểm tra gì?',['Tên class','Chuỗi state và concurrency/error policy','Số dòng','Màu UI'],1,'Giá trị nằm ở transition và behavior observable.')]
S.append({'id':'quiz-guide','title':'24. Quiz có giải thích đáp án','blocks':[{'type':'quiz','id':i,'question':q,'options':o,'answerIndex':a,'explanation':e} for i,q,o,a,e in Q]})
lesson={'id':'f02','code':'F02','title':'MVVM','summary':'Thiết kế MVVM production trên Android với ViewModel, immutable UiState, action/effect contract, lifecycle, process death, concurrency, error policy và testing.','estimatedMinutes':360,'sections':S}
(D/'lessons'/'f').mkdir(parents=True,exist_ok=True); (D/'lessons'/'f'/'f02.json').write_text(json.dumps(lesson,ensure_ascii=False,separators=(',',':')))
cat=json.loads((D/'catalog.json').read_text())
for ch in cat['chapters']:
 for x in ch['lessons']:
  if x['id']=='f02': x['status']='published'; x['estimatedMinutes']=360
(D/'catalog.json').write_text(json.dumps(cat,ensure_ascii=False,indent=2)+'\n')
plan=json.loads((D/'book-plan.json').read_text()); plan['current']='f03'; plan['completed'].append('f02') if 'f02' not in plan['completed'] else None; (D/'book-plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
idx=json.loads((D/'search-index.json').read_text()); e={'id':'f02','code':'F02','title':'MVVM','chapter':'F','path':'data/lessons/f/f02.json','keywords':['mvvm','viewmodel','ui state','stateflow','ui action','ui effect','savedstatehandle','lifecycle','process death','testing']}
if isinstance(idx,list): idx=[x for x in idx if x.get('id')!='f02']+[e]
else:
 k='items' if 'items' in idx else 'lessons'; idx[k]=[x for x in idx.get(k,[]) if x.get('id')!='f02']+[e]
(D/'search-index.json').write_text(json.dumps(idx,ensure_ascii=False,indent=2)+'\n')
ids=[x['id'] for x in S]; paras=sum(b['type']=='paragraph' for x in S for b in x['blocks']); chars=sum(len(b['content']) for x in S for b in x['blocks'] if b['type']=='paragraph'); codes=sum(b['type']=='code' for x in S for b in x['blocks']); quizzes=[b for x in S for b in x['blocks'] if b['type']=='quiz']
order=['objectives','prerequisites','terminology','mechanism','purpose','problem','when-to-use','when-not-to-use','requirement','analysis','minimal-code','upzi-case','alternatives','tradeoffs','edge-cases','mistakes','interview-basic','interview-deep','experience-answer','practice','scenario','checklist','summary','quiz-guide']
rep={'id':'f02','sections':len(S),'uniqueSectionIds':len(set(ids)),'exactSectionOrder':ids==order,'paragraphs':paras,'paragraphCharacters':chars,'codeBlocks':codes,'quizQuestions':len(quizzes),'quizAnswersValid':all(0<=q['answerIndex']<len(q['options']) and q['explanation'] for q in quizzes),'truthfulnessLabelsPresent':all(z in json.dumps(lesson,ensure_ascii=False) for z in ['confirmed','inferred','proposed','needs-confirmation']),'nextLesson':'f03'}
(D/'validation-f02.json').write_text(json.dumps(rep,ensure_ascii=False,indent=2)+'\n')