import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'android-learning'/'data'; sections=[]
def sec(i,id,title,*paras,codes=None):
 b=[{'type':'paragraph','content':p} for p in paras]
 for label,code in (codes or []): b.append({'type':'code','language':'kotlin','label':label,'content':code})
 sections.append({'id':id,'title':f'{i}. {title}','blocks':b})
sec(1,'objectives','Mục tiêu bài học','Hiểu Context là gateway tới tài nguyên, service và environment của Android, đồng thời phân biệt application, activity, service, receiver và context wrapper theo lifetime, theme và capability. Người học phải giải thích được vì sao chọn sai Context tạo leak, crash theme hoặc hành vi task sai.','Mục tiêu thực hành là nhận diện strong reference chain, GC root, static/singleton leak, callback/listener leak, coroutine leak, Compose capture leak, bitmap/cache pressure và dùng LeakCanary, heap dump, dominator tree để chứng minh nguyên nhân thay vì đoán.')
sec(2,'prerequisites','Kiến thức nền','Cần nắm Activity Lifecycle, configuration change, process death, ViewModel, coroutine scope, DI scope, Compose effect APIs và khái niệm garbage collection. Memory leak không có nghĩa object không bao giờ giải phóng; đó là object không còn cần nhưng vẫn reachable từ GC root.','Cần phân biệt retained memory với leak thật, native memory với Java/Kotlin heap, và high allocation rate với retained object. OOM có thể đến từ leak, cache quá lớn, bitmap/native buffer hoặc workload hợp lệ nhưng vượt ngân sách.')
sec(3,'terminology','Định nghĩa và chú giải thuật ngữ','Context cung cấp Resources, package, system service, component launch và theme context. Application Context sống theo process; Activity Context gắn lifecycle và theme của Activity; Service Context gắn Service; ContextThemeWrapper thêm theme.','GC root gồm thread, static field, JNI reference, class loader và framework root. Reference chain là đường từ root tới object bị giữ. Dominator là object giữ phần lớn retained heap; shallow size là kích thước object, retained size là tổng memory sẽ giải phóng nếu object đó biến mất.','LeakCanary theo dõi destroyed object bằng weak reference, chờ GC rồi dump heap nếu object vẫn retained. WeakReference không tự sửa ownership sai; nó chỉ không giữ mạnh object.')
sec(4,'mechanism','Cơ chế hoạt động bên trong','Garbage collector chỉ thu hồi object không còn reachable từ root. Nếu singleton giữ listener là Activity, thread giữ Runnable capture View, hoặc coroutine global capture callback, Activity cũ vẫn reachable sau onDestroy và toàn bộ view tree có thể bị giữ.','Configuration change dễ phơi leak vì Activity cũ phải được thu hồi nhanh trong khi Activity mới đã tồn tại. Một reference tới View thường kéo theo Context, Window, Drawable và hierarchy lớn.','Compose không loại bỏ leak tự động. Lambda remembered, DisposableEffect thiếu cleanup, observer đăng ký sai owner hoặc AndroidView giữ callback cũ đều có thể capture Activity/Composable state quá lâu.',codes=[('Listener lifecycle đúng','''@Composable
fun ConnectivityObserver(manager: ConnectivityManager) {
    val callback = remember { NetworkCallback() }
    DisposableEffect(manager, callback) {
        manager.registerDefaultNetworkCallback(callback)
        onDispose { manager.unregisterNetworkCallback(callback) }
    }
}''')])
sec(5,'purpose','Mục đích của kỹ thuật','Quản lý Context và reference đúng giúp component được thu hồi đúng lifetime, tránh tăng heap theo mỗi lần mở màn, giảm OOM, jank do GC và crash sau nhiều phiên sử dụng.','Mục tiêu không phải thay mọi Activity Context bằng applicationContext. Theme, window, navigation và UI service cần Context đúng capability; nguyên tắc là dependency không được sống lâu hơn object mà nó giữ.')
sec(6,'problem','Vấn đề kỹ thuật được giải quyết','Leak thường xuất hiện âm thầm: mở đóng màn nhiều lần, heap tăng, GC chạy dày, ảnh load chậm, cuối cùng OOM ở vị trí không liên quan. Nếu chỉ nhìn stack trace OOM sẽ dễ sửa nhầm.','Chọn sai Context cũng gây lỗi khác leak: inflate sai theme, dialog token invalid, startActivity thiếu FLAG_ACTIVITY_NEW_TASK, locale wrapper bị bỏ qua hoặc service dùng Activity đã destroy.')
sec(7,'when-to-use','Dấu hiệu cần dùng','Cần audit khi heap tăng sau navigation lặp, destroyed Activity vẫn retained, ViewModel chứa View/Context, singleton giữ callback, SDK yêu cầu register/unregister, custom view chạy animation hoặc handler, media/camera giữ surface.','Cần profiler khi OOM theo phiên dài, bitmap/native memory lớn, paging/feed scroll gây GC nhiều hoặc leak report chỉ ra đường reference từ root.')
sec(8,'when-not-to-use','Khi không nên dùng','Không dùng applicationContext một cách máy móc cho dialog, themed inflate, Activity Result hay navigation. Không bọc mọi reference bằng WeakReference để che ownership sai.','Không gọi System.gc như giải pháp production, không clear mọi cache mỗi onStop và không kết luận leak chỉ vì heap chưa giảm ngay; runtime có thể giữ heap đã cấp phát để tái sử dụng.')
sec(9,'requirement','Yêu cầu sản phẩm cụ thể','Sau 30 vòng mở và đóng Opportunity Detail, Chat Detail và media picker, số Activity/View retained phải trở về baseline; không có listener, socket callback hoặc image target giữ màn đã destroy.','Upload, socket và analytics dùng application-scoped dependency nhưng UI callback phải lifecycle-aware. Dialog, toast, notification và navigation dùng Context phù hợp; không crash BadTokenException khi Activity background.','Acceptance criteria gồm LeakCanary sạch trên critical flows, heap delta có ngưỡng, rotation loop, logout/login, process recreation, image-heavy feed và test SDK register/unregister.')
sec(10,'analysis','Phân tích dependency, error policy, lifecycle và resource limits','Dependency: repository, database, network client thường application scope và chỉ nhận applicationContext nếu thực sự cần. Activity-scoped object được dispose khi Activity destroy; ViewModel không giữ Activity/View; Composable nhận value/callback thay vì service mutable toàn cục.','Error policy: unregister có thể ném nếu registration state sai nên cần idempotent ownership. Cleanup phải an toàn khi callback chưa đăng ký hoặc component bị destroy sớm. SDK callback sau dispose phải bị ignore bằng lifecycle/state token.','Lifecycle: đăng ký ở onStart thì hủy ở onStop; resource cần visible lifetime dùng STARTED; resource cần foreground interaction dùng RESUMED. Coroutine phải nằm trong lifecycleScope, viewModelScope hoặc scope có owner rõ.','Resource limits: cache phải có size bound và eviction; bitmap decode theo target size; close Cursor, InputStream, ParcelFileDescriptor, ImageProxy và media codec. Leak native resource không luôn hiện rõ trong Java heap.',codes=[('ViewModel không giữ Activity','''class ProfileViewModel(
    private val repository: ProfileRepository
) : ViewModel() {
    fun onShareRequested(userId: String) {
        _events.tryEmit(ProfileEvent.Share(userId))
    }
}
// Activity/Compose xử lý Intent bằng Context hiện tại.''')])
sec(11,'minimal-code','Ví dụ code tối giản','Nếu dependency cần Context để mở database, đọc file hoặc system service process-wide, inject Application hoặc @ApplicationContext. Nếu cần theme/window, truyền Activity Context trong scope ngắn tại UI.','Callback registration nên có owner duy nhất và cleanup đối xứng. rememberUpdatedState hữu ích khi effect sống lâu nhưng callback mới nhất thay đổi, tránh restart effect hoặc capture callback cũ.',codes=[('Callback mới nhất trong effect','''@Composable
fun SensorEffect(onValue: (Float) -> Unit) {
    val latest by rememberUpdatedState(onValue)
    DisposableEffect(Unit) {
        val listener = SensorListener { latest(it) }
        register(listener)
        onDispose { unregister(listener) }
    }
}''')])
sec(12,'upzi-case','Ví dụ thực tế Upzi','confirmed: Upzi dùng single-activity Compose, Koin, socket chat, Paging, image/video picker và deep link; đây là các vùng có nguy cơ giữ Activity, callback hoặc media resource nếu scope và cleanup sai.','inferred: socket manager và repositories có thể ở application scope, còn UI collector lifecycle-aware, nhưng chưa xác nhận LeakCanary, heap budget, Context injection qualifiers hay media resource cleanup. proposed: thêm LeakCanary debug, rotation/navigation stress test, audit Koin scopes và listener ownership. needs-confirmation: cần kiểm tra module DI, image pipeline, socket callbacks và custom views trước khi kể là kinh nghiệm đã triển khai.')
sec(13,'alternatives','Phương án thay thế','Thay callback giữ UI bằng Flow/StateFlow từ repository rồi collect lifecycle-aware. Thay static singleton thủ công bằng DI scope rõ. Thay Handler/Runnable dài hạn bằng coroutine scope có cancellation.','Đối với cache, dùng LruCache, image loader cache hoặc repository cache có size policy. Với observer framework, dùng LifecycleObserver hoặc repeatOnLifecycle thay register trong onCreate rồi quên unregister.')
sec(14,'tradeoffs','Lý do lựa chọn và trade-off','Application Context giảm rủi ro Activity leak nhưng thiếu theme/window và có hành vi startActivity khác. Activity Context đúng cho UI nhưng không được lưu ở object sống lâu.','WeakReference tránh giữ mạnh nhưng làm control flow khó đoán và có thể null bất kỳ lúc nào; lifecycle-aware ownership rõ ràng hơn. LeakCanary tăng overhead debug nhưng đem lại reference chain cụ thể.','Cache lớn giảm network/decode nhưng tăng pressure; cache nhỏ giảm memory nhưng tăng IO. Cần budget theo thiết bị và dữ liệu thực, không chọn cực đoan.')
sec(15,'edge-cases','Edge cases','Dialog hoặc popup tạo trước rotation giữ Activity cũ; Toast custom view, InputMethodManager, WebView, map SDK và ad SDK có lịch sử leak theo version. Cần xác minh library và workaround theo phiên bản.','Coroutine child có thể tiếp tục nếu dùng external scope; suspend function capture lambda Activity; callback đến sau logout có thể cập nhật màn mới sai user.','Compose Preview hoặc test environment có lifecycle khác production. AndroidView factory/update/onRelease cần cleanup resource native hoặc listener.','Multi-window có nhiều resumed Activity; process singleton không được giả định chỉ một Activity hiện tại. CurrentActivity holder static rất dễ stale và leak.',codes=[('Closeable resource','''contentResolver.openInputStream(uri)?.use { input ->
    repository.copyToDraft(input)
} // use bảo đảm close kể cả khi exception''')])
sec(16,'mistakes','Sai lầm thường gặp','Lỗi phổ biến: companion object giữ Activity/View, singleton giữ listener, ViewModel nhận Activity, anonymous inner class capture outer Activity, postDelayed không remove, observeForever không removeObserver và register receiver không unregister.','Trong Compose: remember object có Context cũ với key sai, LaunchedEffect dùng scope ngoài composition, DisposableEffect thiếu onDispose, truyền NavController vào singleton hoặc giữ Painter/Bitmap quá lâu.','Một lỗi khác là xem mọi retained object là leak mà không đọc reference chain hoặc baseline; framework/library có thể giữ tạm thời. Phải lặp thao tác, force GC trong công cụ và so retained count.')
sec(17,'interview-basic','Câu hỏi phỏng vấn cơ bản','Câu hỏi nền: Context là gì; applicationContext khác Activity Context; memory leak là gì; GC root là gì; ViewModel có giữ Activity được không; listener cleanup ở đâu; LeakCanary hoạt động thế nào.','Mẫu trả lời tốt nêu lifetime graph: object A sống lâu hơn B nhưng giữ strong reference tới B; sau khi B hết lifecycle, GC vẫn thấy reachable nên không thu hồi.')
sec(18,'interview-deep','Câu hỏi xoáy sâu và câu hỏi bẫy','Câu xoáy: tại sao heap tăng chưa chắc leak; native bitmap leak tìm thế nào; applicationContext có giải quyết mọi leak không; observeForever dùng khi nào; coroutine capture Activity ra sao; multi-window phá currentActivity singleton thế nào.','Câu bẫy: WeakReference có sửa leak không; onDestroy có luôn cleanup không; ViewModel có sống vĩnh viễn không; System.gc có nên gọi không; cache giữ object có luôn là leak không.')
sec(19,'experience-answer','Mẫu trả lời gắn với kinh nghiệm','Tôi xác định leak bằng cách lặp flow, dùng LeakCanary lấy reference chain, xác định GC root và owner sai, sau đó sửa scope hoặc cleanup đối xứng. Tôi không chỉ thay bằng applicationContext nếu dependency cần theme/window.','Với Upzi, confirmed là có Compose, socket, media picker và DI. LeakCanary hoặc leak cụ thể chỉ được nói là inferred/proposed nếu chưa có issue, heap dump hoặc code xác nhận.')
sec(20,'practice','Bài tập thực hành','Tạo Activity bị leak bởi singleton listener, rotation 10 lần, dùng LeakCanary đọc chain rồi sửa bằng lifecycle-aware registration. Ghi retained size trước và sau.','Tạo Compose effect đăng ký sensor với callback thay đổi; sửa bằng rememberUpdatedState và DisposableEffect.','Profile màn feed ảnh: phân biệt allocation churn, cache retained và Activity leak; đề xuất memory budget cùng test script.')
sec(21,'scenario','Bài tập tình huống','Socket singleton giữ lambda onMessage từ ChatScreen. User logout rồi mở account khác, callback cũ vẫn chạy. Thiết kế subscription token, lifecycle và account scope.','SDK image picker trả URI sau rotation; callback giữ Activity cũ và InputStream không close. Tìm hai lỗi độc lập và sửa.','App có WebView trong detail, mở đóng 20 lần heap tăng. Lập kế hoạch đo Java/native heap, destroy WebView, detach parent và kiểm tra library version.')
sec(22,'checklist','Checklist tự đánh giá','Tôi phân biệt Context theo lifetime/capability, hiểu GC root, strong reference chain, shallow và retained size.','Tôi không giữ Activity/View trong ViewModel/singleton; listener, receiver, observer, coroutine và native resource đều có owner cùng cleanup rõ.','Tôi biết dùng LeakCanary, heap dump, stress loop và baseline; biết chi tiết Upzi nào confirmed hay cần xác nhận.')
sec(23,'summary','Tóm tắt cần nhớ','Memory leak là object hết nhu cầu nhưng vẫn reachable từ GC root. Cốt lõi là lifetime mismatch và ownership sai, không phải chỉ vì dùng Context.','Application Context dành cho dependency process-wide; Activity Context dành cho UI/theme trong scope ngắn. WeakReference và System.gc không thay kiến trúc lifecycle-aware.','Đo bằng reference chain, retained size và flow lặp. Sửa bằng scope đúng, cleanup đối xứng, cancellation, close resource và cache có giới hạn.')
sec(24,'quiz-guide','Quiz có giải thích đáp án','Làm quiz sau khi có thể vẽ reference chain từ static/thread tới Activity bị destroy và chọn Context theo capability.','Mỗi đáp án cần giải thích owner sống bao lâu, reference nào giữ object và cleanup xảy ra ở đâu.')
quiz=[]
def q(i,question,correct,explanation,*options): quiz.append({'id':f'q{i}','question':question,'options':[{'id':chr(97+j),'text':o} for j,o in enumerate(options)],'correctOptionIds':[chr(97+correct)],'explanation':explanation})
q(1,'Memory leak trong managed heap là gì?',0,'Object không còn cần nhưng vẫn reachable từ GC root.','Object vẫn reachable ngoài lifetime cần thiết','Mọi object lớn','Mọi cache','GC chạy chậm')
q(2,'Context nào phù hợp để inflate dialog theo theme Activity?',1,'Dialog cần theme và window token của Activity hiện tại.','Application Context','Activity Context','Service Context','Không cần Context')
q(3,'ViewModel có nên giữ Activity không?',1,'ViewModel có thể sống qua recreation và giữ Activity cũ.','Có luôn','Không','Chỉ landscape','Chỉ debug')
q(4,'LeakCanary tìm leak bằng cách nào?',2,'Nó theo dõi object expected-destroyed, kiểm tra retention và phân tích heap dump.','Đọc logcat בלבד','Gọi System.gc liên tục','Weak reference và heap analysis','Xóa cache')
q(5,'WeakReference có phải giải pháp mặc định không?',1,'Nó không sửa ownership và có thể null bất kỳ lúc nào.','Có','Không','Chỉ với ViewModel','Chỉ với bitmap')
q(6,'Heap tăng sau thao tác có chắc là leak không?',1,'Runtime có thể giữ heap để tái sử dụng hoặc cache hợp lệ.','Có','Không','Chỉ Android 14','Chỉ release')
q(7,'observeForever cần gì?',0,'Observer không tự gắn lifecycle nên owner phải remove rõ ràng.','removeObserver rõ ràng','Activity Context','System.gc','SavedStateHandle')
q(8,'Coroutine nào dễ leak UI nhất?',3,'Global/external scope có thể sống lâu hơn Activity và capture callback UI.','viewModelScope không capture UI','lifecycleScope','rememberCoroutineScope đúng owner','GlobalScope capture Activity')
q(9,'Resource nào nên dùng use?',2,'Closeable như InputStream cần đóng kể cả exception.','String','StateFlow','InputStream','Context')
q(10,'CurrentActivity singleton sai trong multi-window vì sao?',0,'Có thể có nhiều Activity active và reference trở nên stale/leak.','Có nhiều Activity hợp lệ','Không compile','Không có Context','Chỉ tablet')
q(11,'Cache lớn có luôn là leak không?',1,'Cache có chủ đích và eviction có thể là retained memory hợp lệ.','Có','Không','Chỉ bitmap','Chỉ debug')
q(12,'Cách xác minh fix leak tốt nhất?',2,'Lặp lại flow, so retained object và reference chain sau fix.','Đọc code bằng mắt','Restart IDE','Stress flow và đo lại','Gọi clearCache')
lesson={'id':'e04','code':'E04','title':'Context và Memory Leak','summary':'Hiểu Context theo lifetime/capability, nhận diện reference chain giữ Activity và sửa leak bằng scope, cleanup, cancellation, close resource và đo heap có hệ thống.','estimatedMinutes':360,'sections':sections,'quiz':quiz}
lesson_path=DATA/'lessons'/'e'/'e04.json'; lesson_path.parent.mkdir(parents=True,exist_ok=True); lesson_path.write_text(json.dumps(lesson,ensure_ascii=False,separators=(',',':')))
required=['objectives','prerequisites','terminology','mechanism','purpose','problem','when-to-use','when-not-to-use','requirement','analysis','minimal-code','upzi-case','alternatives','tradeoffs','edge-cases','mistakes','interview-basic','interview-deep','experience-answer','practice','scenario','checklist','summary','quiz-guide']
ids=[s['id'] for s in sections]; paragraphs=[b['content'] for s in sections for b in s['blocks'] if b['type']=='paragraph']; codes=[b for s in sections for b in s['blocks'] if b['type']=='code']; assert ids==required and len(set(ids))==24 and len(paragraphs)>=40 and sum(map(len,paragraphs))>=9000 and len(codes)>=4 and len(quiz)>=10
text=lesson_path.read_text(); assert all(x in text for x in ['confirmed:','inferred:','proposed:','needs-confirmation:'])
catalog_path=DATA/'catalog.json'; catalog=json.loads(catalog_path.read_text())
for chapter in catalog['chapters']:
 for item in chapter['lessons']:
  if item['id']=='e04': assert item['status']=='planned'; item['status']='published'; item['estimatedMinutes']=360
catalog_path.write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
plan_path=DATA/'book-plan.json'; plan=json.loads(plan_path.read_text()); assert plan['current']=='e04'; plan['completed'].append('e04'); plan['current']='e05'; plan_path.write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
index_path=DATA/'search-index.json'; index=json.loads(index_path.read_text()); index=[x for x in index if x.get('lessonId')!='e04']; index.append({'lessonId':'e04','code':'E04','title':'Context và Memory Leak','keywords':['Context','applicationContext','Activity Context','memory leak','LeakCanary','heap dump','GC root','retained size','ViewModel leak','listener cleanup','WeakReference','Compose leak'],'headings':['Context lifetime','GC roots and reference chains','LeakCanary','Lifecycle cleanup','Compose leaks','Native resources','Cache budgets','Upzi case study']}); index_path.write_text(json.dumps(index,ensure_ascii=False,indent=2)+'\n')
report={'id':'e04','sections':24,'uniqueSectionIds':24,'exactSectionOrder':True,'paragraphs':len(paragraphs),'paragraphCharacters':sum(map(len,paragraphs)),'codeBlocks':len(codes),'quizQuestions':len(quiz),'quizAnswersValid':True,'truthfulnessLabelsPresent':True,'nextLesson':'e05'}; (ROOT/'validation-e04.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n'); print(json.dumps(report,ensure_ascii=False))