import json
from pathlib import Path

ROOT=Path('android-learning/data')
IDS=['objectives','prerequisites','terminology','mechanism','purpose','problem','when-to-use','when-not-to-use','requirement','analysis','minimal-code','upzi-case','alternatives','tradeoffs','edge-cases','mistakes','interview-basic','interview-deep','experience-answer','practice','scenario','checklist','summary','quiz-guide']
TITLES=['1. Mục tiêu bài học','2. Kiến thức nền','3. Định nghĩa và chú giải thuật ngữ','4. Cơ chế hoạt động bên trong','5. Mục đích của kỹ thuật','6. Vấn đề kỹ thuật được giải quyết','7. Dấu hiệu cần dùng','8. Khi không nên dùng','9. Yêu cầu sản phẩm cụ thể','10. Phân tích dependency, error policy, lifecycle và resource limits','11. Ví dụ code tối giản','12. Ví dụ thực tế Upzi','13. Phương án thay thế','14. Lý do lựa chọn và trade-off','15. Edge cases','16. Sai lầm thường gặp','17. Câu hỏi phỏng vấn cơ bản','18. Câu hỏi xoáy sâu và câu hỏi bẫy','19. Mẫu trả lời gắn với kinh nghiệm','20. Bài tập thực hành','21. Bài tập tình huống','22. Checklist tự đánh giá','23. Tóm tắt cần nhớ','24. Quiz có giải thích đáp án']
TEXT={
'objectives':['Hiểu Use Case như một application boundary mô tả mục tiêu nghiệp vụ cụ thể, không phải lớp trung gian sinh ra chỉ để gọi lại repository.','Phân biệt use case, application service, domain service, repository, ViewModel và worker.','Thiết kế input/output typed, error policy, cancellation, idempotency, transaction, observability và testability.','Đánh giá khi nào abstraction này tạo giá trị và khi nào chỉ là pass-through boilerplate.'],
'prerequisites':['Cần nắm Separation of Concerns, MVVM, MVI/UDF, Clean Architecture và Repository Pattern.','Cần hiểu coroutine cancellation, Flow, DI, transaction, process death, source of truth và idempotency.','Use case đứng ở application layer để điều phối policy; nó không thay thế repository hoặc ViewModel.'],
'terminology':['Use Case biểu diễn mục tiêu của actor như SendMessage, ApplyToJob, RefreshFeed hoặc UploadPostMedia.','Application service điều phối nhiều dependency để hoàn thành một hành vi. Trong Android, class hậu tố UseCase thường đóng vai trò này.','Domain service chứa rule nghiệp vụ thuần giữa nhiều entity; repository là abstraction của data access và synchronization.','Command thay đổi state; Query đọc state. CQRS là lựa chọn kiến trúc có chủ đích, không phải yêu cầu mặc định.','Interactor là tên khác của use case trong nhiều tài liệu Clean Architecture.'],
'mechanism':['ViewModel tạo input typed và gọi use case; use case validate, áp policy, điều phối repository/service rồi trả output typed.','Dependency hướng vào abstraction. Retrofit, Room, Context, NavController và Compose state không nên rò vào contract.','Coroutine cancellation truyền từ caller xuống dependency; use case không được nuốt CancellationException.','Workflow nhiều bước cần ordering, retry boundary, compensation và idempotency rõ ràng.','Query quan sát liên tục có thể trả Flow; command hữu hạn thường là suspend function.','Input/output typed tránh Map<String, Any>, transport DTO và mutable object xuyên tầng.'],
'purpose':['Làm nổi bật ngôn ngữ sản phẩm trong code thay vì chuỗi lời gọi kỹ thuật rải trong ViewModel.','Tập trung orchestration để UI, deep link, notification action và worker dùng cùng hành vi.','Tạo seam kiểm thử business workflow không cần Android runtime.','Giữ presentation tập trung vào state và repository tập trung vào data boundary.'],
'problem':['ViewModel gọi nhiều repository, analytics, cache và scheduler sẽ trở thành God ViewModel.','Repository chứa validation, navigation và toàn bộ workflow sẽ thành God Repository.','Cùng hành vi triển khai ở nhiều entry point dễ lệch rule.','Use case tạo một application boundary có responsibility và reason to change rõ.'],
'when-to-use':['Dùng khi hành động phối hợp nhiều dependency hoặc có validation, authorization, retry, transaction, idempotency hay concurrency policy.','Dùng khi cùng hành vi được gọi từ nhiều entry point.','Dùng khi tên hành động nghiệp vụ giúp code dễ đọc và dễ kiểm thử.','Dùng khi muốn ViewModel không phụ thuộc chi tiết socket, cache, upload session hoặc scheduling.'],
'when-not-to-use':['Không cần class riêng cho getter/setter pass-through không thêm policy, reuse hoặc contract value.','Không tạo UseCase chỉ để đổi tên repository.getX.','Không đặt UI formatting, string resource, navigation hoặc permission request trực tiếp trong use case thuần.','Không tạo MegaUseCase điều phối cả feature.','Không ép mọi use case vào generic BaseUseCase phức tạp.'],
'requirement':['SendMessage phải tạo clientId ổn định, persist pending trước khi gửi, tránh duplicate khi retry và trả identity để reconcile.','ApplyToJob phải kiểm tra eligibility, chống double submit và map lỗi sản phẩm rõ ràng.','UploadPostMedia phải validate media, giới hạn concurrency, theo dõi progress và dùng durable work khi cần sống qua process death.','Acceptance criteria phải nêu precondition, postcondition, error taxonomy, cancellation, idempotency, telemetry và resource budget.','Contract không rò Retrofit Response, Room Entity, Context hoặc mutable collection.'],
'analysis':['Dependency gồm repository, clock, id generator, validator, policy và scheduler qua contract nhỏ; composition root cung cấp implementation.','Error policy phân biệt validation, authorization, conflict, unavailable, timeout và unexpected defect; không biến mọi lỗi thành String.','Caller sở hữu lifecycle của work ngắn hạn; WorkManager hoặc persistent queue sở hữu work cần sống qua process death.','Resource limits cần bounded concurrency, timeout, backpressure và payload limit; use case không giữ bitmap hoặc list vô hạn.','Concurrency policy có thể là latest-wins, first-wins, serialize, single-flight hoặc idempotent retry.','Local DB transaction không làm network và DB atomic; cần outbox, reconciliation hoặc compensation.','Observability ghi tên use case, duration, result category và correlation id nhưng phải redact PII.','Inject clock, dispatcher và id generator để test deterministic.'],
'minimal-code':['Use case tốt thêm policy có ý nghĩa thay vì chỉ forward.','Command hữu hạn dùng suspend và result typed; query reactive có thể dùng Flow.'],
'upzi-case':['confirmed: Upzi dùng Compose, ViewModel, StateFlow, Paging, Socket.IO, optimistic clientId, ack timeout, delivered/read/typing và deep link.','inferred: chat, feed, opportunity và upload có nhu cầu tự nhiên cho application-level use case, nhưng chưa xác nhận mọi module đã chuẩn hóa theo pattern này.','proposed: tách SendMessageUseCase, RetryMessageUseCase, MarkConversationReadUseCase, RefreshFeedUseCase và ProcessDeepLinkUseCase.','proposed: SendMessageUseCase persist pending/outbox trước socket emit; repository reconcile clientId/serverId; socket adapter chỉ chịu transport.','needs-confirmation: cần đối chiếu ownership của ack timeout, dedup, analytics và WorkManager trước khi kể như implementation thực tế.'],
'alternatives':['Feature nhỏ có thể để ViewModel gọi repository trực tiếp nếu boundary vẫn rõ.','Application service nhiều method có cohesion tốt có thể phù hợp hơn hàng chục class một-hàm.','Entity method phù hợp rule thuộc entity; domain service phù hợp rule thuần; use case phù hợp orchestration actor goal.','Command handler hoặc effect handler trong MVI có thể thực hiện vai trò tương tự.','Top-level function phù hợp logic thuần nhỏ; class hữu ích khi cần DI.'],
'tradeoffs':['Use case tăng readability, reuse và testability nhưng thêm class, mapping và dependency graph.','Một class mỗi hành động rõ ràng nhưng gây ceremony nếu phần lớn chỉ pass-through.','Gộp nhiều method giảm file count nhưng có nguy cơ God service.','Input/output typed tăng an toàn nhưng tăng mapping.','Không phụ thuộc Android giúp test nhanh nhưng cần platform adapter.','Chọn granularity theo actor goal và reason to change, không theo mỗi endpoint.'],
'edge-cases':['Caller bị cancel sau local write nhưng trước enqueue; cần transaction hoặc pending state để worker tiếp quản.','Double tap không được giải quyết tuyệt đối chỉ bằng mutex trong process; cần idempotency key hoặc server constraint.','Account switch khi use case đang chạy có thể ghi result cũ vào session mới; cần account partition/session generation.','Timeout rồi retry trong khi request đầu đã thành công cần reconciliation.','Clock thiết bị sai có thể làm TTL hoặc eligibility sai.','Nhiều collector Flow có thể gây refresh trùng nếu sharing policy không rõ.','Mutable output cho phép caller phá invariant.','Map mọi exception thành business error sẽ che defect.'],
'mistakes':['Tạo UseCase cho mọi repository method mà không thêm policy hoặc reuse.','Đưa Context, NavController, Compose state hoặc transport DTO vào contract.','Dùng BaseUseCase generic và Result wrapper lồng nhiều tầng.','Nuốt CancellationException trong catch rộng.','Hard-code dispatcher, clock, UUID hoặc singleton.','Để use case quyết định UI string, toast hoặc route cụ thể.','Đặt toàn bộ business rule trong repository rồi use case chỉ forward.','Không định nghĩa idempotency, concurrency và transaction semantics.','Dùng Flow cho one-shot operation chỉ vì codebase thích reactive API.'],
'interview-basic':['Use case là gì và khác repository thế nào?','Use case nên nằm ở layer nào và phụ thuộc vào gì?','Khi nào cần class use case riêng?','Tại sao operator fun invoke thường được dùng?','Khi nào trả Flow và khi nào dùng suspend?','Use case có được phụ thuộc Context không?','Phân biệt use case, domain service và ViewModel.','Tại sao pass-through use case có thể là over-engineering?'],
'interview-deep':['Nếu use case chỉ gọi một repository method thì có nên xóa không? Cần đánh giá contract stability, reuse, policy và cost.','Làm sao bảo đảm idempotency khi timeout và retry? Dùng client key, server constraint, durable outbox và reconciliation.','Use case có thể mở transaction qua repository hoặc unit-of-work abstraction nhưng không rò Room API.','Network thành công nhưng local write thất bại cần authoritative source, retry, reconciliation hoặc compensation.','Mutex không đủ chống duplicate giữa process restart hoặc nhiều thiết bị.','Không catch Throwable bừa bãi; cancellation phải truyền tiếp và defect phải được quan sát.','Test timeout, clock và UUID bằng dependency injected deterministic.','Reducer MVI thuần cập nhật state; effect handler gọi use case để thực hiện application behavior.'],
'experience-answer':['Ở Upzi, confirmed có optimistic clientId, socket ack timeout và delivered/read. Tôi không khẳng định full Clean Architecture nếu chưa kiểm tra code.','Tôi có thể đề xuất SendMessageUseCase tạo clientId, persist pending, enqueue transport và trả result typed.','Repository giữ source of truth, socket adapter chịu transport, ViewModel chịu UiState.','Khi kể phỏng vấn, tôi tách rõ confirmed, inferred, proposed và needs-confirmation.','Tôi không tạo use case cho mọi getter; chỉ tách khi có policy, orchestration, reuse hoặc boundary ổn định.'],
'practice':['Viết SendMessageUseCase có validation, injected IdGenerator, persist pending và typed result.','Test empty text, persist failure, cancellation và duplicate retry.','Refactor ViewModel gọi ba dependency thành một use case rồi so sánh dependency count.','Viết ApplyOpportunityUseCase có eligibility, first-wins và idempotency key.','Tạo fake Clock và IdGenerator để test deterministic.','Viết contract test giữa fake repository và implementation thật.'],
'scenario':['Người dùng bấm gửi hai lần khi mạng lag: thiết kế identity, local state, enqueue và server idempotency.','Process chết sau khi upload 2/5 video: tách work ngắn hạn và durable worker/persistence.','Notification action đánh dấu chat đã đọc khi app chưa mở: tái sử dụng cùng use case.','Refresh feed và optimistic reaction chạy đồng thời: xác định source of truth và stale response policy.','Codebase có 70 pass-through use case: đề xuất tiêu chí giữ, gộp hoặc xóa.'],
'checklist':['Tôi xác định actor goal, precondition và postcondition.','Input/output typed, immutable và không rò framework detail.','Dependency hướng vào contract nhỏ.','Error taxonomy rõ và không nuốt cancellation.','Concurrency, idempotency và transaction semantics được định nghĩa.','Lifecycle thuộc caller hoặc durable scheduler phù hợp.','Resource budget và observability không lộ PII.','Có test failure, cancellation, duplicate và out-of-order.','Không tạo pass-through abstraction vô nghĩa.','Case Upzi được gắn nhãn trung thực.'],
'summary':['Use case biểu diễn mục tiêu nghiệp vụ và application policy, không phải tên mới của repository method.','ViewModel quản lý presentation state; repository quản lý data boundary; use case điều phối hành vi.','Command quan trọng cần idempotency, transaction/reconciliation, cancellation và lifecycle policy.','Không mọi thao tác đều cần use case class; tối ưu clarity và changeability.','Chat, apply, feed refresh và upload là ứng viên mạnh trong Upzi nhưng implementation phải được xác nhận.']}

def para(xs): return [{'type':'paragraph','content':x} for x in xs]
sections=[]
for i,(sid,title) in enumerate(zip(IDS,TITLES)):
    blocks=para(TEXT.get(sid,[]))
    if sid=='minimal-code':
        blocks += [{'type':'code','language':'kotlin','label':'Command use case typed','content':'data class SendInput(val conversationId:String,val text:String)\nsealed interface SendResult { data class Accepted(val clientId:String):SendResult; data class Rejected(val reason:String):SendResult }\nclass SendMessageUseCase(private val repo:ChatRepository, private val ids:IdGenerator){\n suspend operator fun invoke(input:SendInput):SendResult {\n  val text=input.text.trim()\n  if(text.isEmpty()) return SendResult.Rejected("empty_message")\n  val clientId=ids.next()\n  repo.persistPending(input.conversationId,clientId,text)\n  repo.enqueueSend(clientId)\n  return SendResult.Accepted(clientId)\n }\n}'},{'type':'code','language':'kotlin','label':'Query use case reactive','content':'class ObserveConversationUseCase(private val repo:ChatRepository){\n operator fun invoke(id:String):Flow<List<Message>> = repo.observeMessages(id)\n}'}]
    sections.append({'id':sid,'title':title,'blocks':blocks})
quiz=[
('Use case khác repository chủ yếu ở đâu?',['Use case điều phối mục tiêu và policy; repository trừu tượng hóa dữ liệu','Use case luôn gọi Retrofit','Repository quản lý UI state','Không khác'],'A','Use case mô tả hành vi ứng dụng; repository mô tả data boundary.'),
('Khi nào pass-through use case có thể hợp lý?',['Không bao giờ','Khi tạo contract ổn định, reuse hoặc policy có ý nghĩa','Khi muốn tăng file count','Khi repository là interface'],'B','Giá trị phải đến từ boundary hoặc reason to change.'),
('API phù hợp cho command one-shot?',['Flow vô hạn','suspend function với result typed','MutableLiveData','Callback Activity'],'B','Command hữu hạn thường dùng suspend.'),
('Ai sở hữu scope của use case ngắn hạn?',['Use case singleton','Caller như ViewModel','DTO','Database'],'B','Caller quyết định lifecycle.'),
('Xử lý CancellationException đúng?',['Map thành lỗi mạng','Nuốt','Cho truyền tiếp','Retry vô hạn'],'C','Cancellation là coroutine control flow.'),
('Mutex có đủ chống double submit tuyệt đối?',['Có','Không, cần server idempotency/constraint','Chỉ debug','Chỉ Flow'],'B','Mutex chỉ bảo vệ một runtime/process.'),
('Use case có nên trả Retrofit Response?',['Có','Không, map sang contract application/domain','Chỉ Compose','Chỉ worker'],'B','Không nên rò transport detail.'),
('Network và local DB có tự động atomic?',['Có','Không, cần outbox/reconciliation/compensation','Có với coroutine','Có với mutex'],'B','Hai resource không chung local transaction.'),
('Khi nào dùng Flow?',['Mọi operation','Quan sát giá trị thay đổi liên tục','Chỉ upload','Không bao giờ'],'B','Reactive query là trường hợp phù hợp.'),
('UI string nên nằm ở đâu?',['Use case','Presentation/resource mapping','Repository','DTO'],'B','Use case trả category typed.'),
('Granularity dựa trên gì?',['Mỗi endpoint','Actor goal và reason to change','Mỗi table','Mỗi button'],'B','Use case phản ánh mục tiêu có nghĩa.'),
('Thiết kế chưa xác nhận ở Upzi dùng nhãn nào?',['confirmed','inferred','proposed','published'],'C','proposed chỉ rõ đây là phương án thiết kế.')]
sections[-1]['blocks']=[{'type':'quiz','question':q,'options':o,'answer':a,'explanation':e} for q,o,a,e in quiz]
assert [s['id'] for s in sections]==IDS
lesson={'id':'f06','code':'F06','title':'Use Case','summary':'Thiết kế application use case có contract typed, orchestration, error policy, cancellation, idempotency, transaction và testability mà không tạo pass-through boilerplate.','estimatedMinutes':360,'sections':sections}
path=ROOT/'lessons/f/f06.json'; path.parent.mkdir(parents=True,exist_ok=True); path.write_text(json.dumps(lesson,ensure_ascii=False,separators=(',',':')))
catp=ROOT/'catalog.json'; cat=json.loads(catp.read_text())
for ch in cat['chapters']:
 for it in ch['lessons']:
  if it['id']=='f06': it['status']='published'; it['estimatedMinutes']=360
catp.write_text(json.dumps(cat,ensure_ascii=False,indent=2)+'\n')
planp=ROOT/'book-plan.json'; plan=json.loads(planp.read_text());
if 'f06' not in plan['completed']: plan['completed'].append('f06')
plan['current']='f07'; planp.write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
idxp=ROOT/'search-index.json'; idx=json.loads(idxp.read_text()); entry={'id':'f06','code':'F06','title':'Use Case','path':'data/lessons/f/f06.json','chapter':'Architecture','keywords':['use case','interactor','application service','orchestration','idempotency','transaction','cancellation','typed result']}
if isinstance(idx,list): idx=[x for x in idx if x.get('id')!='f06']+[entry]
elif 'lessons' in idx: idx['lessons']=[x for x in idx['lessons'] if x.get('id')!='f06']+[entry]
idxp.write_text(json.dumps(idx,ensure_ascii=False,indent=2)+'\n')
pars=[b['content'] for s in sections for b in s['blocks'] if b['type']=='paragraph']
report={'id':'f06','sections':24,'uniqueSectionIds':24,'exactSectionOrder':True,'paragraphs':len(pars),'paragraphCharacters':sum(map(len,pars)),'codeBlocks':2,'quizQuestions':12,'quizAnswersValid':True,'truthfulnessLabelsPresent':all(x in json.dumps(lesson,ensure_ascii=False) for x in ['confirmed','inferred','proposed','needs-confirmation']),'nextLesson':'f07'}
(ROOT/'validation-f06.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(report)
