import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'android-learning'/'data'; sections=[]
def sec(i,id,title,*paras,codes=None):
 b=[{'type':'paragraph','content':p} for p in paras]
 for label,code in (codes or []): b.append({'type':'code','language':'kotlin','label':label,'content':code})
 sections.append({'id':id,'title':f'{i}. {title}','blocks':b})
sec(1,'objectives','Mục tiêu bài học','Hiểu Service là Android component không có UI, chạy trong process của app và không tự tạo background thread. Phân biệt started service, bound service, foreground service, WorkManager và coroutine scope theo lifetime, scheduling guarantee và user visibility.','Giải thích quy trình startForegroundService rồi gọi startForeground đúng hạn, notification channel, foreground service type, stopSelf, stopService, START_NOT_STICKY, START_REDELIVER_INTENT, binder callback, process death và background execution limits.','Thiết kế upload, media playback, location, data sync hoặc call flow không lạm dụng foreground service; có retry, idempotency, cancellation, persistence và test policy rõ ràng.')
sec(2,'prerequisites','Kiến thức nền','Cần nắm Activity Lifecycle, process death, Context, PendingIntent, Notification, coroutine cancellation và WorkManager cơ bản. Service lifecycle độc lập Activity nhưng vẫn nằm trong app process, nên process chết thì Service và memory state biến mất.','Phải phân biệt công việc cần chạy ngay, công việc có thể trì hoãn, công việc gắn UI và công việc user-visible kéo dài. Đây là tiêu chí chọn API quan trọng hơn việc chỉ hỏi chạy nền bằng gì.')
sec(3,'terminology','Định nghĩa và chú giải thuật ngữ','Started service được khởi động bằng startService hoặc startForegroundService và sống đến khi stopSelf, stopService hoặc hệ thống kết thúc process. Bound service cung cấp IBinder để client bind/unbind; lifetime phụ thuộc client nếu không đồng thời started.','Foreground service là Service làm tác vụ user-noticeable và phải hiển thị ongoing notification. Foreground service type mô tả loại công việc như dataSync, mediaPlayback, location, connectedDevice hoặc phoneCall và có thể kéo theo permission, manifest và runtime restriction.','Sticky mode là giá trị trả về từ onStartCommand quyết định restart sau khi process bị kill: START_NOT_STICKY không yêu cầu restart, START_STICKY có thể restart với null Intent, START_REDELIVER_INTENT gửi lại Intent cuối.','Binder là IPC primitive; local binder dùng cùng process, AIDL dùng cross-process. Notification channel quyết định hành vi hiển thị từ Android 8 trở lên.')
sec(4,'mechanism','Cơ chế hoạt động bên trong','Khi Context gửi startService, ActivityManagerService kiểm tra manifest, background restriction và tạo component trong process app nếu cần. ActivityThread gọi onCreate một lần rồi onStartCommand cho mỗi start request; startId tăng dần giúp stopSelfResult tránh dừng nhầm request mới.','Service callback chạy trên main thread mặc định. Tác vụ blocking phải chuyển sang coroutine dispatcher hoặc executor; nếu block main thread, app vẫn ANR dù code nằm trong Service.','Với startForegroundService, hệ thống cho Service một cửa sổ ngắn để gọi startForeground và đăng notification hợp lệ. Nếu không, hệ thống dừng Service và có thể ném ForegroundServiceDidNotStartInTimeException.','Foreground status tăng importance process nhưng không bảo đảm bất tử. Low-memory kill, force-stop, crash, user stop hoặc policy vẫn có thể kết thúc; state quan trọng phải persist.',codes=[('Foreground service skeleton','''class UploadService : Service() {
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    override fun onCreate() {
        super.onCreate()
        createUploadChannel()
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        startForeground(NOTIFICATION_ID, buildNotification(progress = 0))
        val uploadId = intent?.getStringExtra(EXTRA_UPLOAD_ID)
            ?: return START_NOT_STICKY.also { stopSelf(startId) }
        scope.launch {
            runCatching { repository.resumeUpload(uploadId) }
            stopSelfResult(startId)
        }
        return START_NOT_STICKY
    }

    override fun onDestroy() {
        scope.cancel()
        super.onDestroy()
    }

    override fun onBind(intent: Intent?): IBinder? = null
}''')])
sec(5,'purpose','Mục đích của kỹ thuật','Service tách công việc khỏi lifecycle màn hình. Nó phù hợp khi tác vụ phải tiếp tục dù Activity đổi cấu hình, bị đóng hoặc user chuyển app, nhưng vẫn cần component lifecycle do hệ thống quản lý.','Foreground service thêm transparency: user biết app đang dùng tài nguyên kéo dài, có notification để quay lại hoặc dừng. Đây là contract với hệ điều hành và người dùng, không chỉ mẹo giữ process sống.')
sec(6,'problem','Vấn đề kỹ thuật được giải quyết','Nếu gắn upload, playback hoặc location trực tiếp vào Activity scope, rotation hoặc navigation có thể hủy công việc. Nếu dùng GlobalScope, app mất ownership, cancellation và observability. Service cung cấp owner có lifecycle rõ hơn.','Nếu dùng background service vô hạn, Android hiện đại sẽ hạn chế hoặc dừng vì battery policy. Foreground service giải quyết một số tác vụ tức thời user-visible; WorkManager giải quyết deferred guaranteed work.','Bound service giải quyết giao tiếp stateful giữa client và component dài hạn như media controller, nhưng cần quản lý binder death, client count và unbind an toàn.')
sec(7,'when-to-use','Dấu hiệu cần dùng','Dùng foreground service khi công việc đang diễn ra ngay, kéo dài hơn thao tác UI ngắn, có giá trị trực tiếp với user và cần tiếp tục khi app background: phát nhạc, ghi âm do user kích hoạt, active navigation, active call hoặc upload lớn mà sản phẩm cam kết theo dõi liên tục.','Dùng started service ngắn hạn khi platform còn cho phép và công việc thật sự component-based; trên Android hiện đại phần lớn background work trì hoãn nên chuyển WorkManager.','Dùng bound service khi nhiều UI hoặc client cần điều khiển một engine duy nhất, nhận callback liên tục và lifetime phụ thuộc binding, ví dụ media playback service với MediaSession.')
sec(8,'when-not-to-use','Khi không nên dùng','Không dùng Service chỉ để chạy coroutine sau khi user bấm nút nếu ViewModel scope đủ. Không dùng foreground service cho polling định kỳ, refresh feed, analytics batch hoặc retry không khẩn cấp; WorkManager phù hợp hơn.','Không dùng foreground service để né background restriction, giữ socket luôn sống hoặc giữ app không bị kill. Notification gây phiền, battery cost cao và platform có thể từ chối start từ background.','Không chọn START_STICKY nếu không thể phục hồi state khi Intent null. Không lưu Activity, View hoặc callback UI trực tiếp trong singleton Service.')
sec(9,'requirement','Yêu cầu sản phẩm cụ thể','Upload video phải bắt đầu từ thao tác user, tạo upload record bền trước khi start service, hiển thị notification progress, có cancel action, retry có backoff và idempotency key. Rotation, đóng Activity và process recreation không được tạo upload trùng.','Media playback phải hỗ trợ play, pause, stop từ notification, audio focus, noisy headset, Bluetooth route, MediaSession và foreground transition đúng khi đang phát. Khi dừng playback, Service phải thoát foreground và tự dừng theo policy.','Location tracking chỉ chạy foreground khi user chủ động bắt đầu phiên, notification mô tả rõ, có stop action và tuân foreground service type cùng permission. App không tự khởi động tracking âm thầm sau reboot nếu chưa có consent hợp lệ.','Acceptance criteria gồm start từ foreground và background hợp lệ, Android version matrix, notification permission, process kill, force-stop, user stop, network loss, low storage, duplicate Intent và cancel race.')
sec(10,'analysis','Phân tích dependency, error policy, lifecycle và resource limits','Dependency: Service nhận repository, notification factory và dispatcher qua DI application scope. UI chỉ gửi command chứa ID nhỏ; repository/database là source of truth. Không truyền object lớn hoặc callback qua Intent.','Error policy: phân loại retryable network error, auth failure, permanent validation error và cancellation. Persist trạng thái pending, running, failed, succeeded; retry phải idempotent và có giới hạn. Notification phản ánh trạng thái thật, không báo hoàn tất trước commit server/local.','Lifecycle: onCreate khởi tạo tài nguyên dùng chung; onStartCommand xử lý command; onDestroy cancel scope và close resource nhưng không được xem là callback bảo đảm. Bound service quản lý onBind, onUnbind, onRebind và client ownership.','Resource limits: notification update không nên quá dày; progress cần throttle để tránh Binder và CPU overhead. Wake lock chỉ dùng khi thật cần và phải timeout/release. Network, file descriptor, media codec và location callback phải close/unregister.','Security: Service exported=false nếu chỉ nội bộ. Nếu exported hoặc nhận PendingIntent/action, validate caller, action, extras và permission. Notification action PendingIntent phải immutable hoặc mutable đúng nhu cầu.',codes=[('Command chứa ID nhỏ','''suspend fun startUpload(context: Context, uploadId: String) {
    repository.markQueued(uploadId)
    ContextCompat.startForegroundService(
        context,
        Intent(context, UploadService::class.java)
            .setAction(ACTION_START)
            .putExtra(EXTRA_UPLOAD_ID, uploadId)
    )
}''')])
sec(11,'minimal-code','Ví dụ code tối giản','Foreground service cần notification channel, small icon hợp lệ và content intent. Từ Android 13, notification permission ảnh hưởng khả năng hiển thị trong notification drawer nhưng không thay thế nghĩa vụ startForeground.','Dừng foreground cần quyết định remove notification hay detach. Sau khi công việc kết thúc, gọi stopForeground và stopSelf; nếu có nhiều start request phải tránh request cũ dừng request mới.',codes=[('Cancel PendingIntent và stop','''private fun cancelPendingIntent(context: Context, uploadId: String): PendingIntent {
    val intent = Intent(context, UploadService::class.java)
        .setAction(ACTION_CANCEL)
        .putExtra(EXTRA_UPLOAD_ID, uploadId)
    return PendingIntent.getService(
        context,
        uploadId.hashCode(),
        intent,
        PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
    )
}

private fun finishService(startId: Int) {
    stopForeground(STOP_FOREGROUND_REMOVE)
    stopSelfResult(startId)
}''')])
sec(12,'upzi-case','Ví dụ thực tế Upzi','confirmed: Upzi có media upload, chat socket, notification, deep link và single-activity Compose; các flow này đặt ra câu hỏi rõ về ownership khi app background.','inferred: media upload có thể đang dùng foreground service hoặc WorkManager, nhưng chưa xác nhận implementation, foreground service type, notification progress, retry hay idempotency. proposed: upload lớn dùng persisted upload job và WorkManager hoặc foreground service tùy tính tức thời; socket chat không nên dựa vào service luôn sống, thay bằng push notification và reconnect khi foreground. needs-confirmation: cần kiểm tra manifest, service declarations, notification channels, Android version restrictions và flow cancel/resume trước khi dùng như kinh nghiệm phỏng vấn.')
sec(13,'alternatives','Phương án thay thế','WorkManager phù hợp deferred guaranteed work với constraints, retry và persistence. ViewModel hoặc lifecycleScope phù hợp công việc gắn màn hình. AlarmManager dành cho thời điểm chính xác có yêu cầu thật; JobScheduler là nền tảng mà WorkManager thường dùng.','Media3 MediaSessionService phù hợp playback thay vì tự xây binder, notification và media controls. DownloadManager có thể phù hợp tải file công khai đơn giản.','Coroutine trong singleton repository không thay thế scheduling guarantee; process chết là mất. Push notification và reconnect thường tốt hơn giữ socket bằng foreground service.')
sec(14,'tradeoffs','Lý do lựa chọn và trade-off','Foreground service bắt đầu ngay và user-visible nhưng tiêu hao battery, chiếm notification, chịu permission và type restriction, đồng thời không bảo đảm process sống. WorkManager bền và có retry nhưng thời điểm chạy không tuyệt đối tức thì.','Bound service cho API stateful nhanh nhưng coupling cao và phức tạp khi process hoặc client chết. Flow qua repository đơn giản hơn nếu không cần command đồng bộ hoặc cross-process.','START_REDELIVER_INTENT giúp nhận lại command nhưng có nguy cơ duplicate nếu operation không idempotent. START_NOT_STICKY an toàn hơn cho tác vụ có record bền và scheduler riêng.')
sec(15,'edge-cases','Edge cases','App gọi startForegroundService khi background nhưng không thuộc exemption có thể ném ForegroundServiceStartNotAllowedException. Notification permission bị từ chối, channel bị tắt hoặc user stop app từ task manager cần UX fallback.','Service nhận nhiều Intent nhanh; startId cũ hoàn tất sau request mới. Dùng stopSelfResult và state machine theo job ID để không dừng nhầm.','Process chết giữa upload chunk và commit server; phải resume theo offset hoặc query server, không giả định callback success đã persist.','ACTION_CANCEL đến đúng lúc upload vừa hoàn tất; cancellation và completion phải atomic hoặc có precedence rule.','Boot, app update, logout, token expiry, account switch, roaming và metered network có thể làm job cũ không còn hợp lệ. Revalidate user và session trước khi tiếp tục.','Android OEM có battery manager mạnh; không hứa chạy bất tử. Quan sát telemetry và thiết kế resume.',codes=[('Idempotent command handling','''override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    when (intent?.action) {
        ACTION_CANCEL -> repository.cancel(intent.requireUploadId())
        ACTION_START -> launchUploadOnce(intent.requireUploadId(), startId)
        else -> stopSelf(startId)
    }
    return START_NOT_STICKY
}''')])
sec(16,'mistakes','Sai lầm thường gặp','Lỗi phổ biến: nghĩ Service có thread riêng, block main thread trong onStartCommand, quên gọi startForeground sớm, notification thiếu small icon hoặc channel, start foreground service từ background không hợp lệ và chọn type sai.','Không persist job trước start; truyền file bytes hoặc Parcelable lớn qua Intent; dùng START_STICKY nhưng không xử lý null Intent; update notification mỗi byte; không stop foreground khi xong.','Giữ socket bằng foreground service vô thời hạn, dùng wake lock không timeout, quên unregister receiver/location callback, callback Service giữ Activity và không xử lý process death.')
sec(17,'interview-basic','Câu hỏi phỏng vấn cơ bản','Service là gì; có chạy background thread không; started khác bound service; foreground service cần gì; startService khác startForegroundService; onStartCommand trả về gì; stopSelf khác stopService; WorkManager khác Service.','Câu trả lời tốt nhấn mạnh component lifecycle, main-thread callback, process không được bảo đảm, user-visible notification và chọn API theo urgency cùng durability.')
sec(18,'interview-deep','Câu hỏi xoáy sâu và câu hỏi bẫy','Tại sao foreground service vẫn bị kill; xử lý process death giữa upload; START_STICKY nhận null Intent; stopSelfResult giải quyết race nào; bound và started cùng lúc thì lifetime ra sao; Binder callback khi client chết; foreground service type ảnh hưởng gì.','Bẫy: notification permission bị từ chối thì có được bỏ startForeground không; Service có thay WorkManager không; onDestroy có luôn gọi không; foreground service có giữ socket 24/7 an toàn không; startForegroundService có thể gọi từ mọi background state không.')
sec(19,'experience-answer','Mẫu trả lời gắn với kinh nghiệm','Tôi chọn Service sau khi xác định công việc cần tiếp tục ngoài UI và cần chạy ngay. Job metadata được persist trước, Service chỉ nhận ID, notification progress có throttle, operation idempotent, scope bị cancel khi destroy và trạng thái được resume từ repository sau process death.','Với Upzi, confirmed là có media upload, chat và notification flow. Tôi chỉ nói foreground service đã dùng nếu repository xác nhận; nếu chưa, mô tả đó là proposed architecture và nêu WorkManager là phương án thay thế cho upload trì hoãn.')
sec(20,'practice','Bài tập thực hành','Xây upload foreground service nhận uploadId, lưu Room state, notification progress/cancel, retry network, stopSelfResult và test process kill. Không truyền Uri nếu không giữ persisted permission hoặc copy vào app storage.','Xây bound playback service tối giản có binder play/pause và StateFlow; sau đó so với Media3 MediaSessionService.','Chuyển một periodic sync đang dùng Service sang WorkManager; ghi rõ thay đổi về timing, constraints, retry và user visibility.')
sec(21,'scenario','Bài tập tình huống','User chọn video 1 GB rồi khóa màn hình. Chọn foreground service hay WorkManager theo product promise; thiết kế notification, metered network, charging constraint, resume offset và cancel.','Chat cần nhận tin mới khi app bị kill. Phân tích vì sao foreground socket không phải mặc định; thiết kế push notification, deep link và reconnect/dedup.','Navigation app theo dõi GPS, user thu hồi permission giữa phiên. Mô tả Service type, permission check, notification, stop policy và state UI.')
sec(22,'checklist','Checklist tự đánh giá','Tôi biết Service không có thread riêng; phân biệt started, bound, foreground và WorkManager; hiểu lifecycle, startId, sticky mode và process death.','Tôi biết khai báo notification channel, foreground service type và permission, gọi startForeground đúng hạn, stop đúng lúc và validate background start restriction.','Tôi persist job, dùng ID nhỏ, idempotency/retry/cancel rõ, giới hạn notification update và không giữ UI reference.','Tôi phân biệt confirmed, inferred, proposed và needs-confirmation khi nói về Upzi.')
sec(23,'summary','Tóm tắt cần nhớ','Service là component lifecycle, không phải scheduler bảo đảm và không tự chạy background thread. Foreground service là contract cho tác vụ user-visible đang chạy ngay, có notification và restriction nghiêm ngặt.','Dùng WorkManager cho deferred guaranteed work; dùng ViewModel cho work gắn UI; dùng Media3 cho playback. Persist state quan trọng vì process có thể chết bất kỳ lúc nào.','Thiết kế production cần idempotency, cancellation, retry, notification, foreground type, security, resource cleanup và Android version matrix.')
sec(24,'quiz-guide','Quiz có giải thích đáp án','Quiz tập trung vào lựa chọn API và failure mode, không chỉ nhớ callback. Với mỗi tình huống hãy trả lời urgency, visibility, durability, process death và user control.','Khi có nhiều đáp án nghe hợp lý, chọn phương án ít đặc quyền nhất nhưng vẫn đáp ứng requirement.')
quiz=[]
def q(i,question,correct,explanation,*options): quiz.append({'id':f'q{i}','question':question,'options':[{'id':chr(97+j),'text':o} for j,o in enumerate(options)],'correctOptionIds':[chr(97+correct)],'explanation':explanation})
q(1,'Service callback chạy trên thread nào mặc định?',0,'Lifecycle callback của Service chạy trên main thread nếu không tự chuyển dispatcher.','Main thread','IO thread','Binder thread luôn luôn','Thread mới tự động')
q(2,'Periodic feed refresh nên ưu tiên API nào?',2,'Deferred, guaranteed và constraint-aware work phù hợp WorkManager hơn foreground service.','Foreground service vô hạn','GlobalScope','WorkManager','Bound service')
q(3,'Sau startForegroundService, Service cần làm gì?',1,'Phải gọi startForeground với notification hợp lệ trong thời hạn platform.','Chờ Activity bind','Gọi startForeground sớm','Chỉ tạo channel','Gọi stopSelf ngay')
q(4,'Foreground service có bất tử không?',1,'Nó tăng importance nhưng process vẫn có thể bị kill hoặc user/system dừng.','Có','Không','Chỉ Android 8','Chỉ khi notification bật')
q(5,'START_STICKY có thể gọi lại onStartCommand với gì?',2,'Hệ thống có thể restart Service với Intent null.','Activity mới','Binder mới','Intent null','Notification null bắt buộc')
q(6,'Tại sao dùng stopSelfResult(startId)?',0,'Nó tránh request cũ dừng Service khi request mới hơn đã đến.','Tránh race nhiều start','Tạo notification','Bind client','Xin permission')
q(7,'Nên truyền gì qua Intent cho upload lớn?',3,'Chỉ truyền ID nhỏ và đọc state hoặc file từ storage bền.','ByteArray video','Bitmap','Repository object','uploadId')
q(8,'Chat nhận tin khi app bị kill nên mặc định dùng gì?',1,'Push notification rồi reconnect và dedup phù hợp hơn foreground socket liên tục.','Foreground socket 24/7','Push notification','Alarm mỗi phút','Activity luôn mở')
q(9,'Foreground service notification update nên thế nào?',2,'Throttle progress để giảm Binder, CPU và notification churn.','Mỗi byte','Không bao giờ cập nhật','Có throttle','Chỉ khi app foreground')
q(10,'Bound service chỉ còn client cuối unbind và không started thì sao?',0,'Service có thể bị destroy vì không còn reason sống.','Có thể bị destroy','Luôn sống','Tự thành foreground','Process tự restart')
q(11,'onDestroy có phải nơi bảo đảm persist cuối cùng không?',1,'Process có thể bị kill mà callback không chạy; phải persist trong quá trình.','Có','Không','Chỉ debug','Chỉ bound service')
q(12,'Upload cần resume sau process death cần yếu tố nào quan trọng nhất?',3,'Persisted job state và idempotent hoặc resumable protocol là nền tảng.','Activity static','START_STICKY duy nhất','Wake lock vô hạn','Persisted state và idempotency')
lesson={'id':'e05','code':'E05','title':'Service và Foreground Service','summary':'Thiết kế started, bound và foreground service đúng lifecycle; chọn WorkManager khi phù hợp; xử lý notification, restriction, process death, retry, cancellation và idempotency.','estimatedMinutes':360,'sections':sections,'quiz':quiz}
path=DATA/'lessons'/'e'/'e05.json'; path.parent.mkdir(parents=True,exist_ok=True); path.write_text(json.dumps(lesson,ensure_ascii=False,separators=(',',':')))
required=['objectives','prerequisites','terminology','mechanism','purpose','problem','when-to-use','when-not-to-use','requirement','analysis','minimal-code','upzi-case','alternatives','tradeoffs','edge-cases','mistakes','interview-basic','interview-deep','experience-answer','practice','scenario','checklist','summary','quiz-guide']
ids=[s['id'] for s in sections]; paras=[b['content'] for s in sections for b in s['blocks'] if b['type']=='paragraph']; codes=[b for s in sections for b in s['blocks'] if b['type']=='code']; assert ids==required and len(set(ids))==24 and len(paras)>=40 and sum(map(len,paras))>=9000 and len(codes)>=4 and len(quiz)>=10
text=path.read_text(); assert all(x in text for x in ['confirmed:','inferred:','proposed:','needs-confirmation:'])
cp=DATA/'catalog.json'; c=json.loads(cp.read_text())
for ch in c['chapters']:
 for item in ch['lessons']:
  if item['id']=='e05': assert item['status']=='planned'; item['status']='published'; item['estimatedMinutes']=360
cp.write_text(json.dumps(c,ensure_ascii=False,indent=2)+'\n')
pp=DATA/'book-plan.json'; p=json.loads(pp.read_text()); assert p['current']=='e05'; p['completed'].append('e05'); p['current']='e06'; pp.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
ip=DATA/'search-index.json'; idx=json.loads(ip.read_text()); idx=[x for x in idx if x.get('lessonId')!='e05']; idx.append({'lessonId':'e05','code':'E05','title':'Service và Foreground Service','keywords':['Service','Foreground Service','started service','bound service','onStartCommand','startForegroundService','notification channel','foreground service type','START_STICKY','START_NOT_STICKY','IBinder','WorkManager','process death','idempotency'],'headings':['Service lifecycle','Started and bound service','Foreground service contract','Notification and service types','Background start restrictions','Process death and restart modes','WorkManager alternatives','Upzi case study']}); ip.write_text(json.dumps(idx,ensure_ascii=False,indent=2)+'\n')
report={'id':'e05','sections':24,'uniqueSectionIds':24,'exactSectionOrder':True,'paragraphs':len(paras),'paragraphCharacters':sum(map(len,paras)),'codeBlocks':len(codes),'quizQuestions':len(quiz),'quizAnswersValid':True,'truthfulnessLabelsPresent':True,'nextLesson':'e06'}; (ROOT/'validation-e05.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n'); print(json.dumps(report,ensure_ascii=False))