import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'android-learning'/'data'; sections=[]
def sec(i,id,title,*paras,codes=None):
 b=[{'type':'paragraph','content':p} for p in paras]
 for label,code in (codes or []): b.append({'type':'code','language':'kotlin','label':label,'content':code})
 sections.append({'id':id,'title':f'{i}. {title}','blocks':b})
sec(1,'objectives','Mục tiêu bài học','Hiểu BroadcastReceiver là component nhận Intent broadcast trong thời gian rất ngắn, còn PendingIntent là capability token cho phép hệ thống hoặc app khác thực hiện một Intent thay mặt app trong tương lai. Người học phải phân biệt explicit, implicit, ordered, sticky, manifest-registered và context-registered broadcast.','Mục tiêu thực hành là đăng ký receiver đúng lifecycle, xử lý background execution limits, dùng goAsync an toàn, thiết kế PendingIntent mutable hoặc immutable đúng mục đích, tránh collision requestCode, bảo vệ exported surface và xây notification action có semantics chính xác.')
sec(2,'prerequisites','Kiến thức nền','Cần nắm Intent, component, process lifecycle, Service, Foreground Service, WorkManager, notification, permission và Android version compatibility. BroadcastReceiver không phải nơi chạy tác vụ dài, và PendingIntent không phải callback object trong memory.','Cần hiểu app process có thể chưa tồn tại khi broadcast đến; hệ thống có thể tạo process, gọi receiver rồi kết thúc sau callback. Vì vậy receiver không được phụ thuộc state singleton chưa được khởi tạo đầy đủ.')
sec(3,'terminology','Định nghĩa và chú giải thuật ngữ','Broadcast là Intent được gửi tới một hoặc nhiều receiver. Explicit broadcast chỉ định component hoặc package; implicit broadcast mô tả action/data/category để hệ thống resolve receiver phù hợp.','Manifest receiver được khai báo trong AndroidManifest và có thể nhận một số broadcast khi app không chạy. Context-registered receiver chỉ sống trong khoảng registerReceiver đến unregisterReceiver.','Ordered broadcast cho phép receiver chạy theo thứ tự và truyền result; sticky broadcast giữ Intent gần nhất nhưng phần lớn API sticky cũ không nên dùng cho app thông thường.','PendingIntent đóng gói Intent cùng identity của app tạo nó. Immutable nghĩa dữ liệu không thể bị caller thay đổi; mutable chỉ nên dùng khi hệ thống cần fill-in data như RemoteInput.')
sec(4,'mechanism','Cơ chế hoạt động bên trong','Khi sendBroadcast được gọi, system server resolve danh sách receiver, áp dụng package visibility, permission, exported rule và background restriction rồi dispatch callback onReceive. Receiver chạy trên main thread nếu không dùng executor hoặc cơ chế khác.','onReceive phải hoàn tất nhanh. goAsync trả PendingResult để tiếp tục một lượng công việc ngắn ngoài callback, nhưng process vẫn có thể bị kill nếu vượt giới hạn hoặc app không chuyển workload bền vững sang WorkManager/Service.','PendingIntent identity dựa trên loại operation, package, requestCode và các phần Intent dùng trong filterEquals; extras thường không tham gia identity. Vì thế hai PendingIntent khác extras nhưng cùng identity có thể cập nhật hoặc ghi đè nhau tùy flag.','Hệ thống giữ token PendingIntent độc lập với object Kotlin. Khi notification action được bấm sau process death, token vẫn có thể khởi tạo component của app với Intent đã đóng gói.',codes=[('Receiver lifecycle-aware','''@Composable
fun ConnectivityEvents(onChanged: () -> Unit) {
    val context = LocalContext.current
    val latest by rememberUpdatedState(onChanged)
    DisposableEffect(context) {
        val receiver = object : BroadcastReceiver() {
            override fun onReceive(context: Context, intent: Intent) = latest()
        }
        ContextCompat.registerReceiver(
            context, receiver,
            IntentFilter(ACTION_CONNECTIVITY_CHANGED),
            ContextCompat.RECEIVER_NOT_EXPORTED
        )
        onDispose { context.unregisterReceiver(receiver) }
    }
}''')])
sec(5,'purpose','Mục đích của kỹ thuật','BroadcastReceiver phù hợp để bridge event platform hoặc cross-component event ngắn: boot completed, package changes, alarm, notification action, locale/time changes và custom explicit event nội bộ.','PendingIntent cho phép notification, alarm, widget, shortcut hoặc hệ thống thực hiện hành động sau này bằng quyền của app mà không cần giữ process sống. Đây là capability cần được thiết kế như security boundary.')
sec(6,'problem','Vấn đề kỹ thuật được giải quyết','Không có receiver, app khó phản ứng với event platform ngoài lifecycle Activity. Không có PendingIntent, notification action không thể gọi lại app đáng tin cậy sau process death.','Sai thiết kế dẫn tới ANR trong onReceive, receiver leak, duplicate registration, notification action mở nhầm màn, stale extras, privilege escalation qua mutable PendingIntent hoặc receiver exported ngoài ý muốn.')
sec(7,'when-to-use','Dấu hiệu cần dùng','Dùng BroadcastReceiver khi event đến từ Android framework hoặc component khác dưới dạng Intent và handler chỉ cần quyết định nhanh, persist tối thiểu hoặc enqueue công việc tiếp theo.','Dùng PendingIntent cho notification content/action, AlarmManager, app widget, media control, location/geofence callback và API hệ thống yêu cầu token thực thi trong tương lai.')
sec(8,'when-not-to-use','Khi không nên dùng','Không dùng broadcast như event bus nội bộ cho mọi UI state; Flow, callback hoặc repository observable thường rõ ownership hơn. Không dùng receiver để upload, sync dài, decode video hoặc gọi nhiều API.','Không dùng mutable PendingIntent khi không bắt buộc. Không dùng implicit custom broadcast chứa dữ liệu nhạy cảm. Không rely vào manifest implicit broadcast bị hạn chế trên Android mới nếu platform không còn cho phép.')
sec(9,'requirement','Yêu cầu sản phẩm cụ thể','Notification chat phải có content action mở đúng conversationId và action reply dùng RemoteInput; action mark-as-read phải idempotent, không mở Activity và vẫn chạy đúng sau process death.','Upload notification phải có cancel action trỏ đúng uploadId, không collision giữa nhiều upload đồng thời. PendingIntent của mỗi job phải stable nhưng không stale khi notification update.','Receiver cho boot hoặc package update chỉ enqueue WorkManager unique work, không làm network trực tiếp. Receiver không exported trừ khi có contract cross-app rõ và permission bảo vệ.','Acceptance criteria gồm tap nhiều notification khác nhau, process kill, reboot, duplicate action, stale notification, account switch, Android version matrix và security test từ app ngoài.')
sec(10,'analysis','Phân tích dependency, error policy, lifecycle và resource limits','Dependency: receiver nên gọi use case nhỏ hoặc scheduler application-scoped; UI state không nằm trong receiver. PendingIntent builder nhận stable business ID và route contract, không phụ thuộc singleton in-memory.','Error policy: onReceive không throw ra framework; parse Intent defensively, validate action, URI, account và extras. Nếu công việc cần retry, persist command rồi enqueue WorkManager.','Lifecycle: context receiver đăng ký ở STARTED/RESUMED tùy nhu cầu và unregister đối xứng. Manifest receiver chỉ khai báo khi cần wake app hoặc nhận platform event hỗ trợ.','Resource limits: onReceive có ngân sách thời gian ngắn; binder extras có size limit; notification action có thể đến nhiều lần; ordered broadcast có thể bị chậm bởi receiver trước.','Security: explicit component, package scoping, android:exported, receiver permission, immutable PendingIntent và input validation là lớp bảo vệ chính. PendingIntent trao quyền của creator nên không được để caller kiểm soát component hoặc data nhạy cảm.',codes=[('goAsync chuyển sang durable work','''class BootReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        if (intent.action != Intent.ACTION_BOOT_COMPLETED) return
        WorkManager.getInstance(context).enqueueUniqueWork(
            "post-boot-sync",
            ExistingWorkPolicy.KEEP,
            OneTimeWorkRequestBuilder<PostBootSyncWorker>().build()
        )
    }
}''')])
sec(11,'minimal-code','Ví dụ code tối giản','PendingIntent nên dùng explicit Intent, requestCode hoặc data URI ổn định theo business identity và FLAG_IMMUTABLE mặc định. FLAG_UPDATE_CURRENT cập nhật extras của token cùng identity nhưng không tạo identity mới.','RemoteInput là trường hợp phổ biến cần mutable PendingIntent vì hệ thống phải gắn kết quả reply vào Intent trước khi gửi.',codes=[('Notification actions','''fun chatPendingIntent(context: Context, conversationId: String): PendingIntent {
    val intent = Intent(context, MainActivity::class.java).apply {
        action = "OPEN_CHAT"
        data = Uri.parse("upzi://chat/$conversationId")
    }
    return PendingIntent.getActivity(
        context,
        conversationId.hashCode(),
        intent,
        PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
    )
}''')])
sec(12,'upzi-case','Ví dụ thực tế Upzi','confirmed: Upzi có chat, FCM/deep link, notification-driven navigation, upload và single-activity Compose; các flow này có nhu cầu PendingIntent identity, process-death delivery và route validation.','inferred: notification action hoặc receiver hiện tại có thể dùng requestCode/data URI để phân biệt conversation và job, nhưng chưa xác nhận implementation. proposed: chuẩn hóa PendingIntentFactory, immutable-by-default, unique data URI, receiver not-exported và enqueue WorkManager cho durable work. needs-confirmation: cần kiểm tra manifest receivers, notification builder, FCM action handling, RemoteInput và security flags trước khi kể là đã áp dụng.')
sec(13,'alternatives','Phương án thay thế','Flow/StateFlow hoặc callback thay custom broadcast nội bộ trong cùng process. WorkManager thay receiver cho phần execution dài; receiver chỉ là trigger.','Activity Result API thay broadcast cho request-response UI. Direct service binding hoặc repository command thay ordered broadcast nếu cần contract chặt và typed result.','AlarmManager cần PendingIntent cho thời điểm chính xác; WorkManager phù hợp deferred work có constraint. Không nên chọn chỉ dựa thói quen.')
sec(14,'tradeoffs','Lý do lựa chọn và trade-off','Manifest receiver nhận được khi process chưa chạy nhưng tăng exported/security surface và chịu platform restrictions. Context receiver dễ kiểm soát lifecycle nhưng bỏ lỡ event khi chưa đăng ký.','Explicit broadcast an toàn và predictable hơn nhưng coupling component; implicit broadcast linh hoạt hơn nhưng resolve rộng, khó kiểm soát và nhiều action bị hạn chế.','FLAG_UPDATE_CURRENT tiện cập nhật notification nhưng dễ stale/collision nếu identity sai. requestCode unique đơn giản nhưng data URI thường biểu diễn domain identity rõ hơn.','Mutable PendingIntent hỗ trợ RemoteInput/fill-in nhưng tăng attack surface; immutable nên là mặc định.')
sec(15,'edge-cases','Edge cases','Hai notification dùng cùng PendingIntent identity nhưng extras khác có thể mở cùng conversation cuối cùng do FLAG_UPDATE_CURRENT. Phải dùng requestCode/data khác nhau.','Notification cũ sau logout có thể deliver action cho account mới; receiver phải validate accountId/session generation và bỏ command stale.','Receiver có thể nhận duplicate broadcast, redelivery hoặc user tap nhiều lần; side effect phải idempotent.','Dynamic receiver unregister hai lần gây exception; registration state cần owner rõ. Compose recomposition với key sai có thể register nhiều receiver.','RemoteInput reply cần mutable PendingIntent trên version yêu cầu; nhưng chỉ component/extras cần thiết được phép fill-in.','Direct Boot mode trước unlock chỉ truy cập device-protected storage; credential-protected database chưa sẵn sàng.','Android 13+ notification permission ảnh hưởng visibility của notification nhưng PendingIntent contract và receiver security vẫn phải đúng.',codes=[('RemoteInput reply','''val replyIntent = Intent(context, ReplyReceiver::class.java).apply {
    action = ACTION_REPLY
    putExtra(EXTRA_CONVERSATION_ID, conversationId)
}
val replyPendingIntent = PendingIntent.getBroadcast(
    context,
    conversationId.hashCode(),
    replyIntent,
    PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_MUTABLE
)''')])
sec(16,'mistakes','Sai lầm thường gặp','Lỗi phổ biến: làm network trong onReceive, dùng GlobalScope sau goAsync, quên finish PendingResult, register receiver bằng Activity Context rồi không unregister và khai báo receiver exported không cần thiết.','PendingIntent mistakes: dùng requestCode 0 cho mọi notification, nghĩ extras tạo identity, dùng FLAG_MUTABLE mặc định, Intent implicit, thiếu package/component và dùng FLAG_CANCEL_CURRENT gây hành vi bất ngờ.','Một lỗi khác là tin rằng notification tap chỉ xảy ra khi app đang chạy; thực tế process có thể cold start và toàn bộ singleton state trống.')
sec(17,'interview-basic','Câu hỏi phỏng vấn cơ bản','Câu hỏi nền: BroadcastReceiver là gì; manifest và dynamic receiver khác nhau; onReceive chạy thread nào; goAsync dùng khi nào; PendingIntent là gì; immutable khác mutable; requestCode có vai trò gì.','Mẫu trả lời tốt phải nói receiver là entry point ngắn, không phải background thread; PendingIntent là system-held capability token với identity riêng, sống qua process death.')
sec(18,'interview-deep','Câu hỏi xoáy sâu và câu hỏi bẫy','Câu xoáy: extras có tham gia PendingIntent identity không; tại sao notification mở sai item; receiver exported có rủi ro gì; ordered broadcast có phù hợp app architecture không; goAsync có bảo đảm process sống không.','Câu bẫy: FLAG_UPDATE_CURRENT có làm mutable token không; immutable PendingIntent có cập nhật extras bởi creator được không; manifest receiver có nhận mọi implicit broadcast không; onReceive có thể suspend trực tiếp không.')
sec(19,'experience-answer','Mẫu trả lời gắn với kinh nghiệm','Tôi thiết kế receiver như adapter mỏng: validate Intent, persist business ID và enqueue unique WorkManager. Tác vụ dài, retry và network không nằm trong onReceive.','Với notification, tôi tạo PendingIntent explicit, immutable mặc định và dùng data URI/requestCode theo entity để tránh collision. RemoteInput là ngoại lệ có kiểm soát cần mutable.','Khi nói về Upzi, chỉ khẳng định confirmed là có chat, deep link và notification-related flow; implementation flags và receivers phải ghi inferred/proposed nếu chưa audit.')
sec(20,'practice','Bài tập thực hành','Tạo ba notification chat khác nhau, mỗi notification mở đúng conversation sau process kill. Cố tình dùng cùng requestCode để tái hiện collision rồi sửa bằng data URI.','Tạo mark-as-read BroadcastReceiver chỉ nhận explicit Intent, validate account và enqueue unique work. Test tap lặp năm lần nhưng server mutation chỉ xảy ra một lần.','Tạo RemoteInput reply, so sánh immutable và mutable PendingIntent, giải thích vì sao chỉ action này cần mutable.','Viết test đăng ký/unregister receiver theo lifecycle và bảo đảm không duplicate sau rotation.')
sec(21,'scenario','Bài tập tình huống','User nhận hai notification từ hai account, logout rồi login account khác trước khi bấm notification cũ. Thiết kế validation và fallback navigation.','Upload A và B cùng chạy; cancel action của B lại hủy A. Phân tích PendingIntent identity, requestCode, data URI và FLAG_UPDATE_CURRENT.','BOOT_COMPLETED đến khi database credential-protected chưa mở. Mô tả direct boot storage, deferred initialization và WorkManager strategy.')
sec(22,'checklist','Checklist tự đánh giá','Tôi phân biệt manifest và dynamic receiver, biết onReceive budget, goAsync và khi nào chuyển WorkManager.','Tôi hiểu PendingIntent identity, explicit Intent, requestCode, data URI, UPDATE/CANCEL/ONE_SHOT flags và immutable/mutable security.','Tôi kiểm tra exported, permission, input validation, duplicate delivery, process death, account switch và notification collision.','Tôi biết chi tiết Upzi nào confirmed và chi tiết nào cần xác nhận.')
sec(23,'summary','Tóm tắt cần nhớ','BroadcastReceiver là entry point ngắn để phản ứng Intent; không phải nơi giữ process hoặc chạy job dài. Receiver tốt chỉ validate, persist và schedule.','PendingIntent là capability token do hệ thống giữ và thực thi bằng identity của app creator. Immutable là mặc định; mutable chỉ dùng khi caller hợp lệ cần fill-in data.','Identity không dựa chủ yếu vào extras, nên notification action phải có requestCode hoặc data URI domain-specific. Security và idempotency quan trọng ngang lifecycle.')
sec(24,'quiz-guide','Quiz có giải thích đáp án','Làm quiz sau khi có thể giải thích một notification action từ lúc tạo token tới cold-start receiver/Activity và chỉ ra mọi security boundary.','Với mỗi câu, nêu lifetime, identity, exported rule, thread và fallback sang WorkManager nếu công việc không còn ngắn.')
quiz=[]
def q(i,question,correct,explanation,*options): quiz.append({'id':f'q{i}','question':question,'options':[{'id':chr(97+j),'text':o} for j,o in enumerate(options)],'correctOptionIds':[chr(97+correct)],'explanation':explanation})
q(1,'onReceive mặc định chạy ở đâu?',0,'Receiver callback mặc định chạy trên main thread của process.','Main thread','IO thread','Binder pool tùy ý','WorkManager thread')
q(2,'Tác vụ network dài sau broadcast nên làm gì?',2,'Receiver nên enqueue durable work thay vì giữ onReceive.','Chạy trực tiếp','GlobalScope','Enqueue WorkManager','Thread.sleep')
q(3,'Extras có quyết định PendingIntent identity chính không?',1,'Intent filter identity và requestCode quan trọng; extras thường không tham gia.','Có','Không','Chỉ Android 14','Chỉ notification')
q(4,'Flag mặc định an toàn cho PendingIntent thường là gì?',0,'Immutable giảm khả năng caller sửa Intent.','FLAG_IMMUTABLE','FLAG_MUTABLE','FLAG_ONE_SHOT','Không flag')
q(5,'Khi nào cần mutable PendingIntent?',2,'RemoteInput cần hệ thống fill-in reply data.','Mọi notification','Mở Activity','RemoteInput reply','Alarm đơn giản')
q(6,'Manifest receiver có ưu điểm gì?',1,'Có thể nhận một số event khi process chưa chạy.','Luôn nhận mọi implicit broadcast','Có thể wake app cho event được hỗ trợ','Không cần security','Chạy background thread')
q(7,'goAsync bảo đảm process sống vô hạn không?',1,'Nó chỉ kéo dài xử lý ngắn; không thay durable scheduler.','Có','Không','Chỉ khi charging','Chỉ API 33+')
q(8,'Hai notification mở sai cùng item thường do gì?',0,'PendingIntent collision vì cùng identity/requestCode/data.','Cùng PendingIntent identity','Compose recomposition','Notification channel','Dark mode')
q(9,'Receiver không dùng cross-app nên cấu hình gì?',2,'Not exported giảm attack surface.','exported=true','permission trống','not exported','ordered=true')
q(10,'Broadcast nội bộ cùng process thường thay bằng gì?',1,'Flow/callback cho typed lifecycle-aware communication.','Sticky broadcast','Flow hoặc callback','Manifest receiver','AlarmManager')
q(11,'Cancel action cần đặc tính gì?',3,'Phải map đúng job và idempotent khi tap lặp.','Chỉ chạy khi app foreground','Dùng requestCode 0','Implicit Intent','Identity theo job và idempotent')
q(12,'Sau logout, notification cũ nên xử lý thế nào?',0,'Validate account/session trước side effect hoặc navigation.','Validate session/account','Luôn mở màn cũ','Bỏ qua auth','Khởi tạo singleton giả')
lesson={'id':'e07','code':'E07','title':'BroadcastReceiver và PendingIntent','summary':'Hiểu receiver như entry point ngắn và PendingIntent như capability token, từ lifecycle, identity, notification action đến security, process death và durable handoff.','estimatedMinutes':360,'sections':sections,'quiz':quiz}
lesson_path=DATA/'lessons'/'e'/'e07.json'; lesson_path.parent.mkdir(parents=True,exist_ok=True); lesson_path.write_text(json.dumps(lesson,ensure_ascii=False,separators=(',',':')))
required=['objectives','prerequisites','terminology','mechanism','purpose','problem','when-to-use','when-not-to-use','requirement','analysis','minimal-code','upzi-case','alternatives','tradeoffs','edge-cases','mistakes','interview-basic','interview-deep','experience-answer','practice','scenario','checklist','summary','quiz-guide']
ids=[s['id'] for s in sections]; paragraphs=[b['content'] for s in sections for b in s['blocks'] if b['type']=='paragraph']; codes=[b for s in sections for b in s['blocks'] if b['type']=='code']; assert ids==required and len(set(ids))==24 and len(paragraphs)>=45 and sum(map(len,paragraphs))>=10000 and len(codes)>=4 and len(quiz)>=10
text=lesson_path.read_text(); assert all(x in text for x in ['confirmed:','inferred:','proposed:','needs-confirmation:'])
catalog_path=DATA/'catalog.json'; catalog=json.loads(catalog_path.read_text())
for chapter in catalog['chapters']:
 for item in chapter['lessons']:
  if item['id']=='e07': assert item['status']=='planned'; item['status']='published'; item['estimatedMinutes']=360
catalog_path.write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
plan_path=DATA/'book-plan.json'; plan=json.loads(plan_path.read_text()); assert plan['current']=='e07'; plan['completed'].append('e07'); plan['current']='e08'; plan_path.write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
index_path=DATA/'search-index.json'; index=json.loads(index_path.read_text()); index=[x for x in index if x.get('lessonId')!='e07']; index.append({'lessonId':'e07','code':'E07','title':'BroadcastReceiver và PendingIntent','keywords':['BroadcastReceiver','PendingIntent','notification action','RemoteInput','immutable','mutable','requestCode','data URI','exported','goAsync','ordered broadcast','BOOT_COMPLETED'],'headings':['Broadcast dispatch','Receiver lifecycle','PendingIntent identity','Notification actions','RemoteInput','Security boundaries','Process death','WorkManager handoff']}); index_path.write_text(json.dumps(index,ensure_ascii=False,indent=2)+'\n')
report={'id':'e07','sections':24,'uniqueSectionIds':24,'exactSectionOrder':True,'paragraphs':len(paragraphs),'paragraphCharacters':sum(map(len,paragraphs)),'codeBlocks':len(codes),'quizQuestions':len(quiz),'quizAnswersValid':True,'truthfulnessLabelsPresent':True,'nextLesson':'e08'}; (ROOT/'validation-e07.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n'); print(json.dumps(report,ensure_ascii=False))