(()=>{
 const q=new URLSearchParams(location.search); if(q.get('app')!=='werewolf'&&location.hash!=='#werewolf') return;
 const roles=window.WEREWOLF_ROLES||[];
 let names=['Người 1','Người 2','Người 3','Người 4','Người 5'];
 let counts=Object.fromEntries(roles.map(r=>[r.id,r.defaultCount||0]));
 let deck=[], center=[];
 document.body.innerHTML='<main id="root"></main>';
 document.body.style.background='#0b0d14'; document.body.style.color='#f6f1df'; document.body.style.fontFamily='-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif';
 const root=document.getElementById('root'); root.style.cssText='max-width:860px;margin:auto;padding:16px';
 const roleName=id=>(roles.find(r=>r.id===id)||{}).vi||id;
 const speak=t=>{ if(!window.speechSynthesis)return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(t); u.lang='vi-VN'; u.rate=.95; speechSynthesis.speak(u); };
 const shuffle=a=>{a=a.slice();for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
 function paint(){const need=names.length+3,total=Object.values(counts).reduce((s,n)=>s+n,0);root.innerHTML=`<section><a href="./" style="color:#f4c430;font-weight:900">← MyGym</a><h1>Quản trò Ma Sói Một Đêm</h1><p>Chia bài nhanh và đọc lời quản trò bằng giọng nói.</p></section><section><label>Số người chơi <input id="num" type="number" min="3" max="12" value="${names.length}"></label><p>Cần ${need} lá · đang chọn ${total} lá</p><div>${roles.map(r=>`<div class="role"><b>${r.vi}</b><br><small>${r.en}</small><p><button data-dec="${r.id}">−</button> ${counts[r.id]||0} <button data-inc="${r.id}">+</button></p></div>`).join('')}</div><button id="deal" ${need!==total?'disabled':''}>Xáo và chia bài</button><button id="voice">Test giọng đọc</button><div id="game"></div></section>`; style(); bind();}
 function style(){document.querySelectorAll('section').forEach(e=>e.style.cssText='background:#171b26;border:1px solid #33384a;border-radius:22px;padding:16px;margin:12px 0');document.querySelectorAll('button').forEach(e=>e.style.cssText='border:0;border-radius:14px;background:#f4c430;color:#211b05;font-weight:900;padding:12px 14px;margin:4px');document.querySelectorAll('input').forEach(e=>e.style.cssText='width:100%;border:1px solid #33384a;border-radius:14px;background:#0f121a;color:#f6f1df;padding:12px;font-size:16px');document.querySelectorAll('.role').forEach(e=>e.style.cssText='border:1px solid #33384a;border-radius:14px;padding:10px;margin:8px 0;background:#202431')}
 function bind(){document.getElementById('num').onchange=e=>{let n=Math.max(3,Math.min(12,+e.target.value||5));while(names.length<n)names.push('Người '+(names.length+1));names=names.slice(0,n);paint()};document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>{counts[b.dataset.inc]=(counts[b.dataset.inc]||0)+1;paint()});document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>{counts[b.dataset.dec]=Math.max(0,(counts[b.dataset.dec]||0)-1);paint()});document.getElementById('voice').onclick=()=>speak('Xin chào. Tôi sẽ làm quản trò Ma Sói Một Đêm.');document.getElementById('deal').onclick=deal}
 function deal(){let cards=[];Object.entries(counts).forEach(([id,n])=>{for(let i=0;i<n;i++)cards.push(id)});cards=shuffle(cards);deck=cards.slice(0,names.length);center=cards.slice(names.length);let html='<h2>Bài người chơi</h2>'+names.map((p,i)=>`<button data-card="${i}">${p} xem bài</button>`).join('')+'<h2>Quản trò đêm</h2><button id="night">Đọc lượt ban đêm</button><button id="day">Đọc thức dậy</button>';document.getElementById('game').innerHTML=html;style();document.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>alert(names[+b.dataset.card]+': '+roleName(deck[+b.dataset.card])));document.getElementById('night').onclick=()=>speak('Mọi người nhắm mắt lại. Ma Sói thức dậy. Tiên Tri thức dậy. Ăn Trộm thức dậy. Người Gây Rối thức dậy. Kẻ Say Xỉn thức dậy. Cô Bé Mất Ngủ thức dậy.');document.getElementById('day').onclick=()=>speak('Mọi người thức dậy. Bắt đầu thảo luận và tìm Ma Sói.');}
 paint();
})();
