const $=s=>document.querySelector(s);let catalog=null,currentBook=null,currentChapter=null;const state={theme:localStorage.getItem('adk-theme')||'dark'};
const BOOK_UI={
  p201:{cover:'assets/covers/p201-cover.webp',intro:'Năm 2012, tám nữ sinh chuyển vào phòng 201 của một khu ký túc xá từng bị bỏ trống nhiều năm. Những câu chuyện cũ quanh căn phòng nhanh chóng khiến những đêm đầu tiên của họ trở nên khác thường.'},
  'ma-ki-su':{cover:'assets/covers/ma-ki-su-cover.webp',intro:'Trương An Huy, 22 tuổi, cộng tác viên tòa soạn Âm Dương, bắt đầu rong ruổi khắp nơi để viết một series về những chuyện ma và giai thoại dân gian.'},
  'an-hong-ngai':{cover:'assets/covers/an-hong-ngai-cover.webp',intro:'Bảy năm sau những ngày ở phòng 201, Quỳnh nhận được thư mời cưới của Trâm tại Hồng Ngài, một bản miền núi xa xôi nơi một chuyến đi lấy tư liệu khác vừa mất liên lạc.'},
  'huyet-chung':{cover:'assets/covers/huyet-chung-cover.webp',intro:'Vài tháng sau Hồng Ngài, một vụ án mới kéo Thi và Trung trở lại những dấu vết tưởng đã khép lại, trong khi ký ức của Trung bắt đầu xuất hiện những khoảng trống.'}
};
function applyTheme(){document.body.classList.toggle('light',state.theme==='light')}applyTheme();$('#themeToggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('adk-theme',state.theme);applyTheme()};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const pad=n=>String(n).padStart(2,'0');const uiFor=b=>BOOK_UI[b.id]||{cover:'',intro:''};const bookNo=b=>catalog.books.findIndex(x=>x.id===b.id)+1;const partNo=(b,c)=>b.chapters.findIndex(x=>x.id===c.id)+1;
function parseHash(){const raw=location.hash.replace(/^#/,'');const [book,chapter]=raw.split('/');return{book,chapter}}
async function init(){catalog=await fetch('data/catalog.json').then(r=>r.json());renderLibrary();route()}window.addEventListener('hashchange',route);
function renderLibrary(){const grid=$('#bookGrid');grid.innerHTML=catalog.books.map((b,i)=>{const u=uiFor(b);return`<section class="book-card" style="--book-glow:${b.glow}" data-book="${b.id}"><div class="book-poster-wrap"><img class="book-poster" src="${esc(u.cover)}" alt="Poster ${esc(b.title)}" loading="${i<2?'eager':'lazy'}"></div><div class="book-card-copy"><span class="book-no">QUYỂN ${pad(i+1)}</span><h2>${esc(b.title)}</h2><p>${esc(u.intro)}</p></div></section>`}).join('');document.querySelectorAll('.book-card').forEach(x=>x.onclick=()=>location.hash=x.dataset.book)}
function route(){const {book,chapter}=parseHash();window.scrollTo(0,0);if(!book){showLibrary();return}currentBook=catalog.books.find(x=>x.id===book);if(!currentBook){showLibrary();return}if(!chapter){showBook(currentBook);return}currentChapter=currentBook.chapters.find(x=>x.id===chapter);if(!currentChapter){showBook(currentBook);return}showChapter(currentBook,currentChapter)}
function showLibrary(){$('#libraryView').classList.remove('hidden');$('#bookView').classList.add('hidden');$('#readerView').classList.add('hidden');document.title='Âm Dương Kí — Horror Universe'}
function showBook(b){$('#libraryView').classList.add('hidden');$('#readerView').classList.add('hidden');const v=$('#bookView'),u=uiFor(b);v.classList.remove('hidden');v.innerHTML=`<button class="icon-button" onclick="location.hash=''" aria-label="Về thư viện">←</button><header class="book-header"><div class="book-detail-poster-wrap"><img class="book-detail-poster" src="${esc(u.cover)}" alt="Poster ${esc(b.title)}"></div><div class="book-header-copy"><p class="eyebrow">QUYỂN ${pad(bookNo(b))}</p><h1>${esc(b.title)}</h1><p class="desc">${esc(u.intro)}</p></div></header><div class="chapter-list">${b.chapters.map((c,i)=>`<section class="chapter-row" onclick="location.hash='${b.id}/${c.id}'"><div class="chapter-index">PART ${pad(i+1)}</div><h3>${esc(c.title)}</h3></section>`).join('')}</div>`;document.title=`${b.title} — Âm Dương Kí`}
async function showChapter(b,c){$('#libraryView').classList.add('hidden');$('#bookView').classList.add('hidden');const v=$('#readerView');v.classList.remove('hidden');const n=partNo(b,c);v.innerHTML=`<nav class="reader-nav"><button onclick="location.hash='${b.id}'">← ${esc(b.title)}</button></nav><header class="reader-head"><div class="series">PART ${pad(n)}</div><h1>${esc(c.title)}</h1></header><section id="storyBody" class="story-body"><p>Đang mở bản thảo…</p></section><footer class="reader-footer" id="readerFooter"></footer>`;const text=await fetch(c.file).then(r=>{if(!r.ok)throw new Error('chapter');return r.text()});$('#storyBody').innerHTML=renderStory(text);renderFooter(b,c);localStorage.setItem('adk-last',`${b.id}/${c.id}`);document.title=`${c.title} — ${b.title}`;updateProgress()}
function renderStory(text){return text.split(/\n\s*\n/).map(raw=>{const p=raw.trim();if(!p)return'';if(p==='***')return'<div class="scene-break">✦ ✦ ✦</div>';if(p.startsWith('> '))return`<p class="note">${esc(p.slice(2)).replace(/\n/g,'<br>')}</p>`;const dialogue=/^[-–—]/.test(p);return`<p${dialogue?' class="dialogue"':''}>${esc(p).replace(/\n/g,'<br>')}</p>`}).join('')}
function renderFooter(b,c){const i=b.chapters.findIndex(x=>x.id===c.id),prev=b.chapters[i-1],next=b.chapters[i+1];const prevBtn=prev?`<button onclick="location.hash='${b.id}/${prev.id}'">← PART ${pad(i)} — ${esc(prev.title)}</button>`:'<span></span>';const nextBtn=next?`<button onclick="location.hash='${b.id}/${next.id}'">PART ${pad(i+2)} — ${esc(next.title)} →</button>`:`<button onclick="location.hash='${b.id}'">Mục lục →</button>`;$('#readerFooter').innerHTML=prevBtn+nextBtn}
function updateProgress(){const el=$('#readingProgress');const max=document.documentElement.scrollHeight-innerHeight;el.style.width=(max>0?Math.min(100,scrollY/max*100):0)+'%'}window.addEventListener('scroll',updateProgress,{passive:true});init().catch(e=>{console.error(e);$('#bookGrid').innerHTML='<p>Không tải được thư viện truyện.</p>'});