const $=s=>document.querySelector(s);let catalog=null,currentBook=null,currentChapter=null;const state={theme:localStorage.getItem('adk-theme')||'dark'};function applyTheme(){document.body.classList.toggle('light',state.theme==='light')}applyTheme();$('#themeToggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('adk-theme',state.theme);applyTheme()};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function parseHash(){const raw=location.hash.replace(/^#/,'');const [book,chapter]=raw.split('/');return{book,chapter}}
async function init(){catalog=await fetch('data/catalog.json').then(r=>r.json());renderTimeline();route()}window.addEventListener('hashchange',route);
function renderTimeline(){const el=$('#universeTimeline');el.innerHTML=catalog.timeline.map(x=>`<div class="timeline-item"><b>${esc(x.year)}</b><span>${esc(x.label)}</span></div>`).join('');$('#bookGrid').innerHTML=catalog.books.map((b,i)=>`<section class="book-card" style="--book-glow:${b.glow}" data-book="${b.id}"><span class="book-no">QUYỂN ${String(i+1).padStart(2,'0')}</span><h2>${esc(b.title)}</h2><p>${esc(b.hook)}</p><div class="book-meta"><span class="pill">${esc(b.period)}</span><span class="pill">${esc(b.pov)}</span><span class="pill">${b.chapters.length}/${b.plannedChapters} chương</span></div></section>`).join('');document.querySelectorAll('.book-card').forEach(x=>x.onclick=()=>location.hash=x.dataset.book)}
function route(){const {book,chapter}=parseHash();window.scrollTo(0,0);if(!book){showLibrary();return}currentBook=catalog.books.find(x=>x.id===book);if(!currentBook){showLibrary();return}if(!chapter){showBook(currentBook);return}currentChapter=currentBook.chapters.find(x=>x.id===chapter);if(!currentChapter){showBook(currentBook);return}showChapter(currentBook,currentChapter)}
function showLibrary(){$('#libraryView').classList.remove('hidden');$('#bookView').classList.add('hidden');$('#readerView').classList.add('hidden');document.title='Âm Dương Kí — Horror Universe'}
function showBook(b){$('#libraryView').classList.add('hidden');$('#readerView').classList.add('hidden');const v=$('#bookView');v.classList.remove('hidden');v.innerHTML=`<button class="icon-button" onclick="location.hash=''">←</button><header class="book-header"><p class="eyebrow">${esc(b.seriesLabel)}</p><h1>${esc(b.title)}</h1><p class="desc">${esc(b.description)}</p><div class="book-meta"><span class="pill">${esc(b.period)}</span><span class="pill">${esc(b.genre)}</span><span class="pill">POV: ${esc(b.pov)}</span><span class="pill">${b.chapters.length}/${b.plannedChapters} chương đã đăng</span><a class="pill" style="text-decoration:none" href="wiki/?series=${encodeURIComponent(b.id)}">Wiki bộ này →</a></div></header><div class="chapter-list">${b.chapters.map((c,i)=>`<section class="chapter-row" onclick="location.hash='${b.id}/${c.id}'"><div class="chapter-index">${String(i+1).padStart(2,'0')}</div><div><h3>${esc(c.title)}</h3><p>${esc(c.teaser||'')}</p></div><div class="chapter-state">ĐỌC →</div></section>`).join('')}</div>`;document.title=`${b.title} — Âm Dương Kí`}
async function showChapter(b,c){$('#libraryView').classList.add('hidden');$('#bookView').classList.add('hidden');const v=$('#readerView');v.classList.remove('hidden');v.innerHTML=`<nav class="reader-nav"><button onclick="location.hash='${b.id}'">← ${esc(b.title)}</button><span>${esc(c.date||'')}</span></nav><header class="reader-head"><div class="series">${esc(b.seriesLabel)}</div><h1>${esc(c.title)}</h1>${c.subtitle?`<div class="subtitle">${esc(c.subtitle)}</div>`:''}</header><section id="storyBody" class="story-body"><p>Đang mở bản thảo…</p></section><footer class="reader-footer" id="readerFooter"></footer>`;const text=await fetch(c.file).then(r=>{if(!r.ok)throw new Error('chapter');return r.text()});$('#storyBody').innerHTML=renderStory(text);renderFooter(b,c);localStorage.setItem('adk-last',`${b.id}/${c.id}`);document.title=`${c.title} — ${b.title}`;updateProgress()}
function renderStory(text){return text.split(/\n\s*\n/).map(raw=>{const p=raw.trim();if(!p)return'';if(p==='***')return'<div class="scene-break">✦ ✦ ✦</div>';if(p.startsWith('> '))return`<p class="note">${esc(p.slice(2)).replace(/\n/g,'<br>')}</p>`;const dialogue=/^[-–—]/.test(p);return`<p${dialogue?' class="dialogue"':''}>${esc(p).replace(/\n/g,'<br>')}</p>`}).join('')}
function renderFooter(b,c){const i=b.chapters.findIndex(x=>x.id===c.id),prev=b.chapters[i-1],next=b.chapters[i+1];const prevBtn=prev?`<button onclick="location.hash='${b.id}/${prev.id}'">← ${esc(prev.title)}</button>`:'<span></span>';const nextBtn=next?`<button onclick="location.hash='${b.id}/${next.id}'">${esc(next.title)} →</button>`:`<button onclick="location.hash='${b.id}'">Mục lục →</button>`;$('#readerFooter').innerHTML=prevBtn+nextBtn}
function updateProgress(){const el=$('#readingProgress');const max=document.documentElement.scrollHeight-innerHeight;el.style.width=(max>0?Math.min(100,scrollY/max*100):0)+'%'}window.addEventListener('scroll',updateProgress,{passive:true});init().catch(e=>{console.error(e);$('#bookGrid').innerHTML='<p>Không tải được thư viện truyện.</p>'});